### ISSUE TITLE
Recipe for iron spool

### ISSUE THREAD

**Issue by G-Stav** [mrh0/createaddition#103]
**Describe the bug**

Iron spools have been removed but the recipe still remains.

"Parsing error loading recipe createaddition:crafting/iron_spool"

**To Reproduce**
Load the mod with output log on.

**Additional context**
- Mod version: 20210711a
- Forge version: 36.1.32
- Create version: 0.3.2a

**Comment by mrh0** [comment]
Fixed in 20210713a
