### ISSUE TITLE
Crafttweaker support for the rolling mill

### ISSUE THREAD

**Issue by onetoxiczombie** [mrh0/createaddition#109]
The title kinda says it all. After looking at the recipes I would assume you can do it via datapack but crafttweaker support would be nice as the rolling mill is unique in terms of create stuff. Also if there is already support and I'm just missing it I'm sorry.

**Comment by mrh0** [comment]
There isn't any official integration but you can still do it. This is from a user on my Discord:
<recipetype:createaddition:rolling>.addJSONRecipe("recipename", {
    "type": "createaddition:rolling",
    "result": {
        "item": "modid:item",
        "count": 1
    },
    "input": [
        {
            "item": "modid:item"
        }
    ]
});
