### ISSUE TITLE
Rolling Mill issue with Optifine

### ISSUE THREAD

**Issue by FLGOBon** [mrh0/createaddition#11]
Optifine absolutely hates the Rolling Mill and refuses to load it, It crashes when trying to load the shaft that runs through the centre. crash report states "Crashed while trying to render block entity"

**Comment by FLGOBon** [comment]
Sorry I Mistook the Rolling Mill for the Mechanical Press

**Comment by mrh0** [comment]
Please provide a crash report

**Comment by FLGOBon** [comment]
[crash-2021-02-23_19.43.30-client.txt](https://github.com/mrh0/createaddition/files/6037406/crash-2021-02-23_19.43.30-client.txt)

**Comment by mrh0** [comment]
Incompatible Create version.
