### ISSUE TITLE
Induction Heater not working

### ISSUE THREAD

**Issue by helpmeitsnotdownloading** [mrh0/createaddition#110]
The induction heater ceases to work when a furnace engine is attached to the furnace that the induction heater is powering. This is true for the regular furnace and the blast furnace.

Place down a furnace or a blast furnace. Then, place down an induction heater and power it. The furnace should be lit up by the heater. Next, place a furnace engine down on it. If you click on the furnace that the furnace engine is attached to, you will see that the flame isn't being replenished and will eventually die out.

- Mod version: Not sure if this is the mod's version, but 20210713a
- Forge version: 36.1.4
- Create version: 0.3.2b

**Comment by Ch1216** [comment]
Its supposed to be like that (Induction heaters not working when attached to a furnace engine) It was mentioned originally mentioned in tooltips before the induction heaters got ponder, you can also enable it working with furnace engines in the config

**Comment by helpmeitsnotdownloading** [comment]
> Its supposed to be like that (Induction heaters not working when attached to a furnace engine) It was mentioned originally mentioned in summary before the induction heaters got ponder, you can also enable it working with furnace engines in the config

oh, dang im just stupid

**Comment by GamerSupreme1** [comment]
> Its supposed to be like that (Induction heaters not working when attached to a furnace engine) It was mentioned originally mentioned in summary before the induction heaters got ponder, you can also enable it working with furnace engines in the config

how tho?
