### ISSUE TITLE
Stockpile Switch but for Tanks and Energy Storage

### ISSUE THREAD

**Issue by laserlemons** [mrh0/createaddition#111]
I was disappointed to see that the Stockpile Switch doesn't work with liquids or energy. That'd be a nice thing to have for automation. Any chance you could add something like that?

**Comment by mrh0** [comment]
Never used the stockpile switch myself but I'll look into it.

**Comment by laserlemons** [comment]
Fluids were implemented into the stockpile switch in Create.
