### ISSUE TITLE
Freshly build mod crashes the game

### ISSUE THREAD

**Issue by Lgmrszd** [mrh0/createaddition#112]
**Describe the bug**
When I'm trying to build this mod and run it (`./gradlew runClient`), the game crashes after creating and loading the world.
This worked perfectly fine two days ago.
I cloned this repo once again but issue persists.
Maybe this is not issue with the mod itself but with Immersive Engineering, as it seems according to log, but again, nothing was changed in the `build.gradle` so I don't even know why it's not working anymore.
If it's IE issue, then I think this issue needs to be reproduced with IE only

**To Reproduce**
 - Clone this repo
 - `./gradlew runClient`
 - Create a new world

**Additional context**
[Crash log](https://gist.github.com/Lgmrszd/1445e469486cd241f369603851c003a6)

**Comment by mrh0** [comment]
It's definitely an issue with IE, however, it works just fine for me. You could try changing the IE version in build.gradlew

**Comment by Lgmrszd** [comment]
Switching to the 135 IE build (`231951:3326143`) fixed this issue for me, as it seems that they moved to Forge 36.1.0 with it. Not sure why the crash never happened before, as well why it is happening for me now even on fresh instances, but I suggest to move to this or never build just in case.
