### ISSUE TITLE
Flywheel updated to 0.2.0 and createaddition doesn't want to run

### ISSUE THREAD

**Issue by jawsawn** [mrh0/createaddition#114]
**Describe the bug**
Create and Flywheel just updated today and because of flywheel updated to 0.2.0 createadditions crashes the game with the crash report:
![image](https://user-images.githubusercontent.com/8208988/127720948-e11009ea-aa7f-4ff6-84a1-4b0b5a126ad2.png)

**To Reproduce**
Update flywheel
Get crash screen

**Additional context**
- Mod version:latest
- Forge version:latest
- Create version:latest

**Comment by Corvus20** [comment]
Can confirm, I am getting this issue too.

**Comment by KatoNamus** [comment]
+1 Confirmation

**Comment by mrh0** [comment]
You are not running the latest CC&A update to 20210801b
