### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Catomax262** [mrh0/createaddition#118]
**Describe the bug**
Here's the crash log.

**To Reproduce**
https://pastebin.com/aUMdDFhD

**Additional context**
- Mod version: i don't remember
- Forge version: i don't remember
- Create version: 0.3.2c

**Comment by mrh0** [comment]
link broken

**Comment by Catomax262** [comment]
Is that a frickin reason to close it?

**Comment by mrh0** [comment]
This is a good example of how to not make a bug report. If you want me to put in the effort to help you, you should at least put in the effort to tell me what versions you are on, when (launch, world loading, or in-game), and provide a log file.

**Comment by Catomax262** [comment]
Just wait man i am not in the mood of using my PC
