### ISSUE TITLE
Charging chromatic compound is a pickaxe??

### ISSUE THREAD

**Issue by erisdev** [mrh0/createaddition#119]
Just as the title says, it's usable as a pickaxe wherever a pickaxe can be used. It even works for Farmer's Delight cutting board recipes for breaking apart brick blocks.

**Additional context**
- Mod version: 20210801b
- Forge version: 36.2.0
- Create version: 0.3.2c

**Comment by mrh0** [comment]
mistake, supposed to be for the hammer

**Comment by erisdev** [comment]
Aha, makes sense. I had a pretty funny moment realizing what was going on. Thanks for the response!

**Comment by mrh0** [comment]
in 20210810a
