### ISSUE TITLE
Connecting connectors causes all entities to become invisible, as well as various other visual glitches.

### ISSUE THREAD

**Issue by etroozo** [mrh0/createaddition#124]
**Describe the bug**
When clicking on a connector with a spool, all entities - mobs, drops, the player model, etc. - instantly disappear, and a bright bar appears on the horizon. This persists even after connecting to another node, and reloading the world. The bug only goes away once the game is restarted.
Video: https://imgur.com/a/ZbwGNq4

**To Reproduce**
I run a ton of mods - I assume one of them is causing a conflict. Graphical mods are optifine, flywheel, fast suite, ferritecore, entity culling, and some others. So I guess step one would be to download my modlist (https://pastebin.com/e2MH3eMA) and step two would be to click on a connector with a spool.

**Additional context**
- Mod version: 20210810a
- Forge version: 36.2.0
- Create version: 0.3.2d

**Comment by mrh0** [comment]
What shader pack are you running? Also, does this issue persist if you disable the shader pack (none or internal)

**Comment by etroozo** [comment]
> What shader pack are you running? Also, does this issue persist if you disable the shader pack (none or internal)

I usually use complementary. It works when I totally disable shaders (don't know why I didn't think to try that), but in all the other shaders I tried the problem persists, even with internal.

**Comment by mrh0** [comment]
Removed the wire renderer for holding a wire spool. Fixed in 20210819a.
