### ISSUE TITLE
Add disabling Sphalerite to config file

### ISSUE THREAD

**Issue by Koku0** [mrh0/createaddition#125]
I want to add my own sphalerite vein to my modpack in the Nether, and I can't disable or adjust Create Crafts and Addition's sphalerite vein without going into the appropriate .json file and changing the details myself.

Of course that's easy to do, but I don't think that editing the .json file of your mod then putting that modified version up for download as part of my pack is allowed.

An option in the config would solve these problems, and allow for greater user control over the features of the mod, which I don't think is a bad thing.

**Comment by mrh0** [comment]
There are several ways to do this: Datapack, CraftTweaker, and KubeJS to name a few common ones.
