### ISSUE TITLE
A handful of connector issues, Goggles show incorrect values and a couple other bugs, questions and suggestions

### ISSUE THREAD

**Issue by McFow1er** [mrh0/createaddition#126]
Hey man, I would like to say before any of this that love the work you've done with this mod, I've been playing around with it for a good two weeks now and have a couple installations using the alternators in place with a few other ideas planned but I was a bit disappointed and confused by a few settings that didn't really hold and figured I'd come by and ask about them.
I'm running this in a large mod pack on a server so this may provide some additional insight for why some things are wonky?? But I did do my research into why certain things were happening as they seemed as though they should have been just fine but I've identified that all of these stem from the code itself in one way or another, or at least I believe so as these are the only culprits I see being the reasons for these.

Also tell me if I should actually separate these into individual posts or not cause, yeah that's a lot down there.

**Okay, onto the actual info:**
- **BUG:** Connector & Conductor transfer rates are, as far as I can tell, unintentionally limited to 4096 FE/t.
From what I could gather looking through the code this limitation comes from the max transfer being defined by [`MAX_BUFF` in EnergyNetwork.java](https://github.com/mrh0/createaddition/blob/main/src/main/java/com/mrh0/createaddition/energy/network/EnergyNetwork.java#L25) instead of pulling the maximum from the value defined by the config file. I discovered this when I and a friend decided to use the connectors as our power network as the other options we have available to us aren't as pleasant to look at nor could be hid in plain sight so we tried extending the max transfer amount to 25k to be balanced that "these aren't supposed to be the best or worst we have" only to discover they only let through a max of 4096 despite the fact that the config values stuck, this only affects the connectors and conductors, everything else can transfer to 3rd party mod energy transfer items just fine. Also looking forward to the introduction of wire energy loss and the electrum wires!

- **QUESTION:** While on the topic of power transfer, would it be possible to change the energy transfer methods of the various blocks to allow for their internal capacity to be smaller than their transfer rate while maintaining the config defined transfer rate as a max throughput? As it currently stands the reserve capacity acts as a seemingly unintentional bottleneck for transfer rates of energy in and out of blocks if it's smaller.
I was thinking something along the lines of going from the current `input > reserves > output` to `input & reserves > max output transfer clamp` as currently the only way to reach peak output of any block is for the reserve capacity to match or exceed the transfer rates. This was a rather limiting factor I ran into regarding the Motor, Alternator and Accumulator as well as the Charger, according to a friend, I haven't tested anything else regarding this but I would assume the same would happen. 

- **BUG:** While trying things out I also discovered that the goggles do not provide accurate info regarding changed config values that are only on the server's side such as SU capacity/use and FE generated per tick.
I have not tested if these values update if applied to the client config but I assume they should and would? Only the energy network transfer values appeared to be correct, at least as far as I could tell given the hard cap of 4096 internally.

- **BUG/LIMITATION:** Motor and Alternator RPM is [limited to 256 RPM max by the config definer](https://github.com/mrh0/createaddition/blob/main/src/main/java/com/mrh0/createaddition/config/Config.java#L82).
This in particular made me quite sad when I discovered this trying to set the value past 256 only for it to reset to it as Create's RPM limit can be extended much further, it would be nice if the max value possible was changed to match that of Create as this would enable the ability to have high stress and energy amounts at higher than default RPM values in Create, while also allowing for reasonable but meaningful values when run at lower RPM values along with the suggestion below.

- **SUGGESTION:** Separate RPM limits for the Motor and Alternator with master SU and FE values balanced based off highest RPM.
Using separated RPM limits for the Motor and Alternator with master SU and FE values would allow for balancing of everything based off of the highest RPM value between the two and not allow for a motor to infinitely power an alternator, effectively taking the current system and just applying a limiter to one so that it can only go so fast but maintains equivalent SU/FE values. I would personally use this system to allow the alternators to spin as fast as the currently active Create max RPM config allows (4096 in the case of our server currently) and apply a decent value of power to make that speed and amount of stress worth the effort of achieving while only allowing the motor to rotate at a max of say 512-1024 RPM so it's only able to run an Alternator at a quarter of full power for looped power comparison.

- **SUGGESTION:** In game SU capacity manipulation of Motors for energy efficiency.
Having the ability to change the SU capacity of a motor based off of the master SU and FE values defined above with alteration of the values based on what it's RPM limit (and thus it's usual top SU capacity) is through some secondary menu means to the RPM gauge and through computer terminals as a `.torque()` parameter would be amazing for using only as much power as you really have to for things, just as you would in the real world. (This value would represent `max SU @ max Motor RPM`)
For example imagine an Alternator had a max of 256 RPM, 4096 SU and 1000 FE/t and a Motor had a max of 128 RPM so it would only report it's "max" values as being half at 2048 SU and 500 FE/t, you could increase the SU capacity to 4096 which would raise the energy usage to 1000 FE/t or drop it to say 512 SU which would drop the energy consumption to 125 FE/t all while it stays at 128 RPM max keeping balanced, though probably a good idea to have a configurable max SU multiplier... Through this and a bit of CC code you could for a good use case, make a very energy efficient, only active when needed elevator made of either fans or a rope winch, only delivering exactly as much RPM and SU as needed for as little power draw as possible.

**Additional context**
- Mod version: createaddition-1.16.5-20210819a
- Forge version: 1.16.5-forge-36.2.2
- Create version: create-mc1.16.5_v0.3.2d

**Comment by mrh0** [comment]
Thanks for the thorough report.
1. Will be addressed in the next update.
2. This is just the same as raising the main buffer, you would just have another "output" buffer.
3. Know issue, for now just make sure to sync server and client configs.
4. Will be addressed in the next update.
5. It's this way because separating them would make it very easy to accidentally create an infinite energy loop unless you are careful. (many people reported inf energy loops before I merged it into one value)
6. Yes this would be great however as you say this requires some sort of new type of interface and this also adds complexity for new users.

**Comment by mrh0** [comment]
I think everything in here (except config sync issue) has been adressed by now
