### ISSUE TITLE
Description electric motor

### ISSUE THREAD

**Issue by albertosaurio65** [mrh0/createaddition#130]
The stress capacity of the electric motor does not appear

I do not know if it is a bug or it does not have it, but it does not appear if it is low, medium or high

1.16.5
Forge
Minecraft español españa ES_es
Create: last version

![2021-09-01_17 17 47](https://user-images.githubusercontent.com/70109413/131697956-950e430d-8d58-4758-a69c-74a84dade01f.png)

**Comment by mrh0** [comment]
Fixed in next update.
