### ISSUE TITLE
Different levels of electric motors

### ISSUE THREAD

**Issue by albertosaurio65** [mrh0/createaddition#132]
In my opinion, adding 3 different levels of electric motors would be very helpful for large constructions and mechanisms, and it is currently my favorite way to generate SU, since it is compact and does not need extra mechanisms to generate SU, it would be something like this: tier 3 would have a high stress capacity and tier 1 would have a low capacity, like the current one, and it goes without saying that tier 2 would be something in between, while the higher the level, the more complex it would be to craft

**Comment by mrh0** [comment]
No, I'm not going to do that. I'm not doing tiers of anything, same as in Create.
