### ISSUE TITLE
Crash generating mineshaft minecarts (possible Quark incompat?)

### ISSUE THREAD

**Issue by Kaleidio** [mrh0/createaddition#133]
**Describe the bug**
instantly crashes whilst generating chunks in a world whilst playing, seemingly because of train mixins your mod is failing to cooperate.  The only other mods present in my pack that modify trains are Create, More Minecarts and Quark.  But as you can see these don't appear in the pathtrace.

Only started happening after 20210902a.  was using 20210819a before just fine

**To Reproduce**
Generate a world and try finding a Mineshaft with a Minecart

LOGS: 
https://pastebin.com/Bqg3dhyA

**Additional context**
- Mod version: 20210902a
- Forge version: 36.2.2
- Create version: 0.3.2d

**Comment by mrh0** [comment]
I don't do anything with minecarts, looking at the log it does look like it is with Create and a incompatibility with another mod.

**Comment by Kaleidio** [comment]
It only triggers when I have your mod fully up to date. It has to be something on your side.

**Comment by Kaleidio** [comment]
I'll just mention this issue on their repo instead I guess...
