### ISSUE TITLE
overcharged hammer boing

### ISSUE THREAD

**Issue by ironfprcefeild** [mrh0/createaddition#140]
throwing the overcharged hammer beneath you while standing throws you in the air, also could give slow-falling. this would be fun simple and makes the hammer a bit more worth it.

**Comment by mrh0** [comment]
Yes, you are not alone in this, I will try to spice it up a bit.

**Comment by mrh0** [comment]
As of 20210930a the hammer applies a 'Shocked' effect when hitting a mob.
