### ISSUE TITLE
electric sparks

### ISSUE THREAD

**Issue by ironfprcefeild** [mrh0/createaddition#141]
items transmitting current, (wires alternators ect) emit a spark particle, this would be nice to just show that power is moving without needing a multimeter. and it would be a cool ambience in factory's

you could also make more intense devices deal electrical damage and require rubber gloves or something similar to be in the inventory to avoid it

**Comment by mrh0** [comment]
1. Could be cool but, would have too large of a performance overhead.
2. I've stated before that i dislike that mechanic (Immersive Engineering) and will not implement it.
