### ISSUE TITLE
Charging Station Automation

### ISSUE THREAD

**Issue by Ganpan14O** [mrh0/createaddition#142]
The charging station being able to accept input and output from things like hoppers, funnels, chutes and such would be nice to have, for things such as using a mod such as ender storage to charge things in a bag, or automating overcharged alloy.

**Comment by mrh0** [comment]
Yes, I'm eventually going to rework the Charging Station to behave like a Depot.

**Comment by mrh0** [comment]
Tesla Coil (which can be automated) replacing the Charging Station by as of 20211122a.
