### ISSUE TITLE
Ports, addon for portals to transport items, liquids, and power between dimensions 

### ISSUE THREAD

**Issue by DevonRumbold** [mrh0/createaddition#143]
Use them by placing them on portal blocks in a working nether portal frame to replace the portal block, but not break the portal, subsequently replacing the portal block in the other dimension with a linked Port both sharing an inventory that can contain either items, liquids, or power from input/output blocks connected to the ports on either side (possibly also preventing other portals from linking to them to prevent weirdness). 

This would allow pipes, conveyors, shafts, power lines/connectors to be connected using nether portal frames as a hub (also for the aesthetic of pipes and cables going into portals). There could alternatively be individual item, liquid, shaft, and energy ports to prevent mix-ups and conflicting input/outputs.

**Comment by mrh0** [comment]
I had an idea to add Teleporting Funnels, crafted using Overcharged Alloy they would have a code (like wireless Redstone in Create) and link two funnels together. I might do this in the future.

**Comment by DevonRumbold** [comment]
Tbh this idea was more for the aesthetic of pipes and such going into portals rather than a dimensional item transport solution, plus it turns nether portals from this esoteric magical thing to an infrastructure hub integrated into the technology of the build.
