### ISSUE TITLE
Alternator Tweaking

### ISSUE THREAD

**Issue by helpmeitsnotdownloading** [mrh0/createaddition#144]
When you put a large amount of SU into a set of alternators, the loss of SU when converting SU to electricity is absolutely enormous (81,920 SU > 61,440 SU) I know that loss of SU during converting it into electricity is an intended feature, but is there a way to make it so that the alternator is more efficient? e.g alternator upgrades? Because there isn't really that big of an upside to using wires over shafts, in fact it's probably worse because of the huge loss of power when converting rotational power to electricity. If you can't add another tier to alternators, could you at least make them more efficient? I know configs exist but I feel like alternators should be more efficient in the unaltered mod. (And no, I don't mean making it 1:1 ratio, but just more efficient)

**Comment by mrh0** [comment]
There is a config option for it, It called 'generatorEfficiency' if I remember correctly, just make sure to change it on both the server and client.
