### ISSUE TITLE
Unbalanced Smelting

### ISSUE THREAD

**Issue by DoctorAbe42** [mrh0/createaddition#146]
**Describe the bug**
When a furnace engine is run into a furnace through alternators, you can smelt 15x the resources with the same amount of fuel.

**To Reproduce**
Run a furnace engine powered by a Furnace Burner into a speed controller set to 256. Run the output of the speed controller into four Alternators. Run the four Alternators into an accumulator and then an Induction Heater connected to a Furnace. The connected Furnace will smelt 15x the resources that a furnace with the same fuel.
Recommended fix: increase the power requirement of the Induction Heater by 2x.

**Additional context**
- Mod version: Unknown (Latest at the time of submission)
- Forge version: 36.2.0
- Create version: 0.3.2

**Comment by mrh0** [comment]
Induction Heater energy draw 16fe/t -> 256fe/t in 20210930a.
