### ISSUE TITLE
Is there a way to move fe power without wires?

### ISSUE THREAD

**Issue by Aiife** [mrh0/createaddition#157]
I need to be able to do this because the wires break on a moving contraption, is there some block i'm unaware of that offers that feature? And if not, is anyone aware of a way to do what I'm attempting?

**Comment by mrh0** [comment]
No, in this mod, but there might be in some other mod.

**Comment by Lgmrszd** [comment]
It's possible to do with IE's capacitors for example, but I don't think it is possible to do with just this mod. Accumulator can accept energy without wires, but not release it.
![2021-11-04_00 04 34](https://user-images.githubusercontent.com/16291541/140192784-160b063f-e7b0-4c9c-9da9-28e1e9337deb.png)
@mrh0 is it possible to make one side of accumulator to extract the energy?
