### ISSUE TITLE
Honey Cake recipe only accepts honey from Create

### ISSUE THREAD

**Issue by Lgmrszd** [mrh0/createaddition#158]
**Describe the bug**
It is impossible to craft Honey Cake with Honey from other mods (for example Resourceful Bees), while Create supports Honey fluids from other mod

**To Reproduce**
Install Create, this mod and Resourceful Bees
Attempt to craft Honey Cake with Honey from Resourceful Bees

**Proposed solution**
To use `"fluidTag": "forge:honey"` instead of `"fluid": "create:honey"` in recipes/filling/honey_cake.json

**Additional context**
- Mod version: 20211023a
- Forge version: 36.2.8
- Create version: 0.3.2f

**Comment by mrh0** [comment]
Fixed in 20211122a.
