### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by Mblackminer** [mrh0/createaddition#159]
**Describe the bug**
cannot register diamond sandpaper

**Additional context**
- Mod version:0930a
- Forge version:36.2.8
- Create version:0.3.2
[crash-2021-11-04_12.04.03-fml.txt](https://github.com/mrh0/createaddition/files/7473572/crash-2021-11-04_12.04.03-fml.txt)
f

**Comment by mrh0** [comment]
You are running an old version of CC&A, update to 20211023a and Create to 3.2f
