### ISSUE TITLE
Induction Heater flickers

### ISSUE THREAD

**Issue by weedeej** [mrh0/createaddition#161]
**The bug**
It was working for me before but now, Induction heater does not heat the furnace and just flickers as if it *lacks* the energy it needs even running at 60fe/t (creative motor)

**To Reproduce**
Use induction heater as normal. It was working for me before. Even with creative motor, It just flickers.

**Additional context**
- Mod version: 20211023a
- Forge version: 36.2.8
- Create version: v0.3.2

https://user-images.githubusercontent.com/87055977/140657950-5e9c0086-17ce-46d9-8041-2526bf929d1b.mp4

https://user-images.githubusercontent.com/87055977/140657970-927617af-b52b-4423-b5fe-48038716f579.mp4

**Comment by mrh0** [comment]
Fixed in 20211122a.
