### ISSUE TITLE
Tesla Coil deaths are unstranslated

### ISSUE THREAD

**Issue by Ch1216** [mrh0/createaddition#167]
**Describe the bug**
When someone dies to a tesla coil "death.attack_tesla_coil" appears in chat
When someone dies to a tesla coil but also got hit by something else before "death,attack,tesla_coil.player" appears in chat

**To Reproduce**
To reproduce the first death message die to the tesla coil
To reproduce the second death message die to the tesla coil while also getting hit by something earlier

**Additional context**
- Mod version: 20211122a
- Forge version: 36.2.8
- Create version: 0.3.2f

**Comment by mrh0** [comment]
forgot :/
