### ISSUE TITLE
Charging station

### ISSUE THREAD

**Issue by Druivenpasta** [mrh0/createaddition#168]
Well, I've been experimenting and I just found out that the charging station has no automatic input.
So I wanted to ask (since I have my own modpack and I want to give overcharged alloy a better use) if you can make charging stations input from mekanism transporters, chutes, mechanical arms et cetera.

**Comment by Druivenpasta** [comment]
Oh just saw the other issue that says the same lol

**Comment by mrh0** [comment]
The charging station has been replaced with the tesla coil (which is capable of what you ask) as of 20211122a.
