### ISSUE TITLE
Refined Storage Wireless Grid doesn't charge

### ISSUE THREAD

**Issue by DaLumma** [mrh0/createaddition#173]
**Describe the bug**
When I put the Refined Storage Wireless grid onto a depot which has a tesla coil above it the wireless grid doesn't charge but the coil has the activation animation. If I remember correctly the old charger was able to do that

**To Reproduce**
Put a tesla coil above a depot, connect it to power and put a wireless grid on the depot.

**Additional context**
- Mod version: 20211122b
- Forge version: 36.2.8
- Create version: v0.3.2f

**Comment by mrh0** [comment]
Fixed in 20211202a.
