### ISSUE TITLE
Tesla Coil does not charge Railgun

### ISSUE THREAD

**Issue by EuSuntMarian** [mrh0/createaddition#174]
**Describe the bug**
The Tesla Coil does not charge items like the railgun from Imersive Engineering. It will look like the coil is charging, but nothing happens to the railgun.

**To Reproduce**
Steps to reproduce the behavior: Have a railgun under a tesla coil

**Additional context**
- Mod version:createaddition-1.16.5-20211122b.jar
- Forge version: 36.2.4
- Create version:create-mc1.16.5_v0.3.2g.jar

**Comment by Koku0** [comment]
I've found this to be an issue too, not just with the railgun, but with the Capacitor Backpack and the Chromatic Compound.
What's your mod list?

**Comment by mrh0** [comment]
Fixed in 20211202a.
