### ISSUE TITLE
Computercraft's modems only connect to the motor when its shaft points north, south, east or west

### ISSUE THREAD

**Issue by Frankaos333** [mrh0/createaddition#176]
**Describe the bug**
As per title, CC's modems won't connect to motors when they're oriented up or down, rendering them impossible to control. It isn't a gamebreaking issue since converting their motion from horizontal to vertical just requires a gearbox, but it is weird.

**To Reproduce**
1 Place an electric motor with its shaft pointing up or down
2 Try connecting a CC modem to it

**Additional context**
- Mod version: 20211202a
- Forge version: 36.2.9
- Create version: 0.3.2g
- ComputerCraft version: 1.98.2

**Comment by mrh0** [comment]
Fixed in 20211215b.
