### ISSUE TITLE
The config file has both value using the same config key 'connector_capacity' when it shouldn't be.

### ISSUE THREAD

**Issue by pharaun** [mrh0/createaddition#177]
**Describe the bug**
https://github.com/mrh0/createaddition/blob/main/src/main/java/com/mrh0/createaddition/config/Config.java#L172-L176

Line 176 should be probs set to 'connector_max_length' not 'connector_capacity' since its already used above on line 173. for capacity.

**To Reproduce**
Set connector_capacity to 256, i can now have my wire span 256 block and transfer 256fe/t, set it to 12, my wire spans 12 blocks and transfer 12fe/t

**Additional context**
- Mod version: Latest
- Forge version: Latest
- Create version: Latest 1.16.5

**Comment by mrh0** [comment]
Fixed in 20211215b.
