### ISSUE TITLE
Config for Heater

### ISSUE THREAD

**Issue by ZEROX7** [mrh0/createaddition#18]
would it be possible to make it a config to replace the IE heater?
and does the induction heater work on blast furnace?
and would it be bossible to make it work with multiblocks like blast furnace or kiln

**Comment by mrh0** [comment]
This is a difficult one, I made the heater as a replacement for the IE heater as with it you could create infinite energy with an Alternator and Furnace Engine. I don't currently have a solution to this problem.

**Comment by ZEROX7** [comment]
and waht about driving blast furnace/ mmultiblock kiln? it would make it better as the old one so not a downgrade XD

**Comment by mrh0** [comment]
The IE external heater can't be used on the multiblock, so I don't quite understand what you mean.
