### ISSUE TITLE
Unexpected error while registering entry createaddition:diamond_grit_sandpaper to registry minecraft:item

### ISSUE THREAD

**Issue by M3veronMast3r** [mrh0/createaddition#180]
[crash-2021-12-21_09.49.34-fml.txt](https://github.com/mrh0/createaddition/files/7750966/crash-2021-12-21_09.49.34-fml.txt)
Added the Mod to my Modpack but it crashes every time because of this mod.

**Comment by mrh0** [comment]
You are running a old version.
