### ISSUE TITLE
Lava fluid as fuel in the crude burner?

### ISSUE THREAD

**Issue by The-Konester** [mrh0/createaddition#182]
I know that it’s mean for oils, but it would be very useful for anyone with a large supply of lava. You can already use lava buckets as a fuel source, and setting up a system to fill up buckets with lava to put them in a furnace burner and then taking the bucket out again and refilling it just sounds tedious.

**Comment by mrh0** [comment]
It is recipe-based, so you can add this yourself using crafttweaker, KubeJS, or a data pack.
