### ISSUE TITLE
Rolling Mill only giving 1 wire instead of 2

### ISSUE THREAD

**Issue by LegendaryTot** [mrh0/createaddition#186]
**Describe the bug**
Rolling Mill should be giving 2 wires as result, but it's only giving 1. Does not seem to respect count in recipe result.

**To Reproduce**
Put any plate in the rolling mill.

**Additional context**
- Minecraft version: 1.18.1
- Mod version: 20220101a
- Forge version: 39.0.9
- Create version: 0.4b

**Comment by mrh0** [comment]
fixed in 20220105a.
