### ISSUE TITLE
Rolling Mill Doesn't Drop When Mined

### ISSUE THREAD

**Issue by digitaltrucker** [mrh0/createaddition#188]
**Describe the bug**
As title states, mining a rolling mill drops nothing.  I've tried both iron and diamond picks.  So far, other machines drop as expected.

**To Reproduce**
Attempt to mine a rolling mill.

**Additional context**
- Mod version:  1.18.1-20220101a
- Forge version:  39.0.10
- Create version:  0.4b

**Comment by digitaltrucker** [comment]
I've found that alternators, motors, and connectors won't drop either.  I've also noticed that they take a very long time to break.

**Comment by mrh0** [comment]
fixed in 20220105a.
