### ISSUE TITLE
Game crashes when placing an induction heater on a furnace

### ISSUE THREAD

**Issue by iubaldo** [mrh0/createaddition#190]
This bug occurred while playing on a server running the "Team Rustic 4" modpack for 1.18.1

Crash log: https://pastebin.com/YjhzGTU5

Place an induction heater on top of a vanilla furnace, and the game crashes.

- Mod version: 1.18.1-20211230c
- Forge version: 39.0.9
- Create version: 0.4b

**Comment by mrh0** [comment]
you are on an old version, update.
