### ISSUE TITLE
[1.16.5] Please add a FE to RPM config for the Electric Motor

### ISSUE THREAD

**Issue by Elfinlocks** [mrh0/createaddition#191]
At the moment, the motor can only have its minimum consumption configured, which does not scale it properly from that minimum consumption point (ie, even if it takes a minimum of 20 fe/t, it still caps at 80 fe/t to produce 256 RPM). Due to this, the config adjustment to set the minimum FE consumption is somewhat worthless.

**Comment by mrh0** [comment]
use Config properties "fe_conversion" and "baseline_stress" to balance the Motor and Alternator.
