### ISSUE TITLE
Furnace burner does not consume fuel items

### ISSUE THREAD

**Issue by dav20011** [mrh0/createaddition#196]
**Describe the bug**
The furnace burner does not consume any items and thus burns forever once it received fuel.

I am pretty sure [this](https://github.com/mrh0/createaddition/blob/0f989612777ebf69fd6dd2522dbc0007f3f94362/src/main/java/com/mrh0/createaddition/blocks/base/AbstractBurnerBlockEntity.java#L75) line is the problem. Reducing the fuel by 0 does nothing.

**Additional context**
- Mod version: 20220111a
- Forge version: 39.0.18
- Create version: 0.4c

**Comment by mrh0** [comment]
Thanks, Fixed in 20220111b.
