### ISSUE TITLE
Furnace Burner is incompatible with Induction Heater

### ISSUE THREAD

**Issue by AndyClausen** [mrh0/createaddition#198]
**Describe the bug**
First off, the tooltip info seems to depend on the client-side config, which is odd and seems unintended. I've enabled `heater_furnace_engine_enable` both on client and server, but hooking up the induction heater still doesn't turn it on. I have a fully charged accumulator with nothing else connected.

I would make a PR, but I have no idea how the internals of configs work in MC... I'd be willing to help though.

**To Reproduce**
Set up like this:
![2022-01-14_15 01 23](https://user-images.githubusercontent.com/16802212/149527569-d715908f-3100-4920-9486-78aaef093bae.png)

**Additional context**
- Mod version: 1.18.1-20220111b
- Forge version: 1.18.1-39.0.9
- Create version: 1.18.1_v0.4c

**Comment by mrh0** [comment]
The config thing is a known issue, however, have bothered to fix it yet :/
By default, the heater won't work on furnaces connected to a Furnace Engine, this is because it could potentially cause an infinite energy loop when using it and an Alternator. It can be re-enabled in the configs.

**Comment by AndyClausen** [comment]
I'm aware of the implications, and will make sure it's not generating more energy than it's consuming through config. But I have set `heater_furnace_engine_enable` to `true` on both client and server, so should that not make it work? Or is there another config flag I'm missing?

I've forked the repo and will be debugging a bit with a local build, I'll see what I can find.

**Comment by AndyClausen** [comment]
Okay, I see the problem now.

The heater only connects to classes that extend `AbstractFurnaceBlockEntity`, and I had placed a Furnace Burner which extends `AbstractBurnerBlockEntity`. It worked somewhat fine once I replaced it with a regular furnace, although it wasn't really functioning well due to the default consumption/input ratio, but that's configurable.

I'm looking at the possibility of including burner blocks (furnace and crude) for the heater, but before I continue and make a PR - is this something you'd even want? It seems like it's a somewhat smooth transition by adding `dataAccess` like in `AbstractFurnaceBlockEntity` and some light casting and type checking.

**Comment by mrh0** [comment]
That's right, I forgot. I had to redo the burners in 1.17+. Don't make a PR yet, I'll have to think about how I want that to work, or if I should deprecate that config option altogether. Thanks for finding this.

**Comment by AndyClausen** [comment]
No worries man, if there's anything I can do to help, feel free to hit me up :)

**Comment by mrh0** [comment]
Fixed in 20220419a/20220420a
