### ISSUE TITLE
KubeJS "Failed to Parse Recipe" Warning

### ISSUE THREAD

**Issue by laserlemons** [mrh0/createaddition#199]
**Describe the bug**
With KubeJS installed it spits out this warning when loading the world:

Failed to parse recipe 'createaddition:mechanical_crafting/overcharged_hammer[create:mechanical_crafting]'! Falling back to vanilla com.google.gson.JsonSyntaxException: Unknown item 'createaddition:overcharged_alloy'

I'm assuming there was a recipe that was not removed when the mod was updated to 1.18.

**To Reproduce**
1. Install KubeJS alongside this mod.
2. Open a world and look at the chat.

**Additional context**
- Mod version: createaddition-1.18.1-20220111b
- Forge version: 39.0.36
- Create version: create-mc1.18.1_v0.4c

**Comment by mrh0** [comment]
Fixed in 20220125a.
