### ISSUE TITLE
Compat Suggestion - Zinc Mineral Deposit for Immersive Engineering

### ISSUE THREAD

**Issue by sharlin073** [mrh0/createaddition#20]
Well, the title is self-explanatory.
Zinc might not be very useful for other tech mods, but there's an external heater compat already, so I'm just throwing a suggestion.
If this is not easy, please just disregard it! (I have no knowledge of coding)

Big thanks to this wonderful mod by the way!

**Comment by mrh0** [comment]
Yes, great idea, will look into it!

**Comment by mrh0** [comment]
added in 20210303a

**Comment by sharlin073** [comment]
Thanks!
