### ISSUE TITLE
Lava being compatible with the crude burner

### ISSUE THREAD

**Issue by pnot0** [mrh0/createaddition#200]
You can make your mod more fun than already is by adding a way to the crude burner function with lava, it is easier for you to setup a lava well in the nether than it is for a seed oil generator, if it is not logical to add lava to the crude burner, you should add a geothermal generator which works with lava, it will facilitate a lot

Best regards
pnot0

**Comment by Tommy7026** [comment]
^

**Comment by mrh0** [comment]
I don't think this should be the default behaviour, but it is possible to add yourself as the crude burner is recipe based.
