### ISSUE TITLE
Incompatible with Latest Flywheel

### ISSUE THREAD

**Issue by GW-Dev** [mrh0/createaddition#203]
**Describe the bug**
Create Crafts & Additions crashing with latest Flywheel version.

[crash log](https://pastebin.com/DAKCYTAr)

**To Reproduce**
Open Minecraft with only CC&A and dependencies.

**Additional context**
- createaddition-1.18.1-20220111b.jar
- Forge version: 39.0.59
-  Create 0.4d

**Comment by mrh0** [comment]
Fixed in 20220125a.
