### ISSUE TITLE
Allow custom tesla coil charging recipes & JEI Support

### ISSUE THREAD

**Issue by ShadowFire5650** [mrh0/createaddition#206]
Hi!
I really like the new tesla coil and the way it works but I do have one suggestion, can you make it JEI and Datapack compatible? That way modpack developers and just generally people who want to customize the game can make their own JSON recipes and can view them in JEI. I am talking about the ability to make crafting recipes similar to that of the "Overcharged Alloy" which has recently been removed. I know that it probably isn't as easy as I think it is but it would still make a great addition!

**Comment by mrh0** [comment]
Added in 20220424a (forgot to close this ticket)
