### ISSUE TITLE
Ponder Electric Motor and Alternator Crash

### ISSUE THREAD

**Issue by cobaltw** [mrh0/createaddition#207]
When attempting to ponder the alternator or electric motor, the game will crash.
If Optifine is installed, the game won't crash, but there will be severe graphical issues that make the game completely unplayable until you exit the world and rejoin.

Reproduction steps are self explanatory

- Mod version: 1.18.1-20220125a
- Forge version: 39.0.75
- Create version: 0.4d

**Comment by mrh0** [comment]
Cannot reproduce
