### ISSUE TITLE
Auto Sanding 

### ISSUE THREAD

**Issue by PhamKun** [mrh0/createaddition#21]
Name said it all, a machine that do the sanding for us
need Rotation Force + Sand Paper in order to operate

**Comment by mrh0** [comment]
Yes perhaps

**Comment by PrincessOfEvil** [comment]
You can just automate it with Create...

**Comment by AbacusOperator** [comment]
You already can do it with deployed, depot and conveyor belt.

**Comment by mrh0** [comment]
did not know that
