### ISSUE TITLE
Motor and Alternator rendering issues

### ISSUE THREAD

**Issue by KyleHannon** [mrh0/createaddition#211]
Since updating to the 1.18.1 version, I noticed the shaft element in the Electric Motor and Alternator models are mis-aligned.

For the electric motor, the shaft remains oriented south no matter how the block is oriented, except for facing down, where it's oriented correctly but offset from the rotation axis.

For the alternator, the shaft is positioned in the south direction when the block is oriented north or up, and for east/west/down it appears to be oriented properly but offset from the rotation axis.

![2022-02-16_14 09 21](https://user-images.githubusercontent.com/4743892/154338894-c8918d34-6305-4c13-b2b5-6e0a77c5a3d5.png)

**Additional context**
Minecraft: 1.18.1
Forge: 39.0.58
Mod: 20220125a

**Comment by mrh0** [comment]
odd haven't experienced this, I'll look into it

**Comment by KyleHannon** [comment]
Okay, so I kept trying other combinations of disabling Optifine and other settings, and found out that it's because I had the Flywheel backend off- "/flywheel backend off"

It renders properly when flywheel is on.

**Comment by mrh0** [comment]
Ok
