### ISSUE TITLE
Wire Connectors causing immense server lag when chunk is unloaded

### ISSUE THREAD

**Issue by grundyboy34** [mrh0/createaddition#212]
**Describe the bug**
Whenever a chunk containing wire connectors/wires is unloaded, the server suffers huge tick times. As well, wires between connectors can become missing when the chunk is loaded again.

**To Reproduce**
Set up an alternator, connect it to a machine or battery with wire connectors and a spool.
Teleport away, notice severe increase in tick times.
My specific setup that this occurred in was an alternator with 1 connector, and 2 machines each with 1 wire connector. I attached a wire from the alternator to the first machine, and a wire from the first machine to the second machine.

**Additional context**
- Spark profiler dump: https://spark.lucko.me/HSmx8FugAL
- Minecraft version: 1.18.1
- Mod version: createaddition-1.18.1-20220125a
- Forge version: 30.0.75
- Create version: create-mc1.18.1_v0.4d

**Comment by mrh0** [comment]
I've had people report this before, but have never been able to reproduce this.

**Comment by grundyboy34** [comment]
Changing the profiler dump's view from all to sources might help. If not, here's the pack (ATLauncher) I'm using.
[1.18.1 Exploration and stuff v10.zip](https://github.com/mrh0/createaddition/files/8102847/1.18.1.Exploration.and.stuff.v10.zip)

**Comment by konstantindustin** [comment]
I am also having this issue.

**Comment by froehlichA** [comment]
Can confirm this is happening in the latest version.
Maybe you can reproduce it on a server instance?

**Comment by mrh0** [comment]
I think I fixed it in 20220328a, though haven't been able to verify it.
