### ISSUE TITLE
Immersive Engineering's LV Wires and Copper Spools inter-compatibility

### ISSUE THREAD

**Issue by mosharky** [mrh0/createaddition#213]
Currently, Copper Spools can only be used with the Copper Connector, and LV Wire Coils can only be used with LV connectors and relays. I'd love to be able to use both this mods Spools with IE's connectors and relays, and vice versa

**Comment by mrh0** [comment]
Too difficult to implement, not worth it

**Comment by ffuentesm** [comment]
would be possible to make the copper connectors charge the Powered lanterns? 
Or allow the copper coils to be connected to the Powered Lanterns? 
![image](https://user-images.githubusercontent.com/44974827/163268925-e9019267-39d8-43c5-b258-8af579b89d6e.png)
