### ISSUE TITLE
Tesla coil not charging remote grid

### ISSUE THREAD

**Issue by BoggerBoss** [mrh0/createaddition#214]
Remote grid from refined storage doesnt charge with tesla coil. No animation or anything. I have 720fe/t hooked up to it

**To Reproduce**
Connector above tesla coil. Tesla coil facing towards depot. Remote grid on depot below tesla coil.

**Additional context**
- Mod version: 1.18.1-20220105a
- Forge version:39.0.5
- Create version:0.4b

**Comment by BoggerBoss** [comment]
Anyone?

**Comment by Xaidee** [comment]
I think tesla coil recipes and the item charging feature was removed a while ago, but I'm pretty sure there's plans to re-add it

**Comment by mrh0** [comment]
could not reproduce
