### ISSUE TITLE
Valve failed

### ISSUE THREAD

**Issue by Zimoge** [mrh0/createaddition#217]
**Describe the bug**
When I closed the fluid valve installed between the seed oil storage tank and the liquid combustion chamber, the valve failed, the combustion chamber did not go out, and it continued to consume the fuel in the tank until it ran out. 
**To Reproduce**
I found a bug in the latest version: When I closed the fluid valve installed between the seed oil storage tank and the liquid combustion chamber, the valve failed, the combustion chamber did not go out, and it continued to consume the fuel in the tank until it ran out. 
**Additional context**
- Mod version:createaddition-1.18.1-20220125a
- Forge version:39.0.59
- Create version:create-mc1.18.1_v0.4d

**Comment by mrh0** [comment]
Could not reproduce this, The Crude Burner (which I guess is what you mean by combustion chamber) has an internal buffer, which might be why it looks like this happens. Also, if this was a bug the way you describe it it would more likely a bug with Create and the valve than the Crude Burner itself.
