### ISSUE TITLE
Electromagnets

### ISSUE THREAD

**Issue by THEDESTROYER9009** [mrh0/createaddition#220]
This mod does a great job adding electricity to Create, but can you also add an electromagnet? This would pull in dropped items in a certain radius based on the electricity being input. This would just leave the items on the ground and not pick them up, but it would be helpful to bring items to one block and be picked up by a hopper or other block that picks up items on the ground.

**Comment by mrh0** [comment]
I like this idea, though I don't know if it would make sense for non-metal items
