### ISSUE TITLE
Immersive engineering Bioethanol Compatibility 

### ISSUE THREAD

**Issue by ffuentesm** [mrh0/createaddition#221]
> Chemically speaking, Bioethanol and Ethanol are the exact same compound as the chemical formula is identical. The difference between the two lies in the method in which they have been made.

We already got some compatibility with seed oil and plant oil, so I think that Ethanol and Bioethanol could be also interchangeable. 

Also, is there a difference between using seed oil vs bioethanol in the crude burner in terms of efficiency? 
Could you add a JEI display of how much those items burn per bucket?  Like how the biomass burns 6 items.

**Comment by mrh0** [comment]
Fixed in 20220419a/20220420a
