### ISSUE TITLE
Not being able to craft Copper rods

### ISSUE THREAD

**Issue by Charmy131** [mrh0/createaddition#224]
**Describe the bug**
I can craft copper rods using the rolling mill I don't know what is the cause of this issue but when I go to JEI and try seeing the recipe it wont give me anything and trying to use the rolling mill it doesn't do anything. This is a bit issue for me since copper rods are used to make a good amount of the mods items. Only other side issue I have is seed oil missing its texture and crude burner not working for me.
**To Reproduce**
Steps to reproduce the behavior: I just try to use the rolling mill but the copper ingot doesn't go inside and does nothing. Crude burner I don't know if I'm using it correctly or not but i just try to pump seed oil into it but it doesn't go inside the crude burner even though connected and then when I just fill it by bucket it still doesn't burn even though it has seed oil inside.

**Additional context**
- Mod version: createaddition-1.17.1-020220101a
- Forge version: 1.17.1 37.1.1
- Create version: create-mc1.17.1_v0.4

**Comment by mrh0** [comment]
CC&A for 1.17.1 is no longer supported, is suggest you fix it with CraftTweaker or KubeJS
