### ISSUE TITLE
[1.18.1] Furnace burner not returning empty buckets

### ISSUE THREAD

**Issue by ffuentesm** [mrh0/createaddition#226]
**Describe the bug**
Once I right-click on the furnace burner with a lava bucket, the empty bucket gets stuck inside and I can't remove it when I right-click with an empty hand on it. 
**To Reproduce**
Add a lava bucket and then try to right-click it with an empty hand. 

**Additional context**
- Mod version: createaddition-1.18.1-20220331a.jar
- Forge version: 39.1.2
- Create version: create-mc1.18.1_v0.4f.jar

**Comment by peacegangsta** [comment]
I tried it in 1.18.2 and it worked properly. It even worked with a hopper pulling the bucket out.

**Comment by ffuentesm** [comment]
The problem I have is to manually remove the empty bucket from inside, for now, I need to use a hopper to remove the bucket.
I was asking if would be possible to remove the bucket with your hand without the need for a hopper.

**Comment by peacegangsta** [comment]
Oh, I thought you were having trouble getting the bucket out in general. Nevertheless, Shift + Right clicking with an empty hand in 1.18.2 returns the bucket. For some reason you can even put the empty bucket back in, by just right clicking again.
