### ISSUE TITLE
Bugs I found in 1.18.2

### ISSUE THREAD

**Issue by peacegangsta** [mrh0/createaddition#227]
**Describe the bugs**

1. The shaft from the alternator and electric motor only appear correctly when facing north.

2. Connectors don't seem to update properly.

3. The config values for the accumulator and wires don't change at all or not properly.

**To Reproduce**

1. Place down alternator/electric motor

2. When breaking and replacing a connector on an alternator/electric motor it doesn't transfer any power. Only after leaving and rejoining the world is it updated (or when grabbing the connector with the "Carry On" mod).

3. The config values for the accumulator and wires don't change at all or not properly. If I want to change how much power can be tranfered and accepted I assumed that would be the place. I also tried to restart the game, with no change.
-> I access the config in game via the Create Config Menu.

**Additional context**
- Mod version: 1.18.2-20220409a
- Forge version: 40.0.45
- Create version: v0.4.1
![image](https://user-images.githubusercontent.com/1748758/162967610-761917bb-ffef-458a-936a-fa9aa5150e86.png)
![image](https://user-images.githubusercontent.com/1748758/162967741-08d80307-2c5f-44c4-8067-f935fa5aa6ea.png)

In the images you can see that the alternator/electric motor facing north has a shaft, while the other two don't. Also you can see that 0 fe/t are transfered, even though power is being generated (and there is still a lot of space left). 

With the AE2 energy acceptor touching the alternator, it's working flawlessly.

**Comment by mrh0** [comment]
for the shafts, you need to enable the FlyWheel renderer ( /flywheel backend instancing )
The connectors are known to have issues, will have to figure out why.

**Comment by mrh0** [comment]
Fixed in 20220517a.
