### ISSUE TITLE
Nixie Tube Freedom (Suggestion)

### ISSUE THREAD

**Issue by Reginald-Halifrax** [mrh0/createaddition#23]
This was something I actually suggested to the Integrated dynamics dev with a more broad idea that happened to fit my use case, however that was as of yet unused.

I like Creates Nixie tubes and enjoy the fact that they do support nametags but, name tags are ever so limiting! I personally would love if I could do FE total displays on Nixie tubes or just put anything that isn't a static value on them. A Redstone value between 0-15 isn't good enough for an FE display, plain and simple.

If there were a way to plug some sort of string writer to read Integrated dynamics variables (or some other method) would be brilliant.

Thank you for reading this, sorry if my idea is too hyper specific or too extraneous to incorporate.

**Comment by mrh0** [comment]
I'll look into it
