### ISSUE TITLE
Induction heater does not work on a furnace engine.

### ISSUE THREAD

**Issue by Kaczkens** [mrh0/createaddition#232]
**Describe the bug**

Induction heater does not work on a furnace engine. Yes i changed it in the config file. I tried reloading and restarting the server multiple times.

**To Reproduce**

After playing for a while on a aternos server i decided to make infinite energy using a furnance engine.
made all the necessary things: alternator , copper wires, copper conectors and the induction heater
I changed "heater_furnace_engine_enable" to true
reloaded server
placed the heater on top of the engine and it still didn't work
i also tried restarting the server and it just doesn't want to work

**Additional context**
- Mod version:1.1.5
- Forge version:1.18.2 (40.1.0)
- Create version:0.4.1

![2022-04-20_17 13 51](https://user-images.githubusercontent.com/104085713/164264076-4225a989-c21e-4022-bc98-2920c90f332e.png)

**Comment by mrh0** [comment]
You need to enable it on the client for the message to go away, should still work though.
