### ISSUE TITLE
[1.18.2] Tesla coil not charging Immersive engineering items

### ISSUE THREAD

**Issue by ffuentesm** [mrh0/createaddition#235]
**Describe the bug**
I am trying to charge the IE accumulator Backpack, but it does not seem to work. 

Is that due to the "Flux" charge it has? 
If so, could you make it so the Tesla coil can charge different types of energy?

**To Reproduce**
Set up a tesla coil charging station
Place the Accumulator backpack under it

**Additional context**
- Mod version:createaddition-1.18.2-20220419a.jar
- ImmersiveEngineering-1.18.2-8.0.1-147.jar
- Forge version: 40.1.0
- Create version: create-mc1.18.2_v0.4.1.jar

**Comment by mrh0** [comment]
Could not reproduce, works perfectly fine for me

**Comment by ffuentesm** [comment]
Oh, I found the problem.

I think you should add to the ponder that you need a Redstone signal to activate the charging station. 
Because of the ponder instructions, I thought that you only needed to place the item below the coil to activate the charging.
![image](https://user-images.githubusercontent.com/44974827/164996437-067f087e-98c1-4480-9138-d0504a429f53.png)
So to charge the items I needed to add a button to the side of it. And I take damage doing that. 
![image](https://user-images.githubusercontent.com/44974827/164996429-476509d6-9e22-4e2f-ac14-a587e8ac5e0f.png)

**Comment by Snowman-25** [comment]
> need a Redstone signal to activate the charging station.

That is not correct. A Redstone signal is only needed for turning the tesla coil into a weapon. Charging will happen without a redstone signal.

**Comment by ffuentesm** [comment]
Well, it did not happen in my version. 
I placed the item in the depo and nothing happened, it only changed once I added the redstone signal.
