### ISSUE TITLE
Connectors does not work

### ISSUE THREAD

**Issue by HerrGru** [mrh0/createaddition#237]
Connectors does not work
They are very buggy sometimes they work but than they dont work thats very strage the other bug is that golden and coper spoles have the same description pls fix it 

https://drive.google.com/file/d/1guk9ZbOKIXv45Qejs4nn6d8tDqt4OhDb/view?usp=sharing

- Mod version: [createaddition-1.18.1-20220420a](https://www.curseforge.com/minecraft/mc-mods/createaddition/files/3760861)
- Forge version: 39.1.2
- Create version: create-mc1.18.1_v0.4f

**Comment by N0FoxG1ven** [comment]
Having the same issue, was about to post a report but i'll outline mine here so an entirely new report is not opened.

1. Copper and gold spools transfer the same amount of power, i dont know if this is intended.

2. Accumulators cannot pass to each other, thus making battery banks difficult to make. requiring all batteries to be hooked up to the same input without buffers. i am however able to take from an accumulator to a motor just fine. provided issue 3.

3. connectors do not pass to each other. you cannot make lines longer than 1 connector to distribute around a base, instead requiring a new alternator in each room to power everything or keeping power close to your generation. i can make a motor run directly off an accumulator but not after a single connector is put between. i am not certain if this is intended and was not this way in the spotlight i watched on this mod so i think it is a bug.

4. while trying to get screenshots i cant get the motor to work directly anymore. 

Screenshots:

![2022-05-04_00 49 54](https://user-images.githubusercontent.com/104889177/166641997-54153d78-d875-4b1a-8f9d-d3a594eb8d73.png)

![2022-05-04_00 50 06](https://user-images.githubusercontent.com/104889177/166642024-7354fa5a-ae7a-4b2b-8aa0-8da61c613589.png)

![2022-05-04_00 50 22](https://user-images.githubusercontent.com/104889177/166642046-79a7f9de-55cc-403f-b41a-e9409fcd77c0.png)

![2022-05-04_00 54 10](https://user-images.githubusercontent.com/104889177/166642151-75d6956f-d853-400a-9211-7569ffe6aef9.png)


Mod Version: 1.18.2-20220424a
Forge Version: 40.0.52
Create Version: 0.4.1

**Comment by lovebirdmic** [comment]
> There seem to be issues with the connectors atm, will look at it when I have time.

I went to make a new issue, but noticed this. I already wrote it up, but it might have some relevant info for bug squashing. 


Bug: Breaking a block with a wire node after it's been/is in use (has transferred energy) and replacing stops the flow of energy. Reblogging seems to fix it.

It seems like maybe something isn't getting updated. Destroying and replacing either a connector acting as in/out for a block (such as a connector on the side of a creative generator) or a block with an in/out put 'built in' (accumulator) and replacing it so the same type of connector is in the same block position causes the energy transfer to halt. For connectors, moving them to another face of the block seems to make it work again and for accumulators, you have to move it to another block location (unless you repeat this again on the new placed block)

Versions:
MC: 1.18.1
Forge: 39.1.2
Create: v0.4f
CCA: 20220420a


finally, I do not believe it is another mod interfering, but just in case, my mod list
<details><summary>Image</summary>

![image](https://user-images.githubusercontent.com/53983658/168092404-b76ef898-58e4-4351-824f-95045b2eb5f7.png)

</details>

**Comment by mrh0** [comment]
Thanks, this reinforces what GreenBudgie concluded in his fix #240, working on integrating the fix with a few other tweaks to the connectors, expect an update soon

**Comment by mrh0** [comment]
Fixed in 20220517a.
