### ISSUE TITLE
Alternator Power Transfer Issue When Sending Power Out

### ISSUE THREAD

**Issue by jplee95** [mrh0/createaddition#24]
Found when the alternator is next to a energy receiving block, the alternator will send to that block even if the receiving block is unable to take energy at that moment. Also Energy is sent to sides that are outputs.

Edit: 
Version: 1.16.4-20210303a
Forge: 36.0.45

**Comment by mrh0** [comment]
will look into it

**Comment by mrh0** [comment]
fixed in 20210320b
