### ISSUE TITLE
Can't create biomass.

### ISSUE THREAD

**Issue by StormDragon-64** [mrh0/createaddition#244]
**Describe the bug**
I am trying to make biomass in order to make bioethanol, but I think the recipe is broken. I have seed oil and flowers in a basin with a mixer above it, and it is being heated by a blaze burner, but nothing is happening. 

**To Reproduce**
-Set up a mixer and put a blaze burner under the basin
-power the blaze burner
-Put seed oil and flowers in the basin
Nothing happens...

**Additional context**
- Mod version: createaddition-1.18.1-20220105a
- Forge version: 39.1.0
- Create version: Create 1.18.1 v0.4f

Image:
![image](https://user-images.githubusercontent.com/80718549/168515471-b0301b58-a028-47c0-9a5a-3b4b1c536309.png)

**Comment by mrh0** [comment]
old version

**Comment by StormDragon-64** [comment]
Oh, for some reason it doesn't show in the curseforge app and I had to manually update it.

**Comment by StormDragon-64** [comment]
Wait nvm, I am using that version, it still happens, I just copied the wrong version name 
to here

**Comment by StormDragon-64** [comment]
I tested this in a singleplayer world and it worked for some reason, but on my server it still doesn't work.

**Comment by StormDragon-64** [comment]
Ok, finally figured it out, apparently your mixer needs to be spinning above a certain rpm in order to work.
