### ISSUE TITLE
fabric-mill dupe

### ISSUE THREAD

**Issue by anim4trix** [mrh0/createaddition#246]
create fabric latest build , just dropped copper sheet in mill and it got duped can anyone confirm?

**Comment by anim4trix** [comment]
cant reproduce in another world , idk maybe a world related issue

**Comment by Notenoughmail** [comment]
I've just encountered this in my playthrough, and it seems that the mill pulls items thrown onto it into its inventory without removing them from the world. I was able to replicate on two separate singleplayer worlds
https://youtu.be/lfL7b3ds5Y4

**Comment by Blightbuster** [comment]
Fixed by #256?

**Comment by Notenoughmail** [comment]
That appears to have fixed it!
