### ISSUE TITLE
Erroring Recipes

### ISSUE THREAD

**Issue by gamenTV** [mrh0/createaddition#248]
**Describe the bug**
There seems to be an Erroring Recipes
-  createaddition:compat/jeed/shocking
-  createaddition:compat/mekanism/rose_quartz_metallurgic_infusing

Screenshots / Scripts / Logs
- https://pastebin.com/YxTjhK5q
- https://pastebin.com/pYw32J8g

**Additional context**
- Mod version: 1.18.2-20220517a
- Forge version: 40.1
- Create version: 1.18.2_v0.4.1
- Other: https://pastebin.com/SrTEck6i

**Comment by mrh0** [comment]
Fixed in 20220813a.
