### ISSUE TITLE
Fe energy Wiring issue

### ISSUE THREAD

**Issue by swagst** [mrh0/createaddition#249]
I made an energy factory using the _create:crafts & addition_ and _create_ itself . i use the electric motors to power my pump and conveyor but when i connect the motors to electricity it only works half of the time, when i connect the wire to an accumulator it only works sometimes . i checked many times the energy production and the energy comsumption and i produce more energy than i need.
i dont if i did smth wrong and i wish i can get some help thx.

**Comment by mrh0** [comment]
Please state the versions you are using

**Comment by swagst** [comment]
> Please state the versions you are using

1.18.2

**Comment by mrh0** [comment]
no the version of the mod, a lot of the connector related issues was fixed in the latest update

**Comment by swagst** [comment]
oh the version is 20220424a

**Comment by mrh0** [comment]
this issue was fixed in later patches
