### ISSUE TITLE
Issue of multiply stress on load save

### ISSUE THREAD

**Issue by slasherbane** [mrh0/createaddition#25]
see https://github.com/Creators-of-Create/Create/issues/1234

**Comment by slasherbane** [comment]
Your mod can  make this issue happen ?

**Comment by mrh0** [comment]
Know this used to happen, what version are you using?

**Comment by slasherbane** [comment]
the 1.16.5 version

**Comment by mrh0** [comment]
no the version date,  for example, 20210303a is the latest version

**Comment by slasherbane** [comment]
oh: createaddition-1.16.4-20210303a

**Comment by slasherbane** [comment]
if it's the latest  that's probably not your mods but the base mod...

**Comment by mrh0** [comment]
Alright, ill look into it.

**Comment by mrh0** [comment]
I have been unable to recreate this problem.
