### ISSUE TITLE
Wires should stretch farther

### ISSUE THREAD

**Issue by tungstonminer** [mrh0/createaddition#251]
In Create, one can stretch belts for 20m—without any power loss—for the cost of 6 dried kelp and a crafting table.  

In this mod, wires can only stretch 10m—with a 25% power loss at the alternator—for the cost of 2 copper ingots and a rolling machine.  This makes wires seem extremely expensive compared to belts, when, in real life, it's the other way around.  One would expect wires to be able to be stretched *at least* that long, and quite probably farther.  I would suggest giving copper wires a range of 30m (1.5x) and gold wires 40m (2.0x).

**Comment by mrh0** [comment]
25% loss is at any distance, the wires themselves have no loss, Think of the 25% as "mechanical friction", the wire length is configurable
