### ISSUE TITLE
Connectors are buggy in 1.18.1

### ISSUE THREAD

**Issue by tungstonminer** [mrh0/createaddition#252]
**Describe the bug**

![2022-05-23_08 46 05](https://user-images.githubusercontent.com/72411157/169845789-b806c85c-c562-4d0a-9303-0962749d75d1.png)

Despite appearances, there is actually no power reaching the electric motor in this screenshot.  The shaft exiting the motor is not spinning, nor is any power being consumed from the accumulator.  And, wearing Engineer's Goggle, if I examine the motor itself:

![2022-05-23_08 47 10](https://user-images.githubusercontent.com/72411157/169846054-41026d66-ae80-40f4-93e2-b271651b1f8d.png)

**To Reproduce**

1. Create some kind of setup where you provide power to an electric motor.
2. Break the connector
3. Replace the connector and re-connect the wire

At step 1, you will see that the motor receives power and spins as expected.
At step 3, you will see that the motor does *not* accept power anymore.  In fact, nothing I do seems to make it possible for the motor to ever accept power on that side again, even breaking and replacing the motor.  Adding a connector on another side works... until you break *that* connector and re-attach it.

**Additional context**

- Mod version: 20220420a
- Forge version: 39.1.2
- Create version: 0.4f

**Comment by mrh0** [comment]
https://www.curseforge.com/minecraft/mc-mods/createaddition/files/3794929

**Comment by tungstonminer** [comment]
That's correct.

**Comment by tungstonminer** [comment]
To expand up on that... I've created a 1.18.1 modpack, [Blocky Go Round](https://github.com/tungstonminer/blocky-go-round) which has a matching server that's been up for some time now.  I can't easily update either at this point.  I would be very grateful if you could post an 1.18.1 version which includes this fix.

**Comment by tungstonminer** [comment]
Not to be a pest, but would it be possible to back-port the fix to the 1.18.1 version of this mod?  Due to the way CurseForge works, it's impractical for me to update the modpack to 1.18.2, so the best I could do without a fix is to warn my players to avoid the electrical system entirely... and that would be very sad!

**Comment by mrh0** [comment]
Yes it would be possible, though It's not a priority for me right now. I'll reopen this ticket
