### ISSUE TITLE
[Suggestion] Oil Lamps that use the Seed Oil

### ISSUE THREAD

**Issue by NealSavage** [mrh0/createaddition#254]
I think that this mod's seed oil has a cool second possibility as a use - lighting. A few oil lamp types could be added to the game to give your seed oil more functionality. I'll link a few types and suggest recipes for each

Clay Oil Lamp 1:
https://media.istockphoto.com/photos/diwali-hindu-festival-of-lights-celebration-diya-oil-lamp-against-picture-id1179778264?k=20&m=1179778264&s=612x612&w=0&h=L1nMjQN5sCqQgdQIhEnQMrN1Q4mKa9tJMGkdp_GUZLE=
Recipe: 1 clay and 1 string
  Variants: Copper, iron, gold. Replace the 1 clay with new ingredient.

Clay Oil Lamp 2:
https://m.media-amazon.com/images/I/61Smlz8Mx9L._AC_SX679_.jpg
Recipe: 2 Clay, 1 string
    Variants of this in copper, iron, and gold would be good. Replace the 2 clay with the new ingredient.

Iron Oil Lamp:
https://m.media-amazon.com/images/I/415kQsQfbEL._AC_.jpg
Recipe: 2 Iron, 1 copper, 1 string
         Variants: Copper, recipe being 3 copper, 1 string.  Gold, recipe being 2 gold, 1 copper, 1 string
         (copper is for the metal inside the glass)

Glass Sconce:
https://m.media-amazon.com/images/I/71NkLdPVJzL._AC_SY879_.jpg
Recipe: 2 glass, 1 iron, 1 string.
    Variants: Copper, Gold, replace the 1 iron with the new ingredient. 

I am not sure if burn times should be variable between the different types.

What do you think?

**Comment by mrh0** [comment]
I don't think this is within the scope of this mod, might fit better for another mod
