### ISSUE TITLE
For the first time get in the world, Crude Burner is not compatible with other mods liquid fuels

### ISSUE THREAD

**Issue by xuwuwudi** [mrh0/createaddition#255]
**Describe the bug**
For the first time get in the world, Crude Burner is not compatible with other mods liquid fuels, like creosote in Immersive Engineering.
I need to /reload or get in the world for second time, creosote could be used in crude burner.

**To Reproduce**
1.add mod Immersive Engineering and CC&A(include Create) and also JEI
2.start game and get in a world
3.use JEI to check the recipe of crude burner.

**Additional context**
- Mod version: createaddition-1.18.2-20220517a
- Forge version:40.1.20
- Create version: create-mc1.18.2_v0.4.1

**Comment by dragonshardz** [comment]
I am having the same problem, and while it's fixable in SSP with a datapack, it doesn't seem to work on a server.

**Comment by dragonshardz** [comment]
I went back and checked.

Creosote Oil works in SSP sans datapack. In SMP, it doesn't work, except for one time immediately after a datapack adding the recipe is loaded.

**Comment by dragonshardz** [comment]
I have the sneaky feeling it is because CC&A finishes processing recipes before IE registers the Creosote fluid, and doing a /reload pulls that Creosote is registered from memory.
