### ISSUE TITLE
[Fabric] REI breaking due to CC&E registering the wrong IDs

### ISSUE THREAD

**Issue by Oliver-makes-code** [mrh0/createaddition#257]
**Describe the bug**
CC&E is registering the wrong IDs for its crafting in REI, causing recipes to not work for everything

**To Reproduce**
Install REI

**Additional context**
- Mod version: 20220525a
- Create version: 0.4.1 patch 2

**Comment by mrh0** [comment]
Old ticket, think this was fixed
