### ISSUE TITLE
[Fabric] Ticking Entity Server Crash with Furnace Burner

### ISSUE THREAD

**Issue by JensenJ** [mrh0/createaddition#260]
**Describe the bug**
Server randomly crashed after using Furnace Burner for a while, and wouldn't restart until removing mod. 

**To Reproduce**
1. Place furnace burner attached to flywheel. 
2. Feed items in using funnels.
3. Wait for crash

**Additional context**
- Mod version: createaddition-1.18.2-20220525a
- Fabric version: 0.14.6
- Fabric API version: 0.53.4 1.18.2
- Create version: 0.4.1 Patch 2
- Using modified Modpack: Better Minecraft V11.5 Fabric 1.18.2 (added Create/Crafts and additions/Charm, removed Fabric Seasons)
- Removing mod allows world to be reloaded.

Server Log:
[2022-05-30-4.log](https://github.com/mrh0/createaddition/files/8800797/2022-05-30-4.log)

**Comment by AlphaMode** [comment]
This seems to be a duplicate of #262 which has been fixed
This should be closed
