### ISSUE TITLE
Changing Configs (Server Side)

### ISSUE THREAD

**Issue by Ginph** [mrh0/createaddition#263]
I've been trying to change the config for 'createaddition-common.toml' to enable the furnace heater. It is apparently set as false as default and I've changed it to true. It still wont recognize the change and it is currently disabled.

**Comment by mrh0** [comment]
note that the not enabled goggles message still appears if it isn't also enabled on the client, the furnace engine should still run, if not i imagine this might be a bug.
What version are you on?

**Comment by Milosovic90** [comment]
I'm having the same issue. I changed the config and the error message disappeared. The heater is working on the blast furnace but as soon as i put down the furnace engine it winds down until it stops. Im not really good at telling the version but the .jar file number is 1.16.5-20220129a.
![heater error](https://user-images.githubusercontent.com/107649736/174159251-b6a99e84-ab02-457f-971c-32dfdc52455b.png)

**Comment by mrh0** [comment]
That's very strange, it worked the last time I tried, however, I don't update the 1.16 versions anymore so if it is a bug I'm not fixing it.
