### ISSUE TITLE
[Fabric] Induction Heater compat for Alloy Forgery

### ISSUE THREAD

**Issue by quattage** [mrh0/createaddition#264]
Here's an example:
![image](https://user-images.githubusercontent.com/49324428/173173083-0b122adb-8d6f-4a27-bbef-e11b4eae28e3.png)
The heater should ideally not be located directly attached to the forge controller, as doing so would block valuable space for i/o automation. This is why I have depicted it attached to the bottom of the structure. Overall I think this would be a nice complement to both Create and Alloy Forgery, and would allow for some semi-late-game automation opportunities as well as more interactions for modpack developers to play around with.

**Comment by mrh0** [comment]
Induction heater has been removed
