### ISSUE TITLE
Furnace Burner not working with furnace engine

### ISSUE THREAD

**Issue by WastefulMeat5** [mrh0/createaddition#268]
furnace burner is not working with the furnace engine from create. 

Followed all instructions. set up furnace engine and fly wheel with furnace burner, added coal but nothing happened. Tried using hoppers and adding the coal before adding the furnace engine. furnace engine and fly wheel are working with vanilla furnaces. 

- Mod version: 1.17.1-20220101a
- Forge version: 37.1.1
- Create version: 1.17.1_v0.4

**Comment by mrh0** [comment]
1.17.1 is no longer supported (and yes furnace burners was broken in that version)
