### ISSUE TITLE
Doesn't work with CC: Restitched

### ISSUE THREAD

**Issue by ivilkhovyi** [mrh0/createaddition#272]
**Describe the bug**
CC: Restitched mod is currently the only computer craft fork available for the latest 1.18.2 Minecraft fabric, it makes sense to make your integration to work with it. Thank you.

**To Reproduce**
Put an electrical motor on the left of a computer. Run Lua command in it. Type motor = peripheral.wrap("left"). the motor will be null, but should access the actual motor.

**Additional context**
- Mod version:  createaddition-1.18.2-20220621a.jar
- Fabric: 0.14.8
- Create version: create-mc1.18.2_v0.4.1+637.jar
- CC: Restitched: cc-restitched-1.100.8.jar

**Comment by mrh0** [comment]
I belive this was fixed
