### ISSUE TITLE
Relay crash the game 

### ISSUE THREAD

**Issue by Guppy3874** [mrh0/createaddition#273]
**Describe the bug**
If you brake an Redstone relay that is turned on an is connected whit something (both sides) the game crashes.

**To Reproduce**
-place a Relay
-connect both sides whit something (motor,generator)
-turn the Relay on
-Game crash

**Additional context**
- Mod version:  createaddition-fabric-1.18.2-20220621a
- Forge version: <--- Fabric loader 1.18.2  0.14.8
- Create version:  create-mc1.18.2_v0.4.1+637.jar (Fabric)

![2022-07-03_19 17 23](https://user-images.githubusercontent.com/98043898/177050380-9002f22f-232e-4748-9053-91b8f7960681.png)

**Comment by denchInside** [comment]
Also crashes on forge

**Comment by mrh0** [comment]
Works perfectly fine for me

**Comment by mrh0** [comment]
fixed
