### ISSUE TITLE
Please make the Electric Motor on/off switchable (with redstone switch) to conserve Energi

### ISSUE THREAD

**Issue by ardissaps** [mrh0/createaddition#275]
Please make the Electric Motor on/off switchable (with redstone switch) to conserve Energi
![image](https://user-images.githubusercontent.com/82106625/177118830-c3f578d4-fdd6-40d1-acdf-42f45975f77a.png)

**Comment by mrh0** [comment]
Already implemented in the latest versions

**Comment by ardissaps** [comment]
> Already implemented in the latest versions

is it realeased?
