### ISSUE TITLE
Crash with 0.5

### ISSUE THREAD

**Issue by StrangerSon71** [mrh0/createaddition#278]
**Describe the bug**
It doesn't work with 0.5

**To Reproduce**
1. Download this and Create 0.5
2. Play it
3. It crashes
**Additional context**
- Mod version: Your mod version names are way to long, latest as of Jul 8
- Forge version: 40.1.54
- Create version: 0.5
- You should probably remove the Crude Burner while you're at it.

**Comment by mrh0** [comment]
Create .5 is out, neat, will fix when i have time

**Comment by PaterFrog** [comment]
I assume it's the same crash I'm experiencing. Logs attached.
[latest.log](https://github.com/mrh0/createaddition/files/9075478/latest.log)
[crash-2022-07-09_01.37.14-fml.txt](https://github.com/mrh0/createaddition/files/9075479/crash-2022-07-09_01.37.14-fml.txt)

**Comment by brewskidafixer** [comment]
the furnace engine was removed in create 0.5 could you add it back in with your mod as a way to fix the issue and also bring back the furnace engine

**Comment by mrh0** [comment]
fixed in 20220709a.
