### ISSUE TITLE
[20220709a] Curseforge dependencies set to fabric version rather than forge.

### ISSUE THREAD

**Issue by laserlemons** [mrh0/createaddition#280]
**Describe the bug**
The dependencies listed on the latest forge version of the mod are set to the same thing as the fabric versions.

**To Reproduce**
1. Look at the dependencies here: https://www.curseforge.com/minecraft/mc-mods/createaddition/files/3865693

**Additional context**
- Mod version: 20220709a
- Forge version:
- Create version:

**Comment by mrh0** [comment]
fixed
