### ISSUE TITLE
Rework Seed Oil for Create 0.5

### ISSUE THREAD

**Issue by Derpford** [mrh0/createaddition#283]
Seeing as Create 0.5 removed the Furnace Engine, the Crude Burner and Seed Oil can no longer function the way it was originally designed (and the burner had to be removed to fix a crash). However, I think seed oil and bioethanol are something that CCA should still add, since seeds typically pile up when using Create for farming.

So, what if the Crude Burner was reworked into a heat source, similar to the Blaze Burner? It would be capable of running at a slightly higher temperature than the regular Blaze Burner, but not as high as the Superheated Blaze Burner--and it would consume seed oil or bioethanol rapidly when doing so. Maybe it could also take a redstone input--throttling the heat output to make fuel last longer, at the cost of dropping down to the same output as a regular Blaze Burner.

The goal here would be to have seed oil and the Crude Burner function as a pre-Nether peak in the player's power output, without necessarily becoming more useful than the Blaze Burner. The Blaze Burner can be better at both fuel efficiency (regular) and high temperature (superheated) while the Crude Burner specializes in being a midrange option with a fuel type that's relatively easy to produce (once you have the infrastructure, of course).

**Comment by mrh0** [comment]
Liquid fuels can now be used in the blaze burner when given a straw
