### ISSUE TITLE
Guzzler Helmet

### ISSUE THREAD

**Issue by AiDSl** [mrh0/createaddition#285]
Guzzler Helmet can give the player potion effect when player sneaking (comsume potion in the process ofc),
this can be fill using spout (both when Guzzler Helmet is item on belt/depot or wear by entity that stand right under it)

you can give Blaze burner a Guzzler Helmet,and then you can connect him with pipes,so you can use liquid fuel to do steam power or other heated mixing recipe.

**Comment by AiDSl** [comment]
that being said,I think just give it lava and it is super heated is cheaty,so I prupose these:

1.liquid fuel can maintain Blaze`s heat phase(limited time or refill indefinitely)
2.liquid fuel can not make burner into superheated phase.

so you still need to give the burner first blaze cake to get into superheated phase.

**Comment by mrh0** [comment]
Now, in 1.19.2 you can give a blaze burner a straw which allows it to burn liquid fuels
