### ISSUE TITLE
Tesla coil isn't localized

### ISSUE THREAD

**Issue by vizthex123** [mrh0/createaddition#286]
**Describe the bug**
The name of tesla coil charging tab in JEI isn't localized
![image](https://user-images.githubusercontent.com/31721920/178380608-5ba8b038-da7f-4e57-8a45-652c90bbb56d.png)

**To Reproduce**
Check the tesla coil charging when AE2 is loaded
**Additional context**
- Mod version: 20220710a
- Forge version: 40.1.60
- Create version: 0.5.0

**Comment by ShibeTemple** [comment]
Can confirm that the mod is incompatible with the latest version of Create, 0.5.0a.

**Comment by vizthex123** [comment]
seems like it's been updated now

**Comment by mrh0** [comment]
Fixed in 20220813a.
