### ISSUE TITLE
Buckets of Seed Oil Bioethenol say they can be used in a Crude Burner even though it got removed

### ISSUE THREAD

**Issue by vizthex123** [mrh0/createaddition#288]
**Describe the bug**
Their tooltips mention the Crude Burner, which got removed from the mod when Create update to 0.5

In addition, the Biomass Pellet's tooltip says it can smelt 6 items, but only has the burn time for 5

**To Reproduce**
Check the tooltips of buckets of seed oil or bioethenol

**Additional context**
- Mod version: 20220712a
- Forge version: 40.1.60
- Create version: 0.5.0c

Screenshots:
![image](https://user-images.githubusercontent.com/31721920/178902219-7deb4713-a191-4f11-8dbc-efe055192049.png)
![image](https://user-images.githubusercontent.com/31721920/178902240-37526f05-5187-4afb-b8f0-e5e9e7b17294.png)

![image](https://user-images.githubusercontent.com/31721920/178902261-4d4e6952-ca94-48f8-9cbd-a0b9f69283ff.png)
![image](https://user-images.githubusercontent.com/31721920/178902276-0debafc4-4de7-498c-a8bf-058d1fec926d.png)

**Comment by mrh0** [comment]
Fixed in 20220813a.
