### ISSUE TITLE
Alternators don't generate power if they're in a square configuration [like 2x2 or 3x3 for example]

### ISSUE THREAD

**Issue by Famous5000** [mrh0/createaddition#29]
**Describe the bug**
Title.

**To Reproduce**
Steps to reproduce the bug: 
Set up a cog network to transfer a large amount of stress into power
Place alternators next to each other and facing the cogs
Observe any power consumer behind it not receiving power.

**Additional context**
- Mod version: 20210320b
- Forge version: Forge 36.0.42
- Create version: v0.3e

Edge-cases: If you have generators in an L shape, only 1 will produce power, and the other two will not. They all will still consume power though.

**Comment by Famous5000** [comment]
To add: You knew of this bug in the discord so I did my best to translate it here. Enjoy.

**Comment by mrh0** [comment]
Thanks, fixed in 20210402a!
