### ISSUE TITLE
CraftTweaker Support

### ISSUE THREAD

**Issue by AlexDevBoi** [mrh0/createaddition#293]
The Rolling Mill and the Tesla Coil have Lots of potential, and it would be cool to be able to make custom recipes

**Comment by mrh0** [comment]
I'm not making an addon for this, KubeJS is far superior in my opinion, which support custom recipe types

**Comment by jaredlll08** [comment]
You don't need to add any specific code to have CraftTweaker support, it also supports recipes with custom recipe types.

The only issue is that you don't register your recipe types anywhere, which is technically a vanilla requirement, example in create: <https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/main/java/com/simibubi/create/AllRecipeTypes.java#L82>

Happy to provide more examples if they are needed, but once that is done, then people will be able to add and remove recipes perfectly fine using https://docs.blamejared.com/1.19/en/mods/other_mods

**Comment by jaredlll08** [comment]
That is not a solution that will help you, @mrh0 needs to implement it, only then can you use the `addJsonRecipe` method.
