### ISSUE TITLE
Crash Bug relating to Furnace Engine removal

### ISSUE THREAD

**Issue by cimds** [mrh0/createaddition#294]
In the previous version of CC&A, the game crashed on loading a world. On this version, I could play for hours, then at some point the internal server stopped working and eventually crashed with surprisingly the same error message:

Mod File: createaddition-1.18.2-20220517a.jar
	Failure message: Create Crafts & Additions (createaddition) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.18.2-20220517a
	Mod Issue URL: https://github.com/mrh0/createaddition/issues
	Exception message: java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.components.
flywheel.engine.FurnaceEngineInteractions$HeatSource

It's possible the internal server failing only triggered this bug incidentally by reloading the mod in an attempt to fix the server problem. Going by the error message, I assume this problem is caused by the furnace engine burners that were in CC&A before Create 0.5 not being fully removed from this mod. That this doesn't happen consistently on loading a world like it did in the previous version of CC&A is strange, though.
Here's the full crash report, with the stacktrace and modlist:
[CreateAdditionCrash.txt](https://github.com/mrh0/createaddition/files/9127008/CreateAdditionCrash.txt)

**Comment by mrh0** [comment]
update the mod

**Comment by cimds** [comment]
Apparently old versions leave behind a broken config file. I fixed the
problem by deleting the config so it would be reset to default when I
loaded it.
