### ISSUE TITLE
JEI doesn't work with some recipes

### ISSUE THREAD

**Issue by traveldesign** [mrh0/createaddition#296]
Hi, just wanted to let you know that the cake base and other recipes don't show up in JEI. I would love to know how to craft them. I believe other people on the discord have mentioned the same bug. 

**To Reproduce**

**Additional context**
- Mod version: createaddition-1.18.2-20220715a
- Forge version: 1.18.2
- Create version: Latest

**Comment by mrh0** [comment]
Yes, however I've never encountered this which makes it difficult to fix

**Comment by traveldesign** [comment]
haha ok that’s fine. Could you at least tell me what the recipe for the
cake base is? Much appreciated :)
