### ISSUE TITLE
Crude burner - seed oil doesn't work 

### ISSUE THREAD

**Issue by Beladric** [mrh0/createaddition#297]
Hello,

**Bug Description**

The crude burner don't work with seed oil (But it's work with other liquids).

**To Reproduce**

Just put in place a crude burner and fill it with seed oil.

**Additional context**

- Mod version: 20220129a
- Forge version: 36.2.33
- Create version: 0.3.2g

Kind regards, Beladric.

**Comment by Beladric** [comment]
Picture to display problem

![2022-07-20_22 46 02](https://user-images.githubusercontent.com/37240228/180078561-553bffea-d7ad-4c3b-9d77-4191d83bbbd7.png)

**Comment by StormDragon-64** [comment]
I don't think the dev supports older versions, and I never had this problem. Maybe try breaking the furnace engine and placing it back on again? the furnace engine on it again?

**Comment by mrh0** [comment]
yep too old
