### ISSUE TITLE
Iron Rod name is not localized in en_us.json

### ISSUE THREAD

**Issue by Swedz** [mrh0/createaddition#298]
**Describe the bug**
The iron rod item name displays as "item.createaddition.iron_rod" instead of "Iron Rod"

**To Reproduce**
- Look at the name of the iron rod item

**Additional context**
- Mod version: 20220715a
- Forge version: 40.1.68
- Create version: 0.5.0c

**Comment by mrh0** [comment]
Fixed in 20220813a.
