### ISSUE TITLE
Art: Catwalk underside textures mirrored/oriented wrong

### ISSUE THREAD

**Issue by Ek-Videogames** [mrh0/createaddition#299]
### Describe the Bug

The underside connected-textures of catwalks are wrong / don't match the top side.

### Reproduction Steps

1. Any multi-block arrangement of catwalks demonstrating the different 'connected-textures' placements.
2. Corners and edges above appear as intended, but looking from below they are not connected right.

### Expected Result

Connected-block textures match as the mirror of the upwards side.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/55356135/180580358-23f41473-6885-4471-bb41-50978d11d7c7.png)

![image](https://user-images.githubusercontent.com/55356135/180580392-2aa9b376-56a7-47a0-83ef-78e54c035a13.png)

### Operating System

Windows

### Mod Version

0.5.0c

### Minecraft Version

1.18.2

### Forge Version

36.2.0

### Other Mods

create-stuff-additions1.18.2_v1.1.8

createaddition-1.18.2-20220712a

createaddition-1.18.2-20220712a

jei-1.18.2-9.7.0.209

**Comment by mrh0** [comment]
Wrong mod.
