### ISSUE TITLE
Config file doesn't change ingame block behavior

### ISSUE THREAD

**Issue by Bezimienny33** [mrh0/createaddition#3]
The config file in config/createaddition-common.toml doesn't seem to affect behavior of the blocks, I've tried changing the power output and stress values in the alternator and the electric motor, but there was no change in game.

- Forge version : 1.16.4-35.1.36 (One release behind latest)
- Mods : Create, Create additions, JEI, Immersive Engineering
- Create Version : create-mc1.16.3_v0.3e
- Create additions Version : 1.16.4-20210127b
- Immersive Engineering Version : 1.16.4-4.1.2-129

**Comment by Bezimienny33** [comment]
Nevermind, i just looked at the configs in a wrong way, energy output/input for the machines is changed by one variable, in the electric motor section of the config, also i sometimes used the /reload command instead of doing a full game restart . Sorry for wasting your time.

**Comment by mrh0** [comment]
No problem, appreciate you reporting potential issues.
