### ISSUE TITLE
Include a relay to enable/disable power based on redstone signal

### ISSUE THREAD

**Issue by arrisar** [mrh0/createaddition#30]
**Description**
This mod is incredible, but one thing that is missing is the ability to disable power into/out of a block.

**Suggestion**
I suggest you include a block that relays energy transmission based on redstone input.

This would be similar to how the gearshift is able to invert shaft rotation when receiving a redstone signal.

**Comment by mrh0** [comment]
Yes this is something I've been thinking about

**Comment by mrh0** [comment]
In 20210410a
