### ISSUE TITLE
connector cannot connect incomplete blocks

### ISSUE THREAD

**Issue by Dr-WeiAL** [mrh0/createaddition#300]
**Describe the bug**
The connector cannot connect to incomplete blocks like trash cans, flux plugs, pipes, etc.

**To Reproduce**
![image](https://user-images.githubusercontent.com/47446553/180653293-efa988fe-309b-497c-b3fe-015ebd339bc6.png)
Immersive Engineering connector can be connected normally
![image](https://user-images.githubusercontent.com/47446553/180653348-219efdf7-c0a4-4ba3-9e88-fdee9dde1430.png)
But the connector of createaddition cannot be placed on it

**Additional context**
- Mod version: 20220715a
- Forge version: 40.1.68
- Create version: 0.5.0c

**Comment by mrh0** [comment]
Fixed in 20221220a.
Added `connector_ignore_face_check` config option.
