### ISSUE TITLE
Fabric: broken with create 5.0

### ISSUE THREAD

**Issue by xiPakuL** [mrh0/createaddition#304]
**Describe the bug**
Startup crash

**To Reproduce**
use create 0.5.x
and createadditions

**Additional context**
- Mod version: createaddition-1.18.2-20220621a
- Fabric version: 0.14.8
- Create version: 0.5.0c

`Caused by: java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullConsumer com.simibubi.create.AllMovementBehaviours.addMovementBehaviour(com.simibubi.create.content.contraptions.components.structureMovement.MovementBehaviour)'`

**Comment by FluffyBumblebees** [comment]
This is a duplicate of https://github.com/mrh0/createaddition/issues/287

**Comment by xiPakuL** [comment]
it seems to be an issue for over a month is this repo dead ?

**Comment by FluffyBumblebees** [comment]
No, the devs are just busy

**Comment by mrh0** [comment]
Fixed in 20220813a.
