### ISSUE TITLE
Update Create version to 0.3.1

### ISSUE THREAD

**Issue by CGGSqaure** [mrh0/createaddition#31]
Hey, sorry to rush already, and i hope you know this already but Create 0.3.1 just came out with a bunch of new things, but create crafts & additions isnt compatible with it! hopefully you can get this out soon.

**Comment by Dr-WeiAL** [comment]
Yes, the same problem occurred after I updated Create 0.3.1 today

**Comment by mrh0** [comment]
Create v0.3.1 is supported as of 20210404a.
