### ISSUE TITLE
Refined Radiance Recipe issue.

### ISSUE THREAD

**Issue by Waterspark63** [mrh0/createaddition#312]
**Describe the bug**
Crafting recipe error

**To Reproduce**
Just load the game and look in the latest.log

**Additional context**
- Mod version: 1.1.8
- Forge version: 1.18.2 - 40.1.68
- Create version: 0.5.0c

Basically, I am going through all my mods that have recipe issues, and reporting the broken recipes to the mod githubs, 
Seems the Refined Radiance Exoskeleton recipe is broken, with "Unknown item 'create_stuff_additions:refined_radiance_exoskeleton_chestplate'", looking at the jar file, I noticed that the textures for it are spelt Rafined, instead of Refined, and there isn't even a lang entry for it, maybe theres a typo somewhere? With the recipe looking for refined_radiance makes me think that it's may not be the recipe that's messing up, but the item itself is typo'd or called something else.

**Comment by mrh0** [comment]
wrong mod
