### ISSUE TITLE
Flywheel naming convention is not correct

### ISSUE THREAD

**Issue by WolfMachina** [mrh0/createaddition#314]
Mod version 813a is showing a conflict with fly wheel. it asks for up to 1.18-0.7.0 but flywheel is now named just 0.6.5 without the 1.18 prefix judging by the error message, it may also be related to the file name now being 1.18.2-0.6.x instead of 1.18-0.6.x

**Comment by hron84** [comment]
It seems like affects backward, all known versions of createadditions and flywheel seems stopped working somehow. Could you please release an urgent hotfix for the current version with just the version dependency updated?
I tried different combinations of flywheel 0.6.2, 0.6.3, 0.6.5 and I went back to version 424a in createadditions but I found no working combination.

**Comment by mrh0** [comment]
Fixed in 20220817a.
