### ISSUE TITLE
[1.18.2] Failing to Load on Server

### ISSUE THREAD

**Issue by HockeyZman2000** [mrh0/createaddition#315]
**Describe the bug**
The mod is throwing an error trying to load on a multiplayer server.

**Additional context**
- Mod version: 1.18.2-20220813a
- Forge version: 40.1.68
- Create version: 0.5.0.d

[latest.log](https://github.com/mrh0/createaddition/files/9337610/latest.log)

**Comment by mrh0** [comment]
Fixed in 20220817a.
