### ISSUE TITLE
Mod Not Compactable with Flywheel 0.6.5

### ISSUE THREAD

**Issue by TurboFunder** [mrh0/createaddition#317]
**Describe the bug**
Mod does not load with Flyhweel 0.6.5, dispite saying it requires something higher than 0.6.2 and lower than 0.7.0

**To Reproduce**
Load Create Addition with flywheel 0.6.5

**Additional context**
- Mod version: 20220813a
- Forge version: 40.1.68
- Create version: 0.5.0d

[crash-2022-08-15_17.57.42-fml.txt](https://github.com/mrh0/createaddition/files/9343989/crash-2022-08-15_17.57.42-fml.txt)

**Comment by KaziiTheAvali** [comment]
![image](https://user-images.githubusercontent.com/87594664/184844620-31089656-f7d2-4863-a73f-c5d91d71ffa5.png)
image for proof (not the same person just adding more info)

**Comment by LaurenxBurch** [comment]
> ![image](https://user-images.githubusercontent.com/87594664/184844620-31089656-f7d2-4863-a73f-c5d91d71ffa5.png) image for proof (not the same person just adding more info)

its basiclly because now they changed the name of flywheel from 1.18- to 1.18.2-

**Comment by MinoCraft** [comment]
> Had the same issue also. Was planning to look at the source code to change it

Fly Wheel number version has changed no ? Create C&A waiting the wrong version number. 
For me it's a FlyWheel issue but Create 0.5d need FlyWheel 0.6.5

**Comment by dhavyzhn** [comment]
> if you did send me the jar file please !

**Comment by mrh0** [comment]
Fixed in 20220817a.
