### ISSUE TITLE
Translation keys for JEI tabs are wrong

### ISSUE THREAD

**Issue by Grauly** [mrh0/createaddition#319]
**Describe the bug**
The JEI tabs for the Rolling Mill and the Tesla Coil are showing their translation keys:
![2022-08-19_15-44](https://user-images.githubusercontent.com/20888711/185632260-8347e427-9de7-4a43-9a01-7981b7aafcb1.png)
![2022-08-19_15-43](https://user-images.githubusercontent.com/20888711/185632266-3d1e0131-2e90-4c3b-8ce7-1c6463903a91.png)

**To Reproduce**
Install JEI,
Go to JEI and look at the usages for the Rolling Mill and the Tesla Coil 
(requires a mod that has been integrated to have a recipe, i.e ae2)

**Additional context**
- Mod version: 1.18.2-20220817a
- Forge version: 40.1.73
- Create version: 0.5.0d
- Flywheel version: 0.6.5

**Comment by mrh0** [comment]
Update the mod
