### ISSUE TITLE
Client crash when destroy a wired redstone relay

### ISSUE THREAD

**Issue by SrRapero720** [mrh0/createaddition#328]
**Describe the bug**
Client crash when you try to destroy a wired redstone relay (Server actually no crash, only client)
<video src="https://user-images.githubusercontent.com/29090346/187314018-0a95828f-0c14-4f68-8d02-3e7cd8bc8d33.mp4"></video>

**Additional context**
- Mod version: createaddition-1.18.2-20220817a.jar
- Forge version: 40.1.74
- Create version: create-1.18.2-0.5.0.d.jar
- Logs: [2022-08-29-7.log](https://github.com/mrh0/createaddition/files/9448368/2022-08-29-7.log)

**Comment by mrh0** [comment]
Fixed in 20220914a.
