### ISSUE TITLE
crashes when launch

### ISSUE THREAD

**Issue by pandleu** [mrh0/createaddition#330]
when I launch the game it loads and I can see that I'm in the menu for a second but then It goes back to the minecraft loading Mojang screen and It crashes with this error 

The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$13" is null

does anyone have a fix for this?
I'm on minecraft 1.18.2 Fabric 
File version createaddition+1.18.2-1.18.2-20220813a

**Comment by GreenBudgie** [comment]
Please provide a crash report

**Comment by mrh0** [comment]
fixed in 20220911a.
