### ISSUE TITLE
Crashing when observing Alternators via Engineer's Goggles

### ISSUE THREAD

**Issue by VVolfly** [mrh0/createaddition#333]
**Describe the bug**
Crashing when wearing Engineer's Goggles from Create when viewing Alternators

**To Reproduce**
While having the Engineer's Goggles equipped, attempt to view an Alternator. The game then, crashes.

- Mod version: 20220813a
- Fabric version: 0.14.9
- Create version: v0.5d-731

[crash-2022-09-05_05.48.21-client.txt](https://github.com/mrh0/createaddition/files/9488854/crash-2022-09-05_05.48.21-client.txt)

**Comment by VVolfly** [comment]
Had the same issue on our server, what we had to do was teleport the affected player as they reconnected. Hope that works for you.

**Comment by SirSebi** [comment]
yeah worked for me too. Seems like there is also a problem when placing down the Electric motors. Server and Client is insta crashing wenn placing it

**Comment by mrh0** [comment]
fixed in 20220911a.

**Comment by jas777** [comment]
The bug is still present in 20220914a
