### ISSUE TITLE
Crashing when breaking Redstone Relay with wire connected

### ISSUE THREAD

**Issue by VVolfly** [mrh0/createaddition#338]
**Describe the bug**
When breaking redstone relays, the client crashes.

**To Reproduce**
Steps to reproduce the behavior: Place a redstone relay, connect either or both ends with wires then attempt to break the relay block.

**Additional context**
- Mod version: 20220911a
- Fabric version: 0.14.9
- Create version: 0.5.0d-731

[crash-2022-09-11_22.06.48-client.txt](https://github.com/mrh0/createaddition/files/9544131/crash-2022-09-11_22.06.48-client.txt)

**Comment by mrh0** [comment]
Fixed in 20220914a.
