### ISSUE TITLE
Mechanical Tinkerer

### ISSUE THREAD

**Issue by Knalli65HD** [mrh0/createaddition#34]
This might be kinda hard to make
how about a Tinkerer in Electrical and Mechanical version, which could get items from a Weighted ejector, belts etc
but it's so you filter a item you want to craft and this machine will autocraft it :D

**Comment by AbacusOperator** [comment]
Create already has autocrafting.

**Comment by Knalli65HD** [comment]
Yes but this should be crafter and you don't need many mech crafters to make a millstone with that tinkerer

**Comment by mrh0** [comment]
I don't understand the purpose of this.
