### ISSUE TITLE
Crash when placing an Electric Motor with Iris 1.3.1

### ISSUE THREAD

**Issue by nebulazorua** [mrh0/createaddition#343]
The game crashes whenever an Electric Motor is placed within the world when I have Iris 1.3.1 loaded
Without it, it works fine, but with it, I get this crash
[crash-2022-09-13_06.57.45-client.txt](https://github.com/mrh0/createaddition/files/9552281/crash-2022-09-13_06.57.45-client.txt)

**Comment by FluffyBumblebees** [comment]
Try update both C:CA and iris to the latest versions
