### ISSUE TITLE
incompatibility?

### ISSUE THREAD

**Issue by poly-1810** [mrh0/createaddition#347]
**Describe the bug**

**To Reproduce**

install create, flywheel, and create additions, as well as immersive engineering 1.18.2-8.2.1 - 152, then load up a world using forge 40.1.73, and it results in prompting you to enter "safe mode" because one or more errors with your datapacks

**Additional context**
- Mod version: 1.18.2 - 20220914a
- Forge version: 40.1.73
- Create version: 1.18.2 - 0.5.0d

![image](https://user-images.githubusercontent.com/105131270/191395525-6927775e-3d30-4e2a-be2a-a7c390cfad8b.png)

**Comment by krashd** [comment]
I've tested with the versions that you have listed which creates the same results.
Upgrading Immersive Engineering to version 1.18.2-8.2.2-154 resolves this issue.

Working mod combinations:
Forge: 40.1.73
Create: 0.5.0.d
Create Crafts & Additions: 1.18.2-20220914a
Flywheel: 0.6.5
**Immersive Engineering: 1.18.2.8.2.2-154**
