### ISSUE TITLE
Issue with placing electric motor

### ISSUE THREAD

**Issue by jakebussell** [mrh0/createaddition#349]
**Describe the bug**
Placing an electric motor causes a crash, both the instance of Minecraft and the server I am connected to. Same behaviour is replicated in single player.

**To Reproduce**
Initially happened whilst next to a load of other blocks from different mods, but same thing happened in a completely separate location with only vanilla blocks around (cleared out a chunk using world edit specifically). Placed a rolling mill with no problem, but placing either the electric motor caused a crash. Had to reset the chunk using MCASelector to be able to reconnect.

**Additional context**
- Mod version: 20220914a
- Fabric version: 0.14.9
- Create version: 0.5.0c-708

Server  and Single Player crashlogs attached.

--SERVER--
[crash-2022-09-24_21.37.20-server.txt](https://github.com/mrh0/createaddition/files/9639552/crash-2022-09-24_21.37.20-server.txt)

--CLIENT--
[crash-2022-09-24_21.49.46-client.txt](https://github.com/mrh0/createaddition/files/9639569/crash-2022-09-24_21.49.46-client.txt)

**Comment by jas777** [comment]
Try updating to Create 0.5d

**Comment by DougStoker** [comment]
this is happening to me on create 0.5e

**Comment by FluffyBumblebees** [comment]
Should be working properly in my PR
