### ISSUE TITLE
Crash when looking at alternator using Engineer's Goggles

### ISSUE THREAD

**Issue by jakebussell** [mrh0/createaddition#350]
**Describe the bug**
Placing and using the alternator causes no issue, but looking at it whilst wearing Engineer's Goggles appears to cause a rendering issue and crash the instance of Minecraft. When on a server, the server does not crash, only the client.

**To Reproduce**
Place alternator, powered or unpowered, and as soon as it is targeted whilst wearing Create's Engineer's Goggles, the game crashes.

**Additional context**
- Mod version: 20220914a
- Fabric version: 0.14.9
- Create version: 0.5.0c-708

Client crashlog attached: 

[crash-2022-09-25_10.39.15-client.txt](https://github.com/mrh0/createaddition/files/9640440/crash-2022-09-25_10.39.15-client.txt)

**Comment by jas777** [comment]
Update Create to 0.5d, that should help iirc :)

**Comment by jakebussell** [comment]
Yep, all fixed, thank you!
