### ISSUE TITLE
mod giving me an error with my flywheel version while it is correct

### ISSUE THREAD

**Issue by Hiccupwarrior89** [mrh0/createaddition#351]
**Describe the bug**
the game will not start and is giving me an error with my version of flywheel

**To Reproduce**
start the game with the version of flywheel and create: crafts and additions that I'm using

**Additional context**
- Mod version: 1.18.2-20220715a
- Forge version: 40.1.78
![image](https://user-images.githubusercontent.com/114190047/192893369-b699ad41-7083-4036-bf9f-544b979f63f0.png)
- Create version: 1.18.2 0.5.0.e

**Comment by mrh0** [comment]
Update the mod
