### ISSUE TITLE
Redstone relay (again) causes crash when interact

### ISSUE THREAD

**Issue by SrRapero720** [mrh0/createaddition#355]
**Describe the bug**
When interact with redstone relay with redstone crash client only (again)
![image](https://user-images.githubusercontent.com/29090346/196637587-ce18c1c8-8ee6-4e26-8306-2de1987c7a24.png)

**To Reproduce**
- Place a redstone relay
- Place yourself from a side (north is input and south the output, you need to stay right on west or oest)
- place 2 redstone wires in both sides (west and owest)
- inrecact (break or use) redstone coming from the other side
- CRASH

![2022-10-19_03h26_01](https://user-images.githubusercontent.com/29090346/196638589-f87e7d2f-7494-41aa-953b-a90c8ee2b047.png)

CRASH REPORT
https://bytebin.lucko.me/fxqkL3BW3N

CRASHY
https://crashy.net/KBGc3OVnK90goSVOchmN

**Additional context**
- Mod version: createaddition-1.18.2-20220914a.jar
- Forge version: 40.1.84
- Create version: create-1.18.2-0.5.0.e.jar

**Comment by SrRapero720** [comment]
Redstone relay hates me

**Comment by Pultex** [comment]
strange it works in the fabric version with no problem but there is no FE in fabric so maybe it is a FE api problem

**Comment by mrh0** [comment]
Fixed in 20221103a (1.19.2 only, keeping this Issue open)

**Comment by mrh0** [comment]
fixed in 20221117a.
