### ISSUE TITLE
[1.19.2] Game Crash when Immersive Engineering is loaded. 

### ISSUE THREAD

**Issue by ffuentesm** [mrh0/createaddition#357]
**Describe the bug**
https://crashy.net/sMwZdCv3gEPUxo8BJaqO

**To Reproduce**
Load a game with both CC&A and IE in the 1.19.2 version. 
Try to load a previous world that did not have CC&A on it, or Create a New World. 
The game will crash or give a "Datapack Error"

**Additional context**
![image](https://user-images.githubusercontent.com/44974827/197422658-e01cb68b-64d0-4fff-bcd1-ac09b221d986.png)
- Create version: 0.5.0f
- Create Crafts & Additions 1.19.2-20221023a

**Comment by BluSunrize** [comment]
Context:
IE's mineral veins have "spoils" now. Basically the worthless rock you dig up along with the ores.
In 1.18 we added a fix to make the spoils definition optional. In 1.19 this fix has not yet been released - and we're allowing ourselves to make API changes between major versions anyway.

Frankly, this is a perfect opportunity for C&A to update their mineral vein definitions to match IE's standard =)

Here's an example what it looks like:
[Recipe builder](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.18.2/src/api/java/blusunrize/immersiveengineering/api/crafting/builders/MineralMixBuilder.java#L119-L169)
[Finished file](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.18.2/src/generated/resources/data/immersiveengineering/recipes/mineral/chalcopyrite.json#L23-L42)

**Comment by mrh0** [comment]
fixed in 20221024a.
