### ISSUE TITLE
Problem with Immersive Engineering 

### ISSUE THREAD

**Issue by TathanDev** [mrh0/createaddition#358]
**Describe the bug**
It's a bug with Immersive Engineering.
I ask for help in the Immersive Engineering discord server but they told me to report at Create Addition because, I quote :

"_Format for mineral veins has changed
And they clearly did not test with IE_"
                                               BluSunrize

**To Reproduce**
I play with this modpack : https://cdn.discordapp.com/attachments/918929299694829649/1034006366605561876/Friends_SMP_4_Forge.zip

**Additional context**
- Mod version: 20221023a
- Forge version: 1.19.2-43.1.38
- Create version: [0.5.0f](https://www.curseforge.com/minecraft/mc-mods/create/files/4011414)
                                               
The crash report : https://gist.github.com/TathanDev/f460f8dce1fd0c5f5566257c30d0e1b6

**Comment by mrh0** [comment]
fixed in 20221024a.
