### ISSUE TITLE
Game Crash, 1.19.2 if you break the mechanical crafter

### ISSUE THREAD

**Issue by monstaa450** [mrh0/createaddition#359]
**Describe the bug**
This problem appeared as i stalled the newest version of this Mod. Since then i can't Mine/Break the Mechanical Crafter, since then the Game crash every time in the end of the breaking process.

**To Reproduce**
Steps to reproduce the behavior: Survival, break Mechanical Breaker with a Pickaxe.

**Additional context**
- Mod version: createaddition-forge-1.19.2-20221024a
- Create version:  Create 1.19.2 v0.5.0f

**Comment by monstaa450** [comment]
PPs. other Creat Mechanical Blocks have the same issues

**Comment by mrh0** [comment]
cannot reproduce
