### ISSUE TITLE
Electric motors not transferring power

### ISSUE THREAD

**Issue by TheRubyGames** [mrh0/createaddition#360]
When using a creative motor, the electric motor will convert the rotational energy into force energy but will not transfer it through cables. I have tried pipez and immersive. The creative generator works perfectly however. 

1.18.2, Forge vers 40.1.84, Latest create mod and CC&A mod, latest immersive, 
1. Creative motor
2. Electric motor
3. immersive/pipez power cables
4. Connect end to AE/RS system controller

I do not know if this is from the creative motor or the electric motor but from my resting it seems it's the electric motor. Thank you

**Comment by mrh0** [comment]
Use the Alternator to generate electric energy from kinetic energy (motor generates kinetic from electric)
