### ISSUE TITLE
[Suggestion] Immersive Engineering Arc Furnace Automation

### ISSUE THREAD

**Issue by bnjmn21** [mrh0/createaddition#361]
Hello,
I wanted to make a modpack with both Create and Immersive Engineering (and Create Additions), but i really hate that there is no way to fully automate the IE Arc Furnace, as you manually have to input Graphite Electrodes through its GUI.
My idea to solve this is to add a feature to Create's Mechanical Arm so that it can insert the Graphite Electrodes into the Arc Furnace.
I don't know how hard/easy it is to add this functionality but if it worked that would be very cool.

**Comment by mrh0** [comment]
This is a Create centered addon, this is not within its scope
