### ISSUE TITLE
Dangerous Tesla Coil crashes game when activated

### ISSUE THREAD

**Issue by daaanker** [mrh0/createaddition#362]
Dangerous Tesla Coil crashes game when activated

Steps to reproduce the behavior: Place Tesla Coil upright, power it, then activate it with Redstone signal

- Mod version: 1.19.2-20221103a
- Forge version: 1.19.2-43.1.47
- Create version: 1.19.2-0.5.0f 

Crash log: [crash-2022-11-04_09.44.16-server.txt](https://github.com/mrh0/createaddition/files/9939434/crash-2022-11-04_09.44.16-server.txt)

**Comment by mrh0** [comment]
Fixed in 20221104a.
