### ISSUE TITLE
[CRASH] Game does not start after fuel related update

### ISSUE THREAD

**Issue by AndreAugustoAAQ** [mrh0/createaddition#363]
**Describe the bug**
Game does not start after fuel related update
Revert to version  `1.19.2-20221024a` works

**To Reproduce**
1. Start game with version `20221104a` or `20221103a`

**Additional context**
- Mod version: **20221103a**
- Forge version: **43.1.47**
- Create version: **0.5.0f**
- Log: https://mclo.gs/LGGg5wb

**Comment by mrh0** [comment]
I think I managed to fix this in 20221106a, though I was never able to reproduce the crash.

**Comment by AndreAugustoAAQ** [comment]
Incredible! Thank you very much!
Crash fixed.
