### ISSUE TITLE
When my friend tries to join my server using the latest version of Create: Craft and Additions his game crashes

### ISSUE THREAD

**Issue by TimeMonkey12006** [mrh0/createaddition#364]
**Describe the bug**
As the title states when he tries to join my server Create Crafts and Additions has some kind of rendering bug that crashes his game
**To Reproduce**
Multiple people who play on my server don't have this issue except for him so i don't know how to replicate it
**Additional context**
- Mod version: createaddition-1.19.2-20221103a.jar
- Forge version: Forge 43.1.47
- Create version: 
create-1.19.2-0.5.0.f.jar

[crahs.txt](https://github.com/mrh0/createaddition/files/9942582/crahs.txt)
these are his logs

**Comment by keivy-git** [comment]
Hi
I have exactly the same problem...

**Comment by mrh0** [comment]
I think I managed to fix this in 20221106a, though I was never able to reproduce the crash.

**Comment by keivy-git** [comment]
> I think I managed to fix this in 20221106a, though I was never able to reproduce the crash.

solved for me
Thanks
