### ISSUE TITLE
Crash from piping lava into Blaze burner after converting it with the Straw

### ISSUE THREAD

**Issue by Doquekc** [mrh0/createaddition#366]
[crash-2022-11-07_07.45.39-server.txt](https://github.com/mrh0/createaddition/files/9951810/crash-2022-11-07_07.45.39-server.txt)

**Comment by mrh0** [comment]
I don't understand how this is happening, it should be impossible, and I cant reproduce it

**Comment by mrh0** [comment]
Think it was fixed
