### ISSUE TITLE
FE Lightbulb Fixtures

### ISSUE THREAD

**Issue by JackyMaelstrom** [mrh0/createaddition#367]
I'm not sure what format I should write this all down in so I broke up these paragraphs; describing what the suggested addition is, describing pros/cons, describing how it would be used, and describing possible recipe for it.

It's very likely that something like this has already been suggested, but I can't see it in any of the suggestion posts within the last year. Having a light bulb block, or fixture, would maybe not be entirely practical, but it would fit the aesthetic and make a hallway more pleasing to look at than a torch. 

On the downside of using lightbulbs that require being plugged into the FE network, it would really just be a more expensive torch. If power is lost for extended periods of time, the whole area turns into a mob spawner. Not a fun time, but it would really tie in well with the overall visual theme of the Create mod(s).

As for placement in the world, they could just be free-anchored blocks, able to place on any solid surface, similar to connectors (similar in size, as well). Or, they could be required to be placed on an existing connector, unable to be placed elsewhere. It's hard to figure out which one would make more sense. 

The crafting recipe would likely involve an empty glass bottle, though I'm not sure what other components would go into it; a piece of copper wire would suffice as a filament, perhaps.

**Comment by mrh0** [comment]
Cool idea but on within the scope of this mod

**Comment by JackyMaelstrom** [comment]
Could you clarify what you mean by "not within the scope of this mod" so I can curb possible future ideas that may arise?
