### ISSUE TITLE
Tinkers' Construce Compat Recipes are Outdated/Incorrect

### ISSUE THREAD

**Issue by TJT01** [mrh0/createaddition#368]
**Describe the bug**
Some of CC&A's recipes for Tinkers' Construct's materials are out-of-date.  
See the table below for the incorrect recipes.
| |CC&A|Tinkers' Construct|
|-|-|-|
|Amethyst Bronze[^1]|3 Copper Ingot + 1 Glass = *Air*|1 Copper Ingot + 1 Amethyst Shard = 1 Amethyst Bronze|
|Rose Gold|3 Copper Ingot + 1 Gold Ingot = 4 Rose Gold|1 Copper Ingot + 1 Gold = 2 Rose Gold|
|Pig Iron|1 Iron Ingot + 1 Coagulated Blood + 1 Clay Ball = 2 Pig Iron|1 Iron Ingot + 2 Coagulated Blood + 1 Honey Bottle = 2 Pig Iron|
|Hepatizon|1 Obsidian + 1 Cobalt Ingot + 2 Copper Ingot = 2 Hepatizon Ingot|1 Block of Quartz + 1 Cobalt Ingot + 2 Copper Ingot = 2 Hepatizon Ingot|
|Slimesteel|1 Iron Ingot + 1 Skyslime Ball + 1 Seared *Block* = 2 Slimesteel Ingot|1 Iron Ingot + 1 Seared *Brick* = 2 Slimesteel Ingot|

**Additional context**
- CC&A version: 1.18.2-20220914a
- Tinkers' Construct version: 3.5.2.40 for 1.18.2
- Forge version: 40.1.80
- Create version: 0.5.0.e

[^1]: Tinker's bronze was replaced with amethyst bronze in [TiCon 3.2.4.60 for 1.18.1](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct/files/3693992).

**Comment by mrh0** [comment]
fixed in 20221117a.
