### ISSUE TITLE
Disable certain features via Config

### ISSUE THREAD

**Issue by AnOutdatedMind** [mrh0/createaddition#370]
With Immersive Engineering installed you'll have some overlapping content, if I were able to disable the wires, spools and other related features this would be resolved.

**Comment by mrh0** [comment]
Disabling content is not recommended by forge

**Comment by AnOutdatedMind** [comment]
Wait, It isn't? Never mind then, I'd rather have the stability then.
Have a great day and further success with your modding endeavors!
