### ISSUE TITLE
liquid blaze burner not using lava when inserted by pipes

### ISSUE THREAD

**Issue by badgeminer** [mrh0/createaddition#371]
**Describe the bug**
liquid blaze burners are not using lava when inserted by pipes even though the engineer's goggles display that they contain lava

**To Reproduce**
1. place liquid blaze burner
2. pipe in lava

**Additional context**
- Mod version: 1.19.2-20221106a
- Forge version: 43.1.47 (1.19.2)
- Create version: 0.5.0f

**Comment by mrh0** [comment]
Its not supposed too, by default, use kubejs or craft tweaker to add lava.

**Comment by mrh0** [comment]
Should be fixed in 20221116a.
