### ISSUE TITLE
Liquid Blaze Burners Crashing server due to NoSuchElementException

### ISSUE THREAD

**Issue by AussieWarGod** [mrh0/createaddition#372]
**Describe the bug**
When pumping Lava into the blaze burner and triggering them to burn, the server crashes with a NoSuchElementException

**To Reproduce**
Pump lava into blaze burner
Trigger blaze burner with lava bucket or blaze rod
server will crash

**Additional context**
- Mod version: 1.19.2-20221106a
- Forge version: 1.19.2-43.1.47
- Create version: 1.19.2-0.5.0.f
- Modpack: ATM 8 1.0.1

crash log:
[crash-2022-11-13_23.05.04-server.txt](https://github.com/mrh0/createaddition/files/9997146/crash-2022-11-13_23.05.04-server.txt)

**Comment by AussieWarGod** [comment]
I have realised this is a duplicate having a second look at the issues log, but as the other issue has very minimal detail i'll leave this here.

**Comment by mrh0** [comment]
Should be fixed in 20221116a.
