### ISSUE TITLE
possible crafting issue 

### ISSUE THREAD

**Issue by SniffSniff125** [mrh0/createaddition#374]
i am not sure if the problem is caused by this mod or create
i was able to craft normally, but then the crafting systed just stopped working for almost all items of this mod and create mod
i did not rejoin nor removed/changed anything
this is what happens when i try to craft any item of create: (i was able to craft only andesite ladders)
![2022-10-09_19 29 40](https://user-images.githubusercontent.com/115304349/201539745-1bfdd765-69d6-461e-99c4-c885422aa77e.png)

**To Reproduce**
im unable to give instruction on how to reproduce this bug, as i do not know what caused this

**Additional context**
- Mod version: 20220914 (create additions) , 6.5 (flywheel)
- Forge version: 40.1.80 (1.18.2)
- Create version: 0.5.0e (1.18.2)
-i have some mods, but none of them gave me any problem
i do not know for sure if this problem is caused by create mod/related addons or by other mods. im willing provide logs and everything that can help to solve this.
i posted an issue on create's github more than a month ago, but no one replied.

if you need more info just ask.

thanks for your time.

**Comment by mrh0** [comment]
I don't think this has anything to do with my mod, and besides, you don't give enough information for me to be able to investigate this.
