### ISSUE TITLE
1.18.2 Fabric Scannable scanners not charged by Tesla.

### ISSUE THREAD

**Issue by WDLBPH** [mrh0/createaddition#376]
1.18.2 on fabric, [1.7.7+67bcbed.jar](https://www.curseforge.com/minecraft/mc-mods/scannable/files/3781153) the scanners from Scannable don't take fe from the Create Crafts and Additions version -20220914a.jar tesla coil charger, and is therefore useless on multiplayer survival. Also reported to the Curseforge page and the Scannable pages.

**Comment by mrh0** [comment]
dupe of #261
