### ISSUE TITLE
Energy typo

### ISSUE THREAD

**Issue by oguh43** [mrh0/createaddition#38]
**Describe the bug**
Stored energy shows Kfefe instead of Kfe

**To Reproduce**
Steps to reproduce the behavior: Look at the electric motor with engineers googles

**Additional context**
- Mod version: createaddition-1.16.5-20210404a
- Forge version: forge-1.16.5-36.1.2
- Create version: create-mc1.16.5_v0.3.1a
![image](https://user-images.githubusercontent.com/13382592/114144345-859db400-9915-11eb-9319-3c376692627d.png)

**Comment by mrh0** [comment]
Resolved 20210410a
