### ISSUE TITLE
New update to Fabric Create Crash

### ISSUE THREAD

**Issue by Daihok41** [mrh0/createaddition#380]
**Describe the bug**
Getting crash with the newest create additions fabric 1.19.2 version. Create updated not long after the release of initial fabric release

It Did work with the 1.19.2 0.5.0f version

**To Reproduce**
Put in newest version of Create Fabric 1.19.2 0.5.0g

**Additional context**
- Mod version: 1.19.2 - 20221122a
- Fabric version: 0.14.10
- Create version: 1.19.2 - 0.5.0g -791

Here is crash report 
https://pastebin.com/vThbG40T

**Comment by xijtsjis** [comment]
Same on 1.18.2.

**Comment by MSandro** [comment]
same here (1.18.2)
https://github.com/Fabricators-of-Create/Create/issues/619

**Comment by MSandro** [comment]
I hope this issue can be fixed very soon.

**Comment by mrh0** [comment]
Fixes in 20221219a.
