### ISSUE TITLE
Crash with steam engine and boilers

### ISSUE THREAD

**Issue by GlorifiedToastr** [mrh0/createaddition#384]
**Describe the bug**
Crash when not all create fluid tanks have blaze burners under them when placing steam engines.

**To Reproduce**
1. Create a 2x2 or 3x3 fluid tank stack
2. Add blaze burners under fluid tanks and exclude 1 or spaces (ex. 2x2 tank setup add only 3 or less blaze burners)
3. Add steam engines
4. Crash happens upon addition of steam engines at step 3

Disabling Create Crafts And Additions results in everything working as normal following the same steps listed above.

**Additional context**
- Mod version: createaddition+1.19.2-1.19.2-20221124b
- Fabric version: 0.14.10
- Create version: 0.5.0g-791+1.19.2
- Error Log URL https://mclo.gs/ZMfNV7M

(Edit Adding Log URL)

**Comment by TheDrLucky** [comment]
Same BUG ! 
https://mclo.gs/BTMedwB

**Comment by ajh123** [comment]
#407 also experienced the same bug. However it **may** of gained the developers attention.

**Comment by mrh0** [comment]
Fixes in 20221219a.
