### ISSUE TITLE
Crash with Vanity Splash Text, due to the ${version} label

### ISSUE THREAD

**Issue by SplendidAlakey** [mrh0/createaddition#386]
**Describe the bug**

The game crashes, if Vanity Splash Text and Crafts and Additions are installed together, because Vanity Splash Text is trying to look for the mod's version, but instead finds `${version}`. I can simply add the mod to the ignore list of VST for now, but would like to see the issue fixed, so that the mod can be featured in vanity splashes.

**To Reproduce**

1. Install Create, Crafts and Additions and [Vanity Splash Text](https://www.curseforge.com/minecraft/mc-mods/vanity-splash-text)
2. Launch the game

**Additional context**

- Mod version: 1.19.2-20221124b
- [Quilt](https://www.curseforge.com/minecraft/mc-mods/qsl) version: 4.0.0-beta.21
- Create version: 0.5.0g

Logs: https://gist.github.com/SplendidAlakey/33b36319d48324ce549525592a667d19

**Comment by mrh0** [comment]
Not familiar with vanity splash but this looks like a vanity spalsh error mor than a cc&a error

**Comment by SplendidAlakey** [comment]
There was another mod, that caused the same crash, and they fixed it on their side. Is it something you could replicate? The fix looks simple https://github.com/AbsolemJackdaw/FatChickens/issues/3
