### ISSUE TITLE
Attempting to fuel liquid blaze burner with pipes results into crash

### ISSUE THREAD

**Issue by Firestrike1** [mrh0/createaddition#387]
[crash-2022-11-26_00.14.52-server.txt](https://github.com/mrh0/createaddition/files/10094510/crash-2022-11-26_00.14.52-server.txt)
*Describe the bug**
Fueling a blaze burner that was given a straw through pipes crashes the game

**To Reproduce**
Give blaze burner a straw
Connect a liquid tank with bioethanol to it
Pump the fuel using mechanical pump

**Additional context**
- Mod version: createaddition+1.19.2-1.19.2-20221124b
- Fabric version: fabric-api-0.67.1+1.19.2
- Create version: create-fabric-0.5.0g-791+1.19.2
![2022-11-26_00 38 34](https://user-images.githubusercontent.com/88449275/204034557-d01f5c8c-88c9-4b84-8124-a6fcfcd2c8fa.png)

**Comment by mrh0** [comment]
Pretty sure this was fixed
