### ISSUE TITLE
Server will not start with mod present

### ISSUE THREAD

**Issue by Chburbsgeeser** [mrh0/createaddition#388]
**Describe the bug**
The bisect server I am using will not start, stating that "Create Crafts & Additions (createaddition) has failed to load correctly"

**To Reproduce**
Put createaddition-1.18.2-20221117a.jar in the mod folder
start the bisect server

**Additional context**
- Mod version: createaddition-1.18.2-20221117a.jar
- Forge version: 40.1.79
- Create version: create-1.18.2-0.5.0.e.jar

[latest.log](https://github.com/mrh0/createaddition/files/10095075/latest.log)
The server log for when I try and run it

**Comment by mrh0** [comment]
Update, you are running an old version

**Comment by Chburbsgeeser** [comment]
updated to version "createaddition-forge-1.18.2-20221122a" still does not work

**Comment by Chburbsgeeser** [comment]
[latest (1).log](https://github.com/mrh0/createaddition/files/10095123/latest.1.log)

**Comment by Chburbsgeeser** [comment]
changed to version "[createaddition-forge-1.18.2-20220914a]" and it works

**Comment by mrh0** [comment]
Ah, you are running an old create version
