### ISSUE TITLE
Crash on Quilt 1.18 with latest version of Create and Create Additions

### ISSUE THREAD

**Issue by Aquaeyes** [mrh0/createaddition#395]
**Describe the bug**
Crash upon startup.

**To Reproduce**
Start game. Only mods present are Quilt API, Create Crafts & Additions, and Create. Running on M1 chip. Also tested with compiling latest fabric build, crash still occurs.

https://mclo.gs/1O5ZWkv

**Additional context**
- Mod version: createaddition+1.18.2-20220914a
- Fabric version: qfapi-1.0.0-beta.28_qsl-1.1.0-beta.26_fapi-0.67.0_mc-1.18.2
- Create version: create-fabric-0.5.0g-792+1.18.2

**Comment by mrh0** [comment]
old version, update

**Comment by Aquaeyes** [comment]
createaddition-fabric-1.18.2-20220914a is the latest available though? Should I be updating something else?
