### ISSUE TITLE
Request for "missing" plate/wire recipes

### ISSUE THREAD

**Issue by IacobusBarbatus** [mrh0/createaddition#398]
In a playthrough I noticed that a Steel ingot would not press into a plate using Create's Mechanical Press, even though this would be a reasonable workflow.  Currently the only way to make IE Plates using Create machines is shapeless crafting with the IE Hammer. Similar gaps exist for the CC&A Rolling Mill (only for lead wire--thank you for adding other IE wire recipes).

Would it be possible to add the "missing" recipes for the Create Mechanical Press and CC&A Rolling Mill?
- IE Ingots to IE Plates in Mechanical Press:
    - Aluminum
    - Lead
    - Silver
    - Nickel
    - Uranium
    - Constantan
    - Electrum
    - Steel
- IE Plates to IE Wires in Rolling Mill:
    - Lead wire (used in IE as solder)

**Comment by IacobusBarbatus** [comment]
I was looking at some of the other recipes in the code to see if I could work through some of it myself.  I *think* these will work based on the other IE-related recipes in createaddition/src/main/resources/data/createaddition/recipes/

I'm not experienced enough with github to fork the mod and test myself, but if these do work, please feel free to add and use them.

[Issue_398.zip](https://github.com/mrh0/createaddition/files/10116850/Issue_398.zip)

**Comment by mrh0** [comment]
Fixed in 20221220a.
