### ISSUE TITLE
Alternator only gives off power every second.

### ISSUE THREAD

**Issue by Darth-Pikachu** [mrh0/createaddition#4]
Maybe I should list this as an enhancement, but it's kind of weird, and different from how most power machines/generators work. (At the very least, a config option would be nice.)

Basically, the alternator gives off a certain amount of power every second instead of giving off the power every tick. Nothing is technically wrong with this, it's just a bit of an oddity.

Also displaying it in power per second makes the player have to divide by 20 when trying to calculate how much power it's actually outputting(Which can cause a bit of confusion for some.)

Consider this really low priority I suppose.

**Comment by mrh0** [comment]
Yeah, I did consider doing fe/t I did fe/s mostly because as you said that's how it operates but it might change it. I made it run every second because that's more CPU friendly less tick lag; I believe Immersive Engineering also does that if I'm not mistaken.
