### ISSUE TITLE
curseforge launcher is listing the 1.18.2 version as 1.19.2

### ISSUE THREAD

**Issue by sumimaiku** [mrh0/createaddition#404]
**Describe the bug** 
createaddition+1.18.2-fabric-1.18.2-20221129a.jar is appearing as a 1.19.2 file/update in curseforge launcher and does cause the game not to crash giving this popup "Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create Crafts & Additions' (createaddition) ${version} with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'Create Crafts & Additions' (createaddition) ${version} requires any version between 1.18.2 (inclusive) and 1.19- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)"

**To Reproduce**
Steps to reproduce the behavior: update create addition thru curseforge system and it will cause the game not to run.

**Additional context**
- Mod version: createaddition+1.18.2-fabric-1.18.2-20221129a.jar
- Fabric version: 0.14.10
easy fix just wanted to let you know

**Comment by mrh0** [comment]
Its been fixed
