### ISSUE TITLE
Crafting infinite "empty spools" out of nothing

### ISSUE THREAD

**Issue by odracius** [mrh0/createaddition#406]
**Describe the bug**
When using a crafting table, if i put some item in the grid, then remove it, empty spools will appear as a craft result.

**To Reproduce**
Use a crafting table, put any item in the crafting grid (random patterns works), them clear the grid. 

**Additional context**
- Mod version: createaddition+1.19.2-1.19.2-20221128a
- Fabric version: 0.14.11
- Create version: create-fabric-0.5.0g-796+1.19.2
![issueca1](https://user-images.githubusercontent.com/119794105/205491620-d7118dba-d696-4376-ab35-a5956de0cfb6.png)
![issueca2](https://user-images.githubusercontent.com/119794105/205491621-f4539a79-1bee-4de4-830b-8ad3e8e6713c.png)

**Comment by mrh0** [comment]
Dope of #401
