### ISSUE TITLE
Game version mislabeled 

### ISSUE THREAD

**Issue by SylisMC** [mrh0/createaddition#409]
**Describe the bug**
1.18.2 jar labeled for 1.19.2

![image](https://user-images.githubusercontent.com/19602662/206321544-dc1a81e4-878f-42c6-bf30-d4c777141303.png)

**Comment by mrh0** [comment]
This was fixed a week ago, it's correct on the website

**Comment by SylisMC** [comment]
> This was fixed a week ago, it's correct on the website

I see that, I wonder why its not updated on the curse launcher, their program is so infuriating..

**Comment by SylisMC** [comment]
I opened a ticket with curseforge, i see this kinda issue a lot,  hopefully they will resolve it

**Comment by mrh0** [comment]
reuploaded the file and achieved the old one.
