### ISSUE TITLE
[Fabric][1.19.2] Diamond Git Not Craftable

### ISSUE THREAD

**Issue by Random-Cookie** [mrh0/createaddition#410]
**Describe the bug**
Diamond grit is not craftable.

**To Reproduce**
Steps to reproduce the behaviour:
Setup grinding wheels as so:
![2022-12-09_09 08 49](https://user-images.githubusercontent.com/11795182/206666212-5a634c9c-035e-4115-9ab0-01e37dd2eab7.png)
Put diamonds in.
Expected: Diamond grit out
Observed: no output

**Additional context**
Pretty sure this is the issue
![image](https://user-images.githubusercontent.com/11795182/206664868-60e5afe3-97e4-4c79-9bc0-364387e6c5f5.png)

- Mod version: 1.3.0
- Fabric version: 0.14.11
- Create version: 0.5.0g-796+1.19.2

**Comment by Random-Cookie** [comment]
created #411
Update to use Minecraft default
not sure if someone else knows of a fabric generic, but I don't and this will fix the issue for now.

**Comment by Random-Cookie** [comment]
Managed to build and test these changes:
REI recipe:
![image](https://user-images.githubusercontent.com/11795182/206746538-660bc83d-5b68-42ec-9843-7eb148d82596.png)
Result:
![image](https://user-images.githubusercontent.com/11795182/206746636-e425f2ad-3f7c-4704-adc9-e20cd1bee824.png)

**Comment by mrh0** [comment]
Fixes in 20221219a.
