### ISSUE TITLE
[Fabric][1.19.2] Mechanical Crafting recipie Fixes

### ISSUE THREAD

**Issue by Random-Cookie** [mrh0/createaddition#412]
**Describe the bug**
Create c item references have changed
This has affected the plates in the mechanical crafting recipes.
This means the items were not craftable and also clicking on the item in REI would crash the game

**To Reproduce**
see above

**Additional context**
Mod version: 1.3.0
Fabric version: 0.14.11
Create version: 0.5.0g-796+1.19.2

**Comment by Random-Cookie** [comment]
Created this to update the plat and ingot specifiers in the crafting recipes: https://github.com/mrh0/createaddition/pull/413
Have built and tested and works spot on

**Comment by mrh0** [comment]
Fixes in 20221219a.
