### ISSUE TITLE
1.18.2 Launcher Crash due to mod

### ISSUE THREAD

**Issue by Failbomb** [mrh0/createaddition#414]
**Describe the bug**
the image should help but it causes an error code 1 and crashes the game client everytime i press play

![Screenshot 2022-12-11 021040](https://user-images.githubusercontent.com/43086339/206891028-60677a36-975e-4dae-9e72-6f2618eb27ce.jpg)

**Additional context**
- Mod version: 1.18.2
- Forge version: 40.1.85
- Create version: 1.18.2-20221122a.jar

**Comment by mrh0** [comment]
Could you supply a full log?
