### ISSUE TITLE
CCA causing server to crash when using steam boilers

### ISSUE THREAD

**Issue by Miyazono1** [mrh0/createaddition#416]
**Describe the bug**
after adding CCA to my server, breaking or placing any block related to steam boilers will crash the server

**To Reproduce**
1. form a fluid tank
2. add a steam engine to the side
3. OR break any of the blocks of the tank after the engine is placed

- Mod version: 1.19.2-1.19.2-20221128a
- Fabric version: 0.68.0
- Create version: create-fabric-0.5.0g-796+1.19.2
[crash-2022-12-11_19.31.32-server.txt](https://github.com/mrh0/createaddition/files/10203768/crash-2022-12-11_19.31.32-server.txt)

**Comment by ajh123** [comment]
Related to #407

**Comment by mrh0** [comment]
Fixes in 20221219a.
