### ISSUE TITLE
[1.19.2-20221128a] fabric rolling mill doesn't accept copper sheets 

### ISSUE THREAD

**Issue by JamesBaker381** [mrh0/createaddition#418]
Rolling mill will not manually accept copper sheets however it will accept copper ingots and turn them into rods as it should. Rolling mill also will not accept copper sheets through funnels again ingots work fine :
![image](https://user-images.githubusercontent.com/120513768/207428241-6c4cf216-f259-456f-b571-6b05864b4ad0.png)

**To Reproduce**
- Install Create mod and Create additions
- Drop copper sheets onto powered rolling mill
- Nothing will happen no particles will be emitted no items will be converted the copper sheets will not be used up

Also recipes in rei for the rolling mill show up with the correct output item and ui but no input item:
![image](https://user-images.githubusercontent.com/120513768/207428028-f2706547-1390-468b-8f87-ab80e514bff9.png)

**To Reproduce**
- Install Roughly Enough Items, Create mod and Create additions
- Search for anything which is made with the rolling mill for example copper wires
- Hover over said item and press r

**Additional context**
- Mod version: 20221128a
- Fabric version: 0.14.11
- Create version: 0.5.0g-796

**Comment by mrh0** [comment]
Fixes in 20221219a.
