### ISSUE TITLE
Boiler heater is registered too early, causing crashes

### ISSUE THREAD

**Issue by TropheusJ** [mrh0/createaddition#419]
The `LIQUID_BLAZE_BURNER` heater is [registered before](https://github.com/mrh0/createaddition/blob/9c17d12f5dd66411468cb66d243865e0af2ea3e7/src/main/java/com/mrh0/createaddition/CreateAddition.java#L40) the [block is registered](https://github.com/mrh0/createaddition/blob/9c17d12f5dd66411468cb66d243865e0af2ea3e7/src/main/java/com/mrh0/createaddition/CreateAddition.java#L63). Registered blocks are [looked up in the registry](https://github.com/Fabricators-of-Create/Create/blob/7a5f31c0bea14fd0236fdbe8ffb5828ed3893742/src/main/java/com/simibubi/create/foundation/utility/CreateRegistry.java#L47), but since it's not registered yet, air is found. So when the heater is called, it gets air, checks for a property that doesn't exist on air, and the game crashes.
Fix is simple, move the heater registration after block registration (bottom of onInitialize).

Supersedes #416, #407, #384

**Comment by ajh123** [comment]
@mrh0 Please look at this!

**Comment by FluffyBumblebees** [comment]
ye I ended up switching to resource locations for the fabric branch. Works like a charm.

**Comment by mrh0** [comment]
Fixes in 20221219a.
