### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by festro** [mrh0/createaddition#421]
**Describe the bug**
latest Update of create has broken the mod.

**To Reproduce**
Start the the game, during load is stops with error

**Additional context**
- Mod version: createaddition-1.19.2-20221124a.jar
- Forge version: 43.2.0
- Create version: create-1.19.2-0.5.0.g.jar
Here's the crash log 
[crash-2022-12-14_13.22.39-fml.txt](https://github.com/mrh0/createaddition/files/10231784/crash-2022-12-14_13.22.39-fml.txt)

**Comment by mrh0** [comment]
Fixed in 20221215.
