### ISSUE TITLE
Blazing Blood from TConstruct is not recognized as liquid fuel. Crashes game on right-click.

### ISSUE THREAD

**Issue by Narwhalian** [mrh0/createaddition#425]
**Describe the bug**
'Blazing Blood' from TConstruct is not recognized as liquid fuel for use with Straws. You can pump it into the Blaze Burner, but it won't utilize any of the liquid. Additionally, directly using a Bucket of Blazing Blood on a Straw-less Blaze Burner works fine, but when performed on a Blaze Burner with a Straw attached will crash the game.
In general, a way to add new types of liquid fuels via the Config would be very much appreciated.

**To Reproduce**
Pump Blazing Blood into a Blaze Burner with a Straw attached.
For the Crash: Use a Bucket of Blazing Blood on a Blaze Burner with a Straw Attached.

**Additional context**
- Mod version: 20221122a
- Forge version: 40.1.74
- Create version: 0.5.0.d

Crash Log: https://paste.ee/p/HXtMh

**Comment by Grimalakin** [comment]
Similar issue with Creosote oil from Immersive Engineering.
You can pump it into the burners, but they won't use any of the liquid. Right-clicking with a bucket or jerrycan with the oil crashes the game (only client side)

**To Reproduce**

- [Pump Creosote oil into a Blaze Burner with a straw attached
Use a bucket (or jerrycan) of Creosote oil on a Blaze Burner with a straw attached]

Was playing Stoneblock 3 version 1.4.3

**Comment by mrh0** [comment]
Fixed in 20221220a.
