### ISSUE TITLE
[Forge] 1.19.2 - Blocks are visible when placed, but become invisible

### ISSUE THREAD

**Issue by gaineyjmichael** [mrh0/createaddition#427]
Blocks are becoming invisible when stopping after moving, when using with other mods, or when vein mined. 

Example: Windmill sails become invisible when stopping windmill motor or activating Minecart assembly.
Limestone blocks become invisible when using Construction Mod. 

Can then right click on the blocks to have them become visible again. Blocks also become visible when logging out and logging back in. 

Create Version: create-1.19.2-0.5.0.g.jar (Also an issue with Create Version: create-1.19.2-0.5.0.f.jar)
Create Crafts & Additions: createaddition-1.19.2-20221215a.jar (Also an issue with version: createaddition-1.19.2-20221124a.jar)

**Comment by mrh0** [comment]
These examples are all of Create blocks, sounds like a Create bug or incompatibility with another mod (shaders?)

**Comment by QianFuv** [comment]
Try [Block Limit Fix](https://www.curseforge.com/minecraft/mc-mods/block-limit-fix)
