### ISSUE TITLE
蒸汽储罐出现错误

### ISSUE THREAD

**Issue by txs1234** [mrh0/createaddition#428]
**Describe the bug**
当撤去蒸汽储罐下方的热源时导致游戏崩溃

**To Reproduce**
1.放置流体储罐
2.将流体储罐变为蒸汽引擎
3.放置热源(在蒸汽引擎下方)
...
**Additional context**
- Mod version:20221128a
- Fabric version:quilt0.18.1beta25
- Create version:0.5.0g
已证实此bug由createaddition引起

**Comment by mrh0** [comment]
Fixes in 20221219a.
