### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by MR-Spagetty** [mrh0/createaddition#435]
**Describe the bug**
Game crashes trying to load Create: crafts & Additions

**To Reproduce**
launch the game with C: C&A installed

**Additional context**
- Mod version: createaddition-1.19.2-20221124a
- Forge version: 43.2.0
- Create version: create-1.19.2-0.5.0.g
[crash-2022-12-21_22.21.39-fml.txt](https://github.com/mrh0/createaddition/files/10276432/crash-2022-12-21_22.21.39-fml.txt)
[latest.log](https://github.com/mrh0/createaddition/files/10276435/latest.log)

**Comment by mrh0** [comment]
Old version, Update the mod.

**Comment by MR-Spagetty** [comment]
for some reason curseforge wasn't giving the update button so i didnt realize it wasn't the latest version
