### ISSUE TITLE
Native EMI Support Broken

### ISSUE THREAD

**Issue by Aquaeyes** [mrh0/createaddition#438]
**Describe the bug**
Using Create Addition breaks support for Mixing, Splashing, Sequenced Assembly, Shapeless basin crafting, etc in EMI. It also removes the barrel from the item vault recipe.

**To Reproduce**
Steps to reproduce the behavior: Install EMI, alongside Create and Create Additions.
Press R on any sturdy sheets, and R on any item vault to see the aforementioned issues.

**Additional context**
- Mod version: create-fabric-0.5.0g-796+1.19.2, createaddition+1.19.2-1.19.2-20221218a, emi-0.5.3+1.19.2, qfapi-4.0.0-beta.25_qsl-3.0.0-beta.24_fapi-0.70.0_mc-1.19.2
- Fabric version: 0.70.0
- Create version: 0.5.0g.796.1.19.2

<img width="270" alt="image" src="https://user-images.githubusercontent.com/10935410/209475174-dc79f287-0541-4ae3-b078-e78f26b268ce.png">

Following: a list of the only supported recipe types with create additions installed.
<img width="235" alt="image" src="https://user-images.githubusercontent.com/10935410/209475185-d4fbf637-5e46-4c54-8cee-466478e05466.png">
<img width="105" alt="image" src="https://user-images.githubusercontent.com/10935410/209475196-65b86e78-c97b-4e1a-aae9-3a4b7e38b3aa.png">

Without:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/10935410/209475248-766a6a1c-aca7-4b65-b637-185276ec9f12.png">
<img width="235" alt="image" src="https://user-images.githubusercontent.com/10935410/209475257-a9dbedfa-41be-4151-9f5b-f18cff7c74c2.png">
<img width="230" alt="image" src="https://user-images.githubusercontent.com/10935410/209475269-d133ac7f-5109-4c1b-9dd4-c67384528ca1.png">
<img width="168" alt="image" src="https://user-images.githubusercontent.com/10935410/209475276-f89d0f32-3918-4064-8466-55a0f25e15b5.png">

I'm very sorry =^='

**Comment by Aquaeyes** [comment]
It's one of the biomass recipes doing this.

**Comment by secretmeister** [comment]
This seems to have been fixed, as a lot of the mods have updated.
