### ISSUE TITLE
Empty Spool crafting bug

### ISSUE THREAD

**Issue by NickDummermuth** [mrh0/createaddition#439]
**Describe the bug**
A clear and concise description of what the bug is. Empty spool appears whether you've crafted one or not.

**To Reproduce**
Steps to reproduce the behavior: Put any item into the crafting bench, or craft anything from the crafting bench, and as soon as you pull your item out, an empty spool will appear.

**Additional context**
- Mod version: createaddition+1.19.2-1.19.2-20221128a
- Fabric version: 0.14.11-1.19.2
- Create version: 0.5.0g-796+1.19.2

**Comment by Kiwi-Co** [comment]
Does redstone relay and rolling mill work for you?

**Comment by mrh0** [comment]
Fixed
