### ISSUE TITLE
Diamond Grit Sandpaper Compatibility with JEI

### ISSUE THREAD

**Issue by The-Math-Fish** [mrh0/createaddition#44]
Currently all of Create's various crafting techniques (even the "mysterious" ones) show all their recipes in JEI and update with Crafttweaker changes.

I would like if the Diamond Grit Sandpaper mimicked the behavior of its Create counterparts (Sand Paper and Red Sand Paper) in this regard. Here is an image to give you an idea what I'm talking about. This is what appears for Sand Paper when I show uses for it with JEI:

![image](https://user-images.githubusercontent.com/82321657/115113436-519b4200-9f58-11eb-9322-7c3455481204.png)

**Comment by mrh0** [comment]
Yes, I'm aware of this issue, not sure it is possible to resolve but I will look into it.

**Comment by mrh0** [comment]
Fixed in 20210419a.
