### ISSUE TITLE
[1.18.2] Crash on dedicated server

### ISSUE THREAD

**Issue by AzureDoom** [mrh0/createaddition#442]
**Describe the bug**
Mod crashes if loaded on dedicated server due to call to client code in Flywheel.

**To Reproduce**
Steps to reproduce the behavior: load the mod on server. See crash report: https://gist.github.com/AzureDoom/16512f52caee75a2df7232c6d87fe86c

**Additional context**
- Mod version: createaddition-1.18.2-20221219a.jar
- Forge version: 40.1.92
- Create version: create-1.18.2-0.5.0.g

**Comment by Yoshimar1** [comment]
Having identical issue on forge version 40.1.86 and create additions version 1.18.2-20221215a
I also do not have the Flywheel or related mods installed, yet still receive this error.

**Comment by AzureDoom** [comment]
> I also do not have the Flywheel or related mods installed, yet still receive this error.

Flywheel is integrated in Create itself now.

**Comment by mrh0** [comment]
Create 1.18.2 still requires Flywheel, its only integrated in >1.19.2

**Comment by Xplodin** [comment]
mod definitely crashes on server along with a few other addons.
