### ISSUE TITLE
1.18.1 wire power tansfer to machines

### ISSUE THREAD

**Issue by GunMetalBlack** [mrh0/createaddition#446]
**Describe the bug**
Machines half the time will not receive power from wires like the connection doesn't work. Even machine from you mod like motors and furnace heater. It seems random sometime when I reconnect it would work and others it just won't give power. 

**To Reproduce**
Steps to reproduce the behavior: I made a video showcasing the problem. [Video](https://youtu.be/IWGtM0xwVrM) 

**Additional context**
- Mod version: newest for 1.18 1
- Forge version: newest for 1.18.1
- Create version:0.4

**Comment by mrh0** [comment]
CC&A for 1.18.1 is no longer supported
