### ISSUE TITLE
[Fabric - 1.19.2] - Missing drops

### ISSUE THREAD

**Issue by p4rty4nimAl** [mrh0/createaddition#455]
**Describe the bug**
When breaking alternators, liquid blaze burners and accumulators (this list is likely not exhaustive), not only does the correct tool not appear to be a pickaxe (in line with Create), but the correct drops are not dropped; none are dropped. Furthermore, using a wrench seems to correct this on alternators and accumulators, but liquid blaze burner still drops nothing, where I would expect at least the blaze burner itself to drop.

**To Reproduce**
 - Create an alternator, liquid blaze burner or accumulator (or potentially others)
 - Place it
 - Try and break the placed block
 - Note that there are no drops.

**Additional context**
- Mod version: 20221218a
- Fabric version: 0.14.10
- Create version: v0.5.0g-796

**Comment by mrh0** [comment]
I think this has been fixed
