### ISSUE TITLE
Doesn't support quilt

### ISSUE THREAD

**Issue by ryleu** [mrh0/createaddition#457]
**Describe the bug**
[The game crashes when attempting to launch with Quilt](https://mclo.gs/34pi4sp)

**To Reproduce**

Install Quilt 0.17.8

Install the mods

Attempt to launch the game

**Additional context**
- Mod version: NONE (according to the jar... this might be something else to fix)
- Quilt version: 0.17.8
- Create version: 0.5.0f-776

**Comment by FluffyBumblebees** [comment]
this crash has nothing to do with quilt, you're using an outdated C:CA
