### ISSUE TITLE
Fluid recipe display behavior with REI

### ISSUE THREAD

**Issue by thehobojoe** [mrh0/createaddition#458]
**Describe the bug**
With REI, all fluid recipes have a serious display bug, it appears to be some sort of recursion. This happens with both fluids from create additions, but no other fluids in the game. Happens with built-in recipes, and with any datapack created recipes.

https://user-images.githubusercontent.com/3493638/213396847-930ee052-729b-480e-b90d-76fa11060c35.mp4

**To Reproduce**
Simple mouse over the output of a recipe with REI for seed oil or bioethenal

**Additional context**
- Mod version: 1.19.2-20221218a
- Fabric version: 0.14.12
- Create version: 0.5.0g-796

**Comment by mrh0** [comment]
Fixed in 20230508b.
