### ISSUE TITLE
Redstone relay doesn't work

### ISSUE THREAD

**Issue by Ogirdor667** [mrh0/createaddition#460]
**Describe the bug**
Redstone relay doesn't react to redstone in any way, being stuck in unpowered state.
Can only be set to powered by using a debug stick.
![image](https://user-images.githubusercontent.com/123264290/213881795-b104cd42-6d26-497c-a67d-e33ab025476e.png)
**To Reproduce**
.Place a redstone relay
.Try to activate it with redstone
**Additional context**
- Mod version: createaddition+1.19.2-1.19.2-20221218a
- Fabric version: 0.14.12
- Create version: create-fabric-0.5.0g-796+1.19.2

**Comment by txs1234** [comment]
I had the same problem

**Comment by FluffyBumblebees** [comment]
the redstone relay has been broken for a while. Unfortunately, I have no idea what is going on because Redstone block state code is horrible.

**Comment by antonioscarpino** [comment]
Same problem

    Mod version: createaddition-fabric-1.19.2-20230211a (Beta)
    Fabric version: 0.14.19
    Create version: create 1.19.2 v0.5.0.i Patch 5 (Beta)

**Comment by Hyperbus02** [comment]
This is still broken for us too

**Comment by mrh0** [comment]
Fixed in 20230508a.
