### ISSUE TITLE
[Suggestion] Energy charger block for tools

### ISSUE THREAD

**Issue by A00826925** [mrh0/createaddition#463]
i know other mods already have charging stations, however, what it by chance you have a mod that has tools that need charge, but the only tech mod you have installed is create and Create crafts and additions.

Well that happened to me, i wanted to charge tools from the Building Gadgets mod, but i dont have any way to charge the items since there are no charging stations with create. (orm aybe there are, but so far i didnt find them, ill delete this if i do)

**Comment by mrh0** [comment]
The Tesla Coil can be used to charge items, see in-game Ponder.

**Comment by A00826925** [comment]
whoops, my bad, thanks!
