### ISSUE TITLE
Missing straw recipe

### ISSUE THREAD

**Issue by ItchyNitchy** [mrh0/createaddition#465]
**Describe the bug**
Straw recipe is missing

**To Reproduce**
Join game and try to craft straw.

**Additional context**
- Mod version: createaddition-fabric-1.19.2-20221218a
- Fabric version: 0.73.0+1.19.2
- Create version: create-fabric-0.5.0g-796+1.19.2

**Comment by FluffyBumblebees** [comment]
Added a placeholder recipe to fix this. 2 Bamboo placed diagonally for 3 straw.

**Comment by mrh0** [comment]
Fixed in 20230211a.
