### ISSUE TITLE
Unable to create liquid blaze burner on server

### ISSUE THREAD

**Issue by ItchyNitchy** [mrh0/createaddition#466]
**Describe the bug**
Liquid blaze burner converts back to regular blaze burner instantly.
Happens only on server. Singleplayer works fine.
**To Reproduce**
Setup fabric server with create and createAdditions mods.
Join game and try to use straw on blaze burner.

**Additional context**
- Mod version: createaddition-fabric-1.19.2-20221218a
- Fabric version: 0.73.0+1.19.2
- Create version: create-fabric-0.5.0g-796+1.19.2

**Comment by FluffyBumblebees** [comment]
just fixed it in my 1.19.2 PR.

**Comment by ItchyNitchy** [comment]
thx!
