### ISSUE TITLE
High Voltage Power Lines/Connectors

### ISSUE THREAD

**Issue by Peekofwar** [mrh0/createaddition#469]
I seem to have run into a throughput maximal with the gold wiring. Would be cool if there was a higher tier of cable that was thicker, and could carry more energy per tick. Some kind of high voltage wire. Perhaps you'd need a higher quality connector to use with it. 

Currently if I want more power throughput, I have to add additional power cables, though this would complicate things if I needed to wire up a bunch of power-hungry machines. 

I prefer the aesthetic of wires going from pole to pole along side a roadway rather than running rigid energy cables under the ground. It just looks cooler.

**Comment by Peekofwar** [comment]
Actually, I think it's mainly the connector that's the problem; the connector only seems to be capable of transferring about 256 fe/t to a machine.

**Comment by mrh0** [comment]
This was added a few updates ago (Large Connectors) closing
