### ISSUE TITLE
Error loading the mod

### ISSUE THREAD

**Issue by HannielGamer56** [mrh0/createaddition#470]
**Describe the bug**
When trying to open the game, it shows a message saying the mod failed to load correctly

**To Reproduce**
Steps to reproduce the behavior: I added this mod to the [Create Skyblock](https://www.curseforge.com/minecraft/modpacks/create-skyblock) modpack on curseforge, I don't know what could cause it, but the only fix I found was removing the mod entirely

**Additional context**
- Mod version: createaddition-1.16.5-20220129a
- Forge version: 36.2.2
- Create version: 0.3.2
- [latest.log](https://github.com/mrh0/createaddition/files/10562722/latest.log)
- [crash-2023-02-01_17.02.01-fml.txt](https://github.com/mrh0/createaddition/files/10562728/crash-2023-02-01_17.02.01-fml.txt)

**Comment by mrh0** [comment]
I no longer support 1.16 however do try older versions of the mod as i suspect it might be too new for the version of create you are running
