### ISSUE TITLE
[1.19.2 FABRIC Crash] on launch

### ISSUE THREAD

**Issue by itsdinkd** [mrh0/createaddition#474]
**Describe the bug**
Crashes when launching with latest version of Create that was released today, and Create additions.

**To Reproduce**
download both mods latest version

**Additional context**
- Mod version:
createaddition+1.19.2-1.19.2-20221218a.jar
- Fabric version: 1.19.2
- Create version: create-fabric-0.5.0.i-925+1.19.2.jar

**Comment by lukiono** [comment]
here is a actual crash log with your latest updated beta version, maybe it helps to pindown the issue.
used fabric version; 0.14.14

https://mclo.gs/SKSmgNt

**Comment by FluffyBumblebees** [comment]
I think the latest release has resolved this issue. Care to test it on your system to see if it works on your system as well?

**Comment by mrh0** [comment]
Fixed in 20230211a.
