### ISSUE TITLE
Cable Pulley Suggestion

### ISSUE THREAD

**Issue by idkwhyievenhavegithub** [mrh0/createaddition#476]
A thing similar to a rope pulley but is has a cable inside that can unwind and wind up.

I want to make a contraption that moves to different heights and can get power at any heights. I think a rope pulley type system could be a cool addition to the mod providing a way to have portable-ish power whilst still remaining in the create aesthetic.

It would require rotational power to wind and unwind like the rope pulley, but would also accept forge energy.

**Comment by memetmemet2009hotmailcom** [comment]
dam that would be very nice tbh
