### ISSUE TITLE
Redstone Contact (for ladder logic)

### ISSUE THREAD

**Issue by Pentasis** [mrh0/createaddition#48]
This is probably a long shot.
I'd like to see the addition of a redstone switch. This would pass a redstone signal (input > output) when it gets another redstone value at the side. (So basically like the redstone relay but for rs instead of fe).
Reason/Use: [Ladder logic.](https://en.wikipedia.org/wiki/Ladder_logic) The switch would act like the input contacts of the ladder.

More ideal would be if they would be wireless (like the redstone links), but non-wireless would fine.
The advantage would be that one could make highly complex control systems in a minecraft-y way. And since ladder logic is widely used in the industry it even serves an educational purpose. It would look something like this:

![2021-04-20_11 22 01](https://user-images.githubusercontent.com/7046024/115372595-5ca9d880-a1cb-11eb-9fd7-4795c64b041f.png)

Where the birch represents the redstone switch/contact. The top rung how it would look if they would be wireless, the bottom rung if they were not (left shows control on north side, right on top, which would save space between rungs).

**Comment by mrh0** [comment]
I'm Pretty sure you can do this with vanilla repeaters already (Locked Repeater).

**Comment by Pentasis** [comment]
No. Because that "locks" the signal. So eg if 2 repeaters in serial are locked, and the first unlocks, the second wont.
