### ISSUE TITLE
Current version of Create Addition crashes with create-fabric-0.5.0.i-921+1.18.2.jar

### ISSUE THREAD

**Issue by Fade-Alchemist** [mrh0/createaddition#482]
The current version of Create Addition crashes with create-fabric-0.5.0.i-921+1.18.2.jar

Steps to recreate - add both these mods in, create additions prevents game launch.

**Comment by MSandro** [comment]
I hope this will be fixed very soon.

**Comment by JoelZBub** [comment]
Duplicate of #474, #475 and #477

**Comment by FluffyBumblebees** [comment]
I think the latest release has resolved this issue. Care to test it on your system to see if it works on your system as well?

**Comment by mrh0** [comment]
Fixed in 20230211a.
