### ISSUE TITLE
[Bug] Issues with alternators and connectors

### ISSUE THREAD

**Issue by AmbroseSilverWolfe** [mrh0/createaddition#489]
The alternator setting went up to push 4.1k per alternator. But, even before that, the system seems to be having issues. No matter what I'm doing or how I set these up it won't push anything into the accumulator. Every time the server restarts, the alternators and connectors have to be replaced and re-wired to refined storage, alternators, and even then it's iffy..
It kind of seems like the connectors are pulling power from controllers of refined storage

It WAS working at one point, but then the alternator stopped pushing power (wires stopped pulling) or the accumulator stopped pulling (wires stopped pushing it inside)
The accumulator only has 2.2Mfe stored out of 188.8Mfe, but then I reconnect everything and it starts working until the next time I re-log
![IMG20230208062740_BURST000_COVER](https://user-images.githubusercontent.com/47878316/218299881-74ace74e-0d1f-436d-b2e7-199326d88b71.jpg)
![IMG20230208062959](https://user-images.githubusercontent.com/47878316/218299884-774779b0-f17b-4152-8d94-0e8a93a90dcc.jpg)
![IMG20230208063014](https://user-images.githubusercontent.com/47878316/218299887-0915880f-3efe-4aed-bdcc-707f7b00b994.jpg)
![IMG20230208062924](https://user-images.githubusercontent.com/47878316/218299888-4ee5b7d1-fe47-48bc-beed-5e308fc69677.jpg)
![IMG20230208062806](https://user-images.githubusercontent.com/47878316/218299889-d3636990-cc59-434f-beac-935cf3c58169.jpg)

**Comment by AmbroseSilverWolfe** [comment]
Some more info/images
I think the issue is in the connectors or wires...
![IMG20230216065050](https://user-images.githubusercontent.com/47878316/219441814-383c9fc2-c102-43c6-9a0a-6e36a6a751b4.jpg)
![IMG20230216065102](https://user-images.githubusercontent.com/47878316/219441822-2ae38fa2-36a9-41f6-bd0f-923347c5909b.jpg)
![IMG20230216065119](https://user-images.githubusercontent.com/47878316/219441830-728a52f4-f66b-4c1a-bfbc-d2cbf6503b9a.jpg)
![IMG20230216065201](https://user-images.githubusercontent.com/47878316/219441838-d817880a-1bf8-4ac0-8ef9-2cebc2faff85.jpg)
![IMG20230216065212](https://user-images.githubusercontent.com/47878316/219441841-049d0037-bf17-4621-b251-b5acdef59400.jpg)

**Comment by mrh0** [comment]
Fixed
