### ISSUE TITLE
Mechanical Polisher

### ISSUE THREAD

**Issue by Knalli65HD** [mrh0/createaddition#49]
If Sandpaper is attached to the belt on it: Items over it get polished which will use one durability point of sandpaper
Appearence:
Mechanical Belt is around 3 shafts in a Andesite casing slab or / block. the middle shaft will rotate the belt :D 
Additional features:
- If sandpaper is attached to the belt Entities who just standing on it get 1 damage per 4 secs at 32 RPM, at Max speed 256RPM = 8hp damage per 0,50 secs also damages the sandpaper
- Enitities gets moved to the direction (left or right),where it's spinning too
- Sandpaper can be stacked to 3
- Engineer's Goggles show Durability and usual information
- Ponderable which would be normal since It's a machine where Weighted Ejectors be only input Mechanical arms, Mechanical Belts input and output

**Comment by mrh0** [comment]
This suggestion is more suited for Create.
