### ISSUE TITLE
The SERIOUS ISSUES with this mod and its electricity.

### ISSUE THREAD

**Issue by RealDoesStuff** [mrh0/createaddition#490]
**Describe the bug**
Hello developer,

Power doesn't travel very far, which is an issue for large networks. In fact the whole system is just bugged beyond belief.

Here's some problems I found while playing,
Power doesn't travel beyond loaded/unloaded chunk borders, and power sometimes refuses to be extracted or put into blocks which as you know is vital and can break entire factories!

These are some SERIOUS ISSUES and should be fixed fairly soon as it makes the mod pointless other than the straw. (Best feature.)

Thanks.
-A very unhappy factory builder

**To Reproduce**
Just make a long power line and place the machine to be powered far enough away to avoid loading the power source chunks.

**Additional context**
- Mod version: 1.18.2-20230203a
- Forge version: 40.2.0
- Create version: 0.5.0.e
- Unhappy (Very)

**Comment by NHoltz02** [comment]
Also having this issue with power connectors moving power to/from source blocks and powered blocks. Playing on a server running the exact game version, forge version and create version. Running the mod on a server near spawn, and this is reproducible by unloading the chunks that the connectors are in.
![alternator](https://user-images.githubusercontent.com/60632267/221326645-ea030fa9-d891-480f-ae6b-37b85e5bf8e2.png)
