### ISSUE TITLE
Connectors with Mekanism create darkness

### ISSUE THREAD

**Issue by DankestO** [mrh0/createaddition#495]
**Describe the bug**
After upgrading to createaddition-forge-1.18.2-20230203a the connectors do strange things with the Mekanism blocks on dedicated server.

Once you place a connector to a mechanism block, close the server, and reopen it, the chunk that the connector is in will ignore all light sources and look all dark.

I've only noticed it on dedicated servers, in singleplayer this doesn't happen.

**To Reproduce**
It is only necessary to place a connector to a Mekanism block wired to another connector and restart the server. After that the magic will happen.

**Additional context**
- Mod version: createaddition-forge-1.18.2-20230203a (and above)
- Forge version: 40.2.0
- Create version: 1.18.2 v0.5.0i

**Comment by mrh0** [comment]
I had this same issue on my own private server and was not able to figure out what the issue was other than it had something to do with mechanism, good to know that its this combination, however I have no clue why this happens 🤷

**Comment by DankestO** [comment]
Oh no...
Well, maybe the Mekanism mod got confused with the connectors?
I'll see if someone else reported this on the Mekanism github to report it 🙋‍♂️
(btw, thank you for creating this nice mod~)
