### ISSUE TITLE
Unable to uninstall Create Additions

### ISSUE THREAD

**Issue by PlsHlp** [mrh0/createaddition#496]
**Cannot get rid of**
Whenever I uninstall the mod, it uninstalls the base Origins mod, and when I reinstall Origins, it reinstalls itself upon a mod list refresh, and does not show up in the files.

Cannot reproduce, it only happens to my pack.

- Mod version: 1.18.2
- Fabric version: 1.19.2
- Create version: None

**Comment by PlsHlp** [comment]
I deleted the modpack and started from scratch, and that seems to have fixed it, but I had to send it to a friend and have them uninstall the mod.

**Comment by PlsHlp** [comment]
Update: It has now installed itself into another pack. PLEASE HELP, IT HAS GAINED SENTIENCE.

**Comment by IceflowRE** [comment]
If you use a modpack contact the modpack creators? Has nothing to do with this mod.

**Comment by PlsHlp** [comment]
> If you use a modpack contact the modpack creators? Has nothing to do with this mod.

I am the modpack creator.

**Comment by PlsHlp** [comment]
> > If you use a modpack contact the modpack creators? Has nothing to do with this mod.
> 
> I am the modpack creator.

I created a modpack from scratch, and it installed itself into the pack, and I cannot remove it without removing the main part of the pack

**Comment by IceflowRE** [comment]
If you use a mod pack manager aka. a gui ignore it and check the files directly and delete the mod file. Sometime the mod manager lose the reference to the mod despite the file was not removed.
Otherwise, this mod cannot install itself if you did not instruct it. (if you didnt install another mod which depends on create additions). And Origins depents not on this mod.

**Comment by PlsHlp** [comment]
> If you use a mod pack manager aka. a gui ignore it and check the files directly and delete the mod file. Sometime the mod manager lose the reference to the mod despite the file was not removed. Otherwise, this mod cannot install itself if you did not instruct it. (if you didnt install another mod which depends on create additions). And Origins depents not on this mod.

I know it doesn't, which is why I am confused  why it keeps uninstalling the Origins mod when I remove Crafts and additions. Crafts and additions doesnt show up in the files, as I stated in the help request.

**Comment by PlsHlp** [comment]
@mrh0 This isn't an outside issue. I cannot remove only this mod, and it is only happening to me. I require assistance as this mod has no files, so I cannot remove it.

**Comment by PlsHlp** [comment]
Also, it is still happening so it should not be closed yet.

**Comment by mrh0** [comment]
there is no way this is an issue with this mod, it is definitely an mod manager/OS problem
