### ISSUE TITLE
Wire disconnection on contraption assembly

### ISSUE THREAD

**Issue by HowzitToyah** [mrh0/createaddition#499]
Connectors attached to contraptions disconnect when assembly is attempted. Even if both ends of the connections are on the contraption, even if the contraption doesn't actually assemble, they disconnect.

![image](https://user-images.githubusercontent.com/109080212/222289048-faa9c5d4-645f-42c5-927d-33c43a4dde94.png)
![image](https://user-images.githubusercontent.com/109080212/222289120-1233c816-6132-4630-8dac-62a5f3aacf67.png)

**To Reproduce**
> Take any contraption
> Put on connectors
> Attach wires
> Push it, spin it, pull it, whatever
> Sigh as you try to figure out how to get around this

**Additional context**
- Mod version: 1.18.2 - 20230221a
- Forge version: 1.18.2 - 40.2.0
- Create version: 1.18.2 - 0.5.0.i

I'm begging you, please fix this, I will legit pay money. I'm so close to having an autonomous chunk mining platform that isn't powered by a bunch of windmill abominations.

**Comment by mrh0** [comment]
Fixed
