### ISSUE TITLE
Zinc Sheet item clashes with Create Deco's Zinc Sheet.

### ISSUE THREAD

**Issue by spectrapulse** [mrh0/createaddition#500]
**Describe the bug**
Create Deco and Create Addition both implement their own Zinc Sheets but they are not intercompatible. In my instance when I use a Mechanical Press on a Zinc Ingot I end up with the Create Deco variation which I can't use to progress with Create Addition.

**To Reproduce**
- Install the latest versions of Create, Create Addition and Create Deco.
- Obtain a Zinc Ingot in-game. 
- Use a mechanical press to press it into a Zinc Sheet. (You will be given the Create Deco variant of the Zinc Sheet)
- Use the Zinc Sheet to craft a capacitor. You will be unable to craft a capacitor.

**Additional context**
- Minecraft version: 1.19.2
- Mod version: v20230211a
- Fabric version: 0.14.14
- Create version: v0.5.0.i-961
- Create Deco version: v1.2.13

**Comment by mrh0** [comment]
This is an issue with Create Deco as the recipe uses a zink tag, and I assume Create Decos zink plate isn't tagged

**Comment by Polarite** [comment]
crafts and additions use forge tag while deco is using the fabric tag, official fabric fork of create also uses fabric tags, so it would be nice if you could change it.

**Comment by Papaturts** [comment]
Having this very issue on the 1.20.1 version as well
unable to craft the Create additions plate or use it in its recipes
