### ISSUE TITLE
more IM(and others mod with cable) 

### ISSUE THREAD

**Issue by SKZGx** [mrh0/createaddition#503]
automatic energy output through pipes or wires.
Now it looks a little strange because you have to make a buffer before going to other pipes/cables
Something like in IM, add outputs to the modular battery, not to the connectors

Thank you for your work <3

**Comment by Robertdebrus** [comment]
To add to this, right now, the Accumulator multiblock accepts power from any source (Immersive Engineering Wires, Flux points, etc, but does not output to any source. Consistency could be improved by allowing the Accumulator to output along the same lines
