### ISSUE TITLE
Game breaking lighting errors occur whenever players enter the world near a chunk with a connector in it

### ISSUE THREAD

**Issue by dther** [mrh0/createaddition#504]
**Describe the bug**
I can confirm that with version forge-1.18.2-20230221a,
Issue #495 still occurs even without Mekanism installed.
The issue first appeared when only a connector on a 1-block-size accumulator was placed,
but has persisted even after building a bigger accumulator and attaching connectors to other devices.
This appears to only occur on dedicated servers.

Sometimes, when a player joins the server,
chunks containing Connectors will suddenly have all of their lighting disappear.
This occurs on the light level cache layer, meaning that not only do mobs begin to spawn in the now pitch-black area,
but that undoing the change without restarting the server requires manually placing lighting all the way to the top of the build height.

The chunk's lighting can be temporarily fixed by restarting the server with the arguments `--forceUpgrade --eraseCache`, which forces a recalculation of light levels.
However, the chunk lighting error seems to reappear when one of the following occurs:

 - a player joins near the area
 - a player exits a nether portal near the area
 - a player loads the chunk in after moving far away (not too sure about this one)

Needless to say, my tower turning into a dungeon packed with mobs every few hours has caused a lot of deaths for everyone in the area.
This is a game-breaking bug for my modpack server.

I'm currently looking for workarounds to fix the lighting errors without restarting by using /fill, so any help there is appreciated.
Please reach out if I can help with debugging this in any way. CCA is a key part of my modpack since it's the only way to generate FE, and it feels terrible to have to restart the server again because my base has gone pitch black for the tenth time today ;-;

**To Reproduce**

On a dedicated minecraft server,
 1. Place a connector somewhere.
 2. Disconnect and reconnect. (This may need to be repeated multiple times)
 3. Observe sudden darkness in the affected chunk.

**Additional context**
Bug occurs both with and without Radon, a lighting engine rework.
- Mod version: forge-1.18.2-202302221a
- Forge version: 40.2.0
- Create version: 0.5.0.i

**Comment by mrh0** [comment]
Fixed in 20230309a.
