### ISSUE TITLE
Wires changes

### ISSUE THREAD

**Issue by T3sT3ro** [mrh0/createaddition#51]
Currently wire is always rendered as a 2 or 3 pixel arc. It is very hard to see up close and needlessly thick if looking from farther away. Please, consider making it a solid model or something similar to vanilla lead instead.

The messages appearing above the quickbar should be replaced with either rendered, colored lead, that shows it's preview in blue if aiming at non-connectible blocks or in the air, green if it can be connected to aimed block and red if it can't be connected (node limit reached, too far away, wrong connector).

Another way instead of rendering something like a lead in arc would be to draw create's wireframe box around target block, or use the particle system to draw a blue/green/red line to player/targeted block.

There is something pretty annoying with connecting many things together into serial connection - right now when you want to connect `A-B-C-D` you have to click A,B, then B,C, then C,D. Instead we could enter "connection mode" (if you ever played factorio then you should know what I mean) - basically you continue connecting the wire from last clicked connector. in above case I would have to simply click in A, B, C and D. To finish after D we could click anywhere else when connection can't be made or shift-right-click.

**Comment by mrh0** [comment]
Yes, when I initially coded the renderer I tried to use the lead renderer but was unable to get it working, I might try again sometime. 
The plan is to get the wire rendering from the block you are connecting, to your hand when connecting.
the connection mode is a good idea.

**Comment by T3sT3ro** [comment]
Maybe this could prove useful for wire renderer:
https://github.com/lilypuree/ConnectibleChains/blob/1.16.x/src/main/java/com/lilypuree/connectiblechains/client/render/entity/ChainKnotEntityRenderer.java

*source: ConnectibleChains mod*

I didn't test it, only seen the presentation on YT, but from what I saw that's basically how it should look.

**Comment by mrh0** [comment]
Added/fixed most of this in 20210625a
