### ISSUE TITLE
Rolling Mill does not interact correctly with Hoppers

### ISSUE THREAD

**Issue by IdrisQe** [mrh0/createaddition#510]
**Describe the bug**
Hoppers will extract items input into the Rolling Mill immediately, before they get processed, and the Mill will still show particles as if it was processing.

This is inconsistent with similar Create machines like the Millstone, which will only output processed items into hoppers.

**To Reproduce**
Place a Rolling Mill, with power, with a Hopper underneath, and throw items into the top.

**Additional context**
- Mod version: 1.18.2-20221218a
- Fabric version: 1.18.2-0.14.12
- Create version: 1.18.2-0.5.0g-792

**Comment by dirtbaghippy** [comment]
Same for me including with andesite funnels.
Mod version: 1.19.2-20230211a
Fabric version: 1.19.2-0.14.13
Create version: 1.19.2-0.5.0.i-961
