### ISSUE TITLE
dark chunks 

### ISSUE THREAD

**Issue by vupleslagopus** [mrh0/createaddition#514]
I am not certain about what exactly is causing this bug but when you place a modular accumulator with a connector on it, close the world and then join back in, the entire chunk will go completely dark even during the day. My suspicion is that it has something to do with the performance mods in the mod pack that I'm using as when I create a new instance with create mod and create addition this doesn't happen.

1: Get the mod pack Create Flavored 5.10 and add create addition to the mods.
2: Create a new world and place a modular accumulator with a connector on it.
3: Save and close the world.
4: Open the world.

- Mod version: 20230202b
- Forge version: 43.2.0
- Create version: 0.5.0.i

![2023-03-12_21 29 11](https://user-images.githubusercontent.com/108636606/224609351-52f56b30-4103-457d-8e84-8cafc38c3a3c.png)
![2023-03-12_21 31 54](https://user-images.githubusercontent.com/108636606/224609371-53356a65-7ad9-4f51-91ae-bfe40c2bcbf5.png)

![2023-03-11_21 11 27](https://user-images.githubusercontent.com/108636606/224526194-1a181474-b9b1-4f06-9640-a11918de05ad.png)
![2023-03-11_21 33 19](https://user-images.githubusercontent.com/108636606/224526484-441f27f4-fd31-4996-864a-f2b3b6494908.png)

**Comment by mrh0** [comment]
Fixed
