### ISSUE TITLE
Seed oil breaks recipes

### ISSUE THREAD

**Issue by KostromDan** [mrh0/createaddition#517]
Pleace add option in config to prevent mod adding water tag to seed oil, it breaks and makes unlogical many mod recipe.
![image](https://user-images.githubusercontent.com/90044015/224989359-f4958b7a-bcd6-46db-a5b4-6ab4890a173d.png)
Seed oil in fission reactor turns into water steam? Seriously?

**Comment by Uraxys** [comment]
This can be fixed by using datapacks. 
Create a new datapack and make a file called `water.json` inside `data/minecraft/tags/fluids/`, then paste the following into the json file:
```json
{
  "replace": true,
  "values": [
    "minecraft:water",
    "minecraft:flowing_water"
  ]
}
```
This removes any mod fluids from the water tag.

**Comment by KostromDan** [comment]
Thanks, if someone else needed:
[M-Tech-custom-fixes-v-0-0-1.zip](https://github.com/mrh0/createaddition/files/11131172/M-Tech-custom-fixes-v-0-0-1.zip)
