### ISSUE TITLE
Looking at a placed Connector with F3 crashes the game

### ISSUE THREAD

**Issue by Filostorm** [mrh0/createaddition#519]
**To Reproduce**
Place a Connector
Enable F3 
Look at said Connector 

**Additional context**
- Mod version: createaddition-1.18.2-20230312a.jar and also tested with createaddition-1.18.2-20230309a.jar
- Forge version: 40.2.1
- Create version: create-1.18.2-0.5.0.i.jar

[crash-2023-03-14_16.42.28-client.txt](https://github.com/mrh0/createaddition/files/10973556/crash-2023-03-14_16.42.28-client.txt)
[latest.log](https://github.com/mrh0/createaddition/files/10973558/latest.log)

**Comment by Filostorm** [comment]
Confirmed to work fine on createaddition-1.18.2-20230221a.jar

**Comment by mrh0** [comment]
Fixed in 20230315a
