### ISSUE TITLE
Server crash on startup - " Mod loading error has occurred"

### ISSUE THREAD

**Issue by ClaudiusMinimus** [mrh0/createaddition#522]
**Describe the bug**
The server crashes while starting

**Additional context**
- Mod version: 1.18.2-20230312a
- Forge version: 40.2.1
- Create version: 0.5.0.i
- Java 17.0.5
- Linux (amd64) version 5.4.0-144-generic
Crash Report [Formated](https://crashy.net/b37b157d-f20f-449e-a722-fa54ee959a36)
or download
[crash-2023-03-14_19.59.53-fml.txt](https://github.com/mrh0/createaddition/files/10975261/crash-2023-03-14_19.59.53-fml.txt)

This is a client beta - the server files were too big to upload. If you install and then remove the client mods, and `creatania-1.18.2-0.3.17-beta.jar` you should be able to replicate if needed.
[Create Conquest Arcane-1.12.0.zip](https://github.com/mrh0/createaddition/files/10975309/Create.Conquest.Arcane-1.12.0.zip)

**Comment by mrh0** [comment]
Fixed in 20230315b.

**Comment by ClaudiusMinimus** [comment]
Thanks! Your update fixed the issue!
