### ISSUE TITLE
Search in REI does not work

### ISSUE THREAD

**Issue by Xomka2280** [mrh0/createaddition#527]
**Describe the bug**
On the latest version of Create Crafts & Additions (Fabric 1.18.2) and in the Russian language of the game, the search in REI stops working. If you install the old version (20221128a), then everything works fine.

**To Reproduce**
Install the latest version of Create Crafts & Additions, REI and set the language in the game to Russian. Try using the REI search.

**Additional context**
- Mod version: 1.18.2-20230211a
- Fabric version: 1.18.2
- Create version: 0.5.0g-792+1.18.2

**Comment by MAGGen-hub** [comment]
Same on 1.19.2... Not only REI... Same problem with JEI and standart creative search bar.

**Comment by madcaker** [comment]
Can confirm that both REI JEI and EMI are not showing the crafting recipes for several (but not all) items. Notably the alternator and generator.

It doesn't seem that the ingame language has anything to do with it.
