### ISSUE TITLE
Crash on Forge when you are on the inventory

### ISSUE THREAD

**Issue by Samu9000** [mrh0/createaddition#534]
Describe the bug:
When I move objects or simply move the cursor in the inventory, for example towards the jei, the game crashes.

To Reproduce
Move the cursor on the inventory.

Additional context
- Mod version: v20230404a
- Forge version: 43.2.8
- Create version: 0.5.0.i

**Comment by mrh0** [comment]
Please provide a crash log

**Comment by Samu9000** [comment]
[crash-2023-04-06_11.02.57-client.txt](https://github.com/mrh0/createaddition/files/11185017/crash-2023-04-06_11.02.57-client.txt)

**Comment by mrh0** [comment]
Not able to reproduce this issue, please make sure you are on the latest versions of cc&a create and flywheel
