### ISSUE TITLE
Very easy infinite power

### ISSUE THREAD

**Issue by Vikthos** [mrh0/createaddition#535]
Its possible to very easily get infinite power using the relay, no need for a source.

How to reproduce
-Get 3 relays next to eachother
-Connect them in a linear fashion with the copper spools and power them with redstone 
-take power by connecting the pull from the 2nd relay to for example your motor or accumilator
-boom infinite power from 3 relays

- Mod version: createaddition-1.19.2-20230404a.jar
- Forge version: 43.2.0-1.19.2
- Create version: create-1.19.2-0.5.0.i.jar

**Comment by mrh0** [comment]
Fixed in 20230411a.
