### ISSUE TITLE
Redstone Relays generating power

### ISSUE THREAD

**Issue by Ocawesome101** [mrh0/createaddition#537]
**Describe the bug**
When given a redstone signal, Redstone Relays emit seemingly limitless amounts of FE regardless of what is connected to their input.

**To Reproduce**
1. Place a Redstone Relay and an Electric Motor
2. Connect the Relay's output terminal to the Motor with a wire
3. Power the Redstone Relay
4. Observe bug

**Additional context**
- Mod version: 1.18.2-20230404a
- Forge version: 40.2.0
- Create version: 0.5.0.i

**Comment by mrh0** [comment]
Fixed in 20230411a.
