### ISSUE TITLE
[POSSIBLE BUG] Have Blaze Burners fitted with straws still be valid targets for mechanical arms

### ISSUE THREAD

**Issue by J0hN555** [mrh0/createaddition#547]
It's self explanatory, i think that the option to have blaze burners be fed from mechanical arms shouldn't be removed when it's fitted with a straw.

**Comment by w-man12** [comment]
i also have this as an issue and i am in agreement it must be changed/fixed and is actually more of an issue as it is difficult to use liquid fuel on a large scale to start up a factory

**Comment by MikeyM3thodic4l** [comment]
They also appear to lose the ability to have an encased fan blow vertially through them as well once they are upgraded, not sure if the fix for these would be related to each other or not.

**Comment by mrh0** [comment]
fixed in v1.2.0.
