### ISSUE TITLE
SU not updating on the Network

### ISSUE THREAD

**Issue by tom-shelby** [mrh0/createaddition#548]
**Describe the bug**
Stress Usage not updating

**To Reproduce**

- Place a Kinetic source (creative motor for example), then a stressometer. If you put and remove an Alternator, SU wouldn't be updated on stressometer.

**Additional context**
- Mod version: createaddition-1.19.2-20230411
- Forge version: 43.2.8
- Create version: 0.5.0.i

**Comment by mrh0** [comment]
Fixed in 20230426a.
