### ISSUE TITLE
Add built-in connector to induction heater, alternator, electric motor and changing station

### ISSUE THREAD

**Issue by T3sT3ro** [mrh0/createaddition#55]
Make it so that wire can be directly connected to those elements without an extra connector. Basically do the same thing that accumulator has.

**Comment by mrh0** [comment]
No, I want the connectors to be optional, and not make it feel like electric blocks require my energy system. The accumulator can have them because most mods that add energy transport also add storage and thus wouldn't need the Accumulator.
