### ISSUE TITLE
Kubejs/crafttweaker support

### ISSUE THREAD

**Issue by Theskullking15** [mrh0/createaddition#550]
In some way, I would like to be able to use the tesla coil in my own recipe sequences. Doesn't really matter how.

**Comment by Drackion** [comment]
with kubejs you can use event.custom to add the recipes to the tesla coil, here is an example:

```javascript
event.custom(
          {
            "type":"createaddition:charging",
            "input": {
                  "item": "ae2:certus_quartz_crystal",
                "count": 1
            },
            "result": {
                "item": "ae2:charged_certus_quartz_crystal",
                "count": 1
            },
            "energy": 1000
           })

**Comment by Theskullking15** [comment]
Oh, sorry at the time of me requesting this I thought that it was called a recipe sequence cause that's what jei refers to it as but looking at the code its actually called sequenced assembly. This is what I was meaning and what I was trying to do was something like this 

e.custom({
    "type": "create:sequenced_assembly",
    "ingredient": {
      "item": "ae2:certus_quartz_crystal"
    },
    "loops": 5,
    "results": [
      {
        "chance": 100.0,
        "item": "ae2:flawless_budding_quartz"
      }
    ],
    "sequence": [
      {
        "type": "create:deploying",
        "ingredients": [
          {
            "item": "create:incomplete_precision_mechanism"
          },
          {
            "item": "ae:charged_certus_quartz_crystal"
          }
        ],
        "results": [
          {
            "item": "create:incomplete_precision_mechanism"
          }
        ]
      },
      {
        "type": "createaddition:charging",
        "ingredients": [
          {
            "item": "create:incomplete_precision_mechanism"
          },
        ],
        "results": [
          {
            "item": "create:incomplete_precision_mechanism"
          }
        ],
        "energy": 20000
      }
    ],
    "transitionalItem": {
      "item": "create:incomplete_precision_mechanism"
    }
  })

**Comment by EvanHsieh0415** [comment]
```js
ServerEvents.recipes(event => {
  let { createaddition } = event.recipes

  createaddition.rolling(Output, Input)

  createaddition.charging(Output, Input)
    .energy(Number)
})
```

**Comment by Theskullking15** [comment]
That didn't work but I'll ask on the kubejs discord to see what they might be able to help with.

**Comment by EvanHsieh0415** [comment]
> That didn't work but I'll ask on the kubejs discord to see what they might be able to help with.

@Theskullking15 My intention is to provide this format to the official team as a reference for supporting KubeJS.
