### ISSUE TITLE
Some items missing from biomass tags

### ISSUE THREAD

**Issue by saltyseadoggo** [mrh0/createaddition#555]
**Describe the bug**
One plant food is missing from `#createaddition:plant_foods` and cannot be used to make biomass:
- Chorus Fruit
Several plants are missing from `#createaddition:plants` and cannot be used to make biomass:
- Dead Bush
- Sea Pickle
- Moss Block
- Moss Carpet
- Big Dripleaf
- Small Dripleaf
- Glow Lichen

**To Reproduce**
Observe the files for these tags under `data/createaddition/tags/items.

**Additional context**
- Mod version: 1.19.2-20230426a
- Forge version: 43.2.8
- Create version: 0.5.0i

**Comment by mrh0** [comment]
fixed in 20230507a.
