### ISSUE TITLE
Game crashed upon hovering bioethanol_bucket or seed_oil_bucket and using Russian language

### ISSUE THREAD

**Issue by xlifi** [mrh0/createaddition#557]
**Describe the bug**
bioethanol_bucket and seed_oil_bucket both fail to create a tooltip. Upon hovering on any of those item, game crashes.

**To Reproduce**
Launch the game, select Russian language, open creative menu and hover over bioethanol_bucket or seed_oil_bucket

**Additional context**
- Mod version: 20230211a
- Fabric version: 0.14.19
- Create version: 0.5.0.i-1003-1.19.2
- Logs: https://mclo.gs/yvAD8Ny

**Comment by xlifi** [comment]
Is there an ETA for the next update?

**Comment by mrh0** [comment]
Should have been fixed in 20230723a. Have not verified it though

**Comment by xllifi** [comment]
Working
