### ISSUE TITLE
Crash (on client) crafting a connector

### ISSUE THREAD

**Issue by SrRapero720** [mrh0/createaddition#563]
**Describe the bug**
I was playing a survival game (server hosted and client)
I try to craft a pair of connectors but game crash when i tried to picked up (end crafting)
only crash on client, server is safe (caused by rendering)

**To Reproduce**
- Put all required items on crafting table
- Press shift + click to items
- CRASH!!

(after restart i can't reproduce it again, so here is another steps, maybe i press CTRL at the same time by accident)
- Put all required items on crafting table
- Press CTRL + SHIFT + Click to items
- CRASH!!

**Additional context**
- Mod version: createaddition-1.18.2-20230507a.jar
- Forge version: 40.2.0
- Create version: create-1.18.2-0.5.0.i.jar

**Gist**
Crash-Report & Logs file: https://gist.github.com/SrRapero720/fea888f1b25b4f6036441f1afe6b1cde

**Comment by skippyall** [comment]
This might be caused by Fastbench. Does it occur without it?
