### ISSUE TITLE
Crashing on newest create version 1.18.2

### ISSUE THREAD

**Issue by IkariDevGIT** [mrh0/createaddition#566]
**Describe the bug**
when using this mod on the newest create version(0.5.1a 1.18.2) the game crashes

**To Reproduce**
1. download this mod(newest version)
2. download create mod(0.5.1a)
3. start minecraft

**Additional context**
- Mod version: 1.18.2-20230507a
- Forge version: 40.2.4
- Create version: 0.5.1a

Error in short:
java.lang.ClassNotFoundException: com.simibubi.create.foundation.block.BlockStressValues$IStressValueProvider
Full error:
https://pastebin.com/9YmvqMPe

could be related:
![grafik](https://github.com/mrh0/createaddition/assets/90197782/85683f41-5dc4-42d8-af2e-469c8ffdb1f3)

**Comment by mrh0** [comment]
Resolved in 20230524a.

**Comment by FishyBusinessYT** [comment]
I'm having this exact issue right now. Please tell me if you need any info, but the full mod list is this:
[Modlist.txt](https://github.com/mrh0/createaddition/files/11604405/Saturn.txt)
