### ISSUE TITLE
1.19.2 Create Crafts & Additions Not Compatible with Create .5.1.a Update

### ISSUE THREAD

**Issue by ClaudiusMinimus** [mrh0/createaddition#567]
Ceate Crafts & Additions `createaddition-1.19.2-20230507a.jar` is incompatible with the new Create .5.1.a update.
![image](https://github.com/mrh0/createaddition/assets/17887664/f24fedb0-834a-4e9d-83a4-a1753df96a1d)

**Comment by mrh0** [comment]
Resolved in 20230524a.
