### ISSUE TITLE
Accumulator changes

### ISSUE THREAD

**Issue by T3sT3ro** [mrh0/createaddition#57]
Make accumulator a passive network element with only one connector (two connectors logic is too cumbersome).

- When there is more energy than needed in the network - accumulator is charging
- When there is not enough energy in the network, the accumulator should discharge stored energy.
- When accumulator is powered by redstone signal it should not discharge (but it should always charge)
- Charging/discharging accumulator should produce some particles or change texture to give some info about what's happening.
- Integrate showing accumulator capacity and stored energy into engineering goggles as KFET - Kilo-FE-Tick as an analogy to KWH. Also show in the tooltip accumulators charge and discharge rate.
- Be able to pickup charged accumulator
- Be able to read with comparator `energy stored / capacity ` of accumulator

**Comment by mrh0** [comment]
1-2 is not currently possible, I'm planning to rework the energy system which could enable this.
3 could be done
4-5 would require additional networking syncing with the client. If I figure out a performant way to do this I will.
6-7 are already features

**Comment by mrh0** [comment]
1-2 is hard to implement and get working of blocks from other mods.
3 Use a Redstone Relay.
4 Maybe in  the future
5 was added in 20210625a.
