### ISSUE TITLE
Rolling Mill shafts are animated improperly

### ISSUE THREAD

**Issue by JuniKnytt** [mrh0/createaddition#571]
**Describe the bug**
Roller shafts are misaligned and spin on the wrong axis.
![image](https://github.com/mrh0/createaddition/assets/42306249/5d52add0-0e23-471a-8181-db6b932c86e7)

**To Reproduce**
Have the shafts of the roller line up with the Z-axis

**Additional context**
- Mod version: createaddition-forge-1.19.2-20230524a 
- Forge version: 43.2.11
- Create version: 1.19.2-0.5.1b

**Comment by mrh0** [comment]
Fixed in 20230527a.
