### ISSUE TITLE
CC&A and Emendatus 

### ISSUE THREAD

**Issue by FooterManDev** [mrh0/createaddition#575]
**Describe the bug**
When using CC&A with Emendatus Enigmatica, it causes Emendatus to throw a registry error and fail to start the game.

**To Reproduce**
Unfortunately I was unable to reproduce this with only CC&A, Create and Emendatus alone. I found this bug while working on my pack [Fun in the Sky](https://github.com/TheGangModpacks/Fun-in-the-Sky), so it could be anything really. I'll still give you instructions for reproducing with the pack:

After installing, enable customization (Depending on the launcher).
Update CC&A to any versions above 20230507a.
Attempt to load the game. You should get an EE Registry crash.

**Additional context**
- Mod version: 20230524a plus future versions. The previous version (20230507a) works fine. (What is this version naming😄)
- Forge version: 43.2.8
- Create version: 0.5.0.i
- EE version: 2.1.5
- Logs: [Crash](https://gist.github.com/FooterMan15/991ca0e6d34fff1e647f444bda9bc50f), [Latest](https://gist.github.com/FooterMan15/ca3b295860cc2f8ff29495f9345729ce)

I apologize if this is not your mod's fault, but I don't really have anywhere to go. It's clear that something is conflicting with CC&A and EE, but I'm not sure what.

**Comment by mrh0** [comment]
20230507a is the last version to support Create 0.5.0
20230524a onward requires Create 0.5.1
the versioning scheme is just the release date 2023-05-24-(a-z)
