### ISSUE TITLE
Stress Generator.

### ISSUE THREAD

**Issue by ironfprcefeild** [mrh0/createaddition#58]
compared to other mods the power generated from this mod is just unusable, my suggestion is for an item enabled in the config, this item goes in front of a alternator to build a energy converter based off available stress, ex: ALT*Su/4=Fe. where alt is energy output of the alternator and su is the stress capacity of the system its connected too, you could edit the amount of su its allowed to consume by scrolling on the back, if you go to the very top it gets set to max using all stress in the system allowing no more parts to be attached. the energy output of this would send the other energy items in this mod over capacity so it would most likely only be used with other modded items, like the mekanism mod, so it would have to be disabled by default.

**Comment by mrh0** [comment]
You can already change the energy conversion rate in the configs and you have to keep in mind that increasing the output of the alternator will affect the cost of running the Electric Motor (as to not break the laws of thermodynamics).
