### ISSUE TITLE
Blazing, Gilded Quartz, Brass, Zinc, and Copper Pickaxes are not using the forge:tools/pickaxes tag for 1.19.2 plus

### ISSUE THREAD

**Issue by ModernGamingWorld** [mrh0/createaddition#582]
Currently your pickaxes are missing the forge tag for pickaxes

**Comment by mrh0** [comment]
Wrong mod, The mod you are referring to is Create stuff & Additions (i think) this is for Create Crafts & Additions. 
This is a common misstake.
