### ISSUE TITLE
Changing max wire length in the config does nothing 

### ISSUE THREAD

**Issue by AzureFist** [mrh0/createaddition#585]
**Describe the bug**
Adjusting the max wire length in the configuration of the mod does not actually allow the wire to be longer, resulting in a "wire is too long" message. 

**To Reproduce**
1. Open a world
2. Pause the game and access Create's config menu 
3. Access the config files for other mods and select createaddition 
4. Click on the wire tab and adjust max wire length to a number >12 
5. Save changes to config 
6. Unpause and attempt to connect 2 connectors together at the new specified distance 
This should result in an error message at the top of the hotbar that says "wire is too long" even though the distance was adjusted. 

**Additional context**
- Mod version: CreateAddition 1.19.2 20230524
- Forge version: 1.19.2 forge 43.2.14 
- Create version: Create 1.19.2 0.5.1b

**Comment by mrh0** [comment]
currently, you need to restart the game, but it will be fixed in the next update
