### ISSUE TITLE
Dependency client crash in 1.18.2 due to fabric create updating to 0.5.1b-patch-1

### ISSUE THREAD

**Issue by netcore10** [mrh0/createaddition#586]
**Describe the bug**
Dependency error in the 1.18 version
**To Reproduce**
https://paste.atlauncher.com/view/77512231-373d-4485-8c9c-b1daf1812404

**Additional context**
- Mod version: 1.18.2 
- Fabric version: 1.18.2
- Create version: 0.5.1b-patch-1

**Comment by MCAlexisYT** [comment]
Same thing happens for me on 1.19.2

**Comment by mrh0** [comment]
create 0.5.1 on 1.18 is now supported update to the latest version of CC&A, 1.19 is on its way
