### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'!

### ISSUE THREAD

**Issue by Jiriki79** [mrh0/createaddition#587]
**Describe the bug**
[crash-2023-06-23_20.11.22-client.txt](https://github.com/mrh0/createaddition/files/11854105/crash-2023-06-23_20.11.22-client.txt)

**To Reproduce**

**Additional context**
- Mod version: createaddition-fabric+1.19.2-20230508b.jar
- Fabric version: 0.14.21
- Create version: create-fabric-0.5.1-b-build.1079+mc1.19.2.jar

**Comment by thekrugers** [comment]
I'm getting this with create-fabric-0.5.1-b-build.1075+mc1.19.2.jar as well as create-fabric-0.5.1-b-build.1079+mc1.19.2.jar

**Comment by TheInfamousAlk** [comment]
I am also getting this, same setup as the comment above. create-fabric-0.5.1-b-build.1075+mc1.19.2.jar as well as create-fabric-0.5.1-b-build.1079+mc1.19.2.jar

**Comment by mrh0** [comment]
create 0.5.1 is not yet supported

**Comment by thekrugers** [comment]
Please correct the dependency info on Modrinth, as the createaddition-fabric-1.19.2-20230508b.jar version of CC&M shows "Create Fabric
Version 0.5.1-b-build.1079+mc1.19.2 is required"

**Comment by mrh0** [comment]
Update to the latest version 20230723a.
