### ISSUE TITLE
Game cannot load due to error with IWrenchable

### ISSUE THREAD

**Issue by cybercat5555** [mrh0/createaddition#589]
**Describe the bug**
The game is unable to launch with the current build createaddition-fabric+1.19.2-20230508b with the newest update of create-fabric-0.5.1-b-build.1079+mc1.19.2. Seems to be similar but different from https://github.com/mrh0/createaddition/issues/587

**To Reproduce**
- Add create-fabric-0.5.1-b-build.1079+mc1.19.2
- Add createaddition-fabric+1.19.2-20230508b
- Try to launch the game
- It crashes

**Additional context**
- Mod version: createaddition-fabric+1.19.2-20230508b
- Fabric version: 0.14.21
- Create version: create-fabric-0.5.1-b-build.1079+mc1.19.2

**Comment by Canz2** [comment]
I'm getting this error too
Create change a lot of class name in their newest update
so CreateAddition needs an update to work with it

**Comment by Gentleman-Ghost** [comment]
Also getting this issue with the latest version of Additions on Fabric.

**Comment by sh0tybumbati** [comment]
this seems to not be an issue on 1.18 since that version of the fabric edition of the mod was updated last week-
but 1.19 version of the mod hasn't been yet.
If the 1.19 version got a parity update to the 1.18's current version i think this bug would be resolved

**Comment by mrh0** [comment]
Update to the latest version 20230723a.
