### ISSUE TITLE
Furnace burner consumes bucket when fueled with lava bucket

### ISSUE THREAD

**Issue by T3sT3ro** [mrh0/createaddition#59]
When clicked with lava bucket, furnace burner consumes the bucket. When destroyed, the bucket is dropped back.

**Additional context**
- Mod version: `createaddition-1.16.5-20210422a.jar`
- Forge version: `36.1.4`
- Create version: `0.3.1c`

**Comment by mrh0** [comment]
think you can use a hopper to get it back

**Comment by T3sT3ro** [comment]
That's... not a reason to close the issue. It still is a bug even with this workaround/hack.
The issue should stay open until:
- labeled as WON'T FIX
- labeled as WAI - WORKS AS INTENDED
- solved by commit

Otherwise it's like in this joke:
> A patient arrives at doctor's clinic
> \- Doctor, it hurts when I do that - says while rising his leg.
> \- Then don't do that
