### ISSUE TITLE
Description: Mod loading error has occurred

### ISSUE THREAD

**Issue by JvGame** [mrh0/createaddition#590]
**Describe the bug**
I was trying to update the kubejs create addon mods and until then everything was normal, before with these same mods the server was opening and running but after trying to install the new version and uninstalling and installing new versions of the mod the error started to crash server failed to load this mod.

**To Reproduce**
[2023-06-24-9.log.gz](https://github.com/mrh0/createaddition/files/11858312/2023-06-24-9.log.gz) The log
[crash-2023-06-24_19.09.25-fml.txt](https://github.com/mrh0/createaddition/files/11858314/crash-2023-06-24_19.09.25-fml.txt) The crash report

**Additional context**
- Mod version: 1.18.2-20221219a
- Forge version: 40.2.8
- Create version: v0.5.0c

**Comment by mrh0** [comment]
The version you are using is very old, please consider updating CC&A and Create
