### ISSUE TITLE
crashes with create-fabric-0.5.1-b-build.1078+mc1.18.2

### ISSUE THREAD

**Issue by Fade-Alchemist** [mrh0/createaddition#598]
**Describe the bug**
crashes with create-fabric-0.5.1-b-build.1078+mc1.18.2 on start up.

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'!

Exit Code: -1

**To Reproduce**
Install version createaddition-fabric+1.18.2-20230508b with create-fabric-0.5.1-b-build.1078+mc1.18.2 

**Additional context**
- Mod version: see above
- Fabric version: 0.14.21
- Create version: see above

[crash-2023-07-01_16.39.38-client.txt](https://github.com/mrh0/createaddition/files/11927201/crash-2023-07-01_16.39.38-client.txt)

**Comment by dragonshardz** [comment]
The Fabric port for 0.5.1 isn't done yet. Community members are working on it.

**Comment by NolanHewitt** [comment]
Praying for a fabric 1.19 create 0.5.1 version (;﹏;)

**Comment by mrh0** [comment]
CC&A for Create fabric 0.5.1 for Minecraft 1.18 is out now, please update to the latest version

**Comment by NolanHewitt** [comment]
*Sad 1.19.2 noises*
