### ISSUE TITLE
Induction heater doesn't power burner furnace with furnace engine mounted to it

### ISSUE THREAD

**Issue by T3sT3ro** [mrh0/createaddition#60]
Induction Heater doesn't heat the furnace burner that has a Create's furnace engine mounted on it even when the settings in mod config are set up:
```
#Heater
[heater]
	#Enable Induction Heater when attached to a Furnace Engine.
	heater_furnace_engine_enable = true
```

**To Reproduce**
1. Edit config as above
2. Place furnace burner
3. Attach induction heater to furnace burner and power the heater - it should work now
4. mount the Create's engine and flywheel to the furnace - it will work for a second or so and then the furnace burner shuts down.

**Additional context**
- Mod version: `createaddition-1.16.5-20210422a.jar`
- Forge version: `36.1.4`
- Create version: `0.3.1c`

**Comment by mrh0** [comment]
When heater_furnace_engine_enable is set to true it will consume much more power (according to another config option) and usually, you won't be able to provide enough power.

**Comment by T3sT3ro** [comment]
@mrh0 I linked it directly to creative generator so I assumed it should work.
