### ISSUE TITLE
Crash at startup with newest upload

### ISSUE THREAD

**Issue by Rosenblack** [mrh0/createaddition#601]
**Describe the bug**
Crash at startup

**To Reproduce**
no mods other than fabric api, create and additions

**Additional context**
- Mod version: 20230508b
- Fabric version: 0.76.0
- Create version: 0.5.1b patch 2

log if needed
https://mclo.gs/t7BHmi4

**Comment by mrh0** [comment]
Create fabric 0.5.1 for 1.19 is not yet supported

**Comment by itsdinkd** [comment]
time frame on when it will be?

**Comment by dragonshardz** [comment]
per #321, when the community ports it and mrh0 approves the pull request.

**Comment by mrh0** [comment]
Update to the latest version 20230723a.
