### ISSUE TITLE
Using a lava bucket on the furnace burner doesn't give you an empty bucket

### ISSUE THREAD

**Issue by L0pz** [mrh0/createaddition#605]
**Describe the bug**
Right-clicking the furnace burner with a lava bucket consumes the entire item instead of giving you an empty bucket

**To Reproduce**
Equip a bucket of lava and right-click on a furnace burner

**Additional context**
- Mod version: 1.16.5-20220129a 
- Forge version: 36.2.39
- Create version: v0.3.2g

**Comment by mrh0** [comment]
This version of the mod is no longer supported
