### ISSUE TITLE
Create Crafts and Additions Crashing on startup

### ISSUE THREAD

**Issue by origin-n** [mrh0/createaddition#606]
**Describe the bug**
When starting the game, it crashed due to this mod.

**To Reproduce**
Start the game

**Additional context**
Using modrinth launcher

- Mod version: All 1.19.2 Versions, crash report using fabric-1.19.2-20230508b
- Fabric version: 0.14.21
- Create version: 0.5.1-b-build.1089+mc1.19.2

Crash Report
[crash-2023-07-12_17.51.02-client.txt](https://github.com/mrh0/createaddition/files/12030425/crash-2023-07-12_17.51.02-client.txt)

Modlist
![image_2023-07-12_175523191](https://github.com/mrh0/createaddition/assets/75280519/0acb3592-ad11-4c07-b564-dd1e8ec19e78)

Log
[latest.log](https://github.com/mrh0/createaddition/files/12030616/latest.log)

**Comment by skippyall** [comment]
Create Crafts & Additions for Fabric currently isn't compatible with Create 0.5.1. Use an older version of Create.

**Comment by mrh0** [comment]
Update to the latest version 20230723a.
