### ISSUE TITLE
1.20.1 Port?

### ISSUE THREAD

**Issue by KLONOA9X6** [mrh0/createaddition#607]
as the title

**Comment by markaabo** [comment]
I asked the same question on the discord and 2 people have said its already out but then backed down when i reply its not. and no one seems to wanna answer on the discord of when 1.20 is coming... kinda weird no-one of the mod devs wanna just give a msg like 1.20 is coming soon to confirm its in the plans :(

**Comment by mrh0** [comment]
Its going to happen, but icannot give you any timeframe

**Comment by techiend** [comment]
> Its going to happen, but icannot give you any timeframe

Im a JAVA Developer interesed in learn about Minecraft modding, I accept any comment or recomendation and I offer myself for help
