### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by minecraftuser1243** [mrh0/createaddition#611]
**Describe the bug**
I just installed this mod and now my game crashes on startup. 

**To Reproduce**
 I have deleted the mod and it loads up just fine. 

**Additional context**
- Mod version:20230527a
- Forge version:43.2.14
- Create version:0.5.0.i
[crash-2023-07-17_05.04.28-client.txt](https://github.com/mrh0/createaddition/files/12068999/crash-2023-07-17_05.04.28-client.txt)

**Comment by mrh0** [comment]
You are running an old version of this mod, please update to 20230623a
