### ISSUE TITLE
Biomass Pellet has a difference with REI

### ISSUE THREAD

**Issue by dorelboss9** [mrh0/createaddition#616]
**Describe the bug**
When you hold shift for summary it says that it can smelt 6 items but REI(Roughly Enough Items) says 5
(I think this issue can be reproduced with other similar mods for example JEI but haven't tested)

**To Reproduce**
Use fabric 1.19.2 version 0.14.19
Install Create fabric 0.5.0.i-1017+1.19.2
Install Create Crafts & Additions 20230508b
Install Roughly enough items (for me it's version 9.1.595 but any should work)
Enter the game on any world
Press "Shift" on a biomass Pellet.. it says 6 items
Pres "U" on it.. it says 5

**Additional context**
- Mod version:Create Crafts & Additions 20230508b
- Fabric version:fabric 1.19.2 version 0.14.19
- Create version:Create fabric 0.5.0.i-1017+1.19.2

**Comment by mrh0** [comment]
Fixed in 20230723a.
