### ISSUE TITLE
1.19.2 crashing upon launch

### ISSUE THREAD

**Issue by Asprin14** [mrh0/createaddition#617]
Using several different releases(beta or full releases) I get 1 of 2 results. Launches fine but adds nothing to the game, or it crashes upon launch giving me this error message:

"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'!"

and with an exit code: -1

I attempted to remake a new directory and folder. and use the minimum amount of mods to make it work.
- JEI
- Fabric API
- Create
- Create: Crafts & Additions

Even with bare bone mods I experienced the same two issues depending on which "crafts and additions" version I used.

- Mod version: 1.19.2
- Fabric version: 0.14.21
- Create version: 0.5.1(1.19.2)

not sure if I'm missing a dependency but it works fine on forge. I'm aware of this mods situation with fabric but I just wanted to raise attention(as I really like sodium) Thanks for your time!

**Comment by mrh0** [comment]
Update to the latest version 20230723a.

**Comment by Asprin14** [comment]
this has worked. thank you!
