### ISSUE TITLE
Crash with latest mod version and create version

### ISSUE THREAD

**Issue by minecraftuser1243** [mrh0/createaddition#618]
**Describe the bug**
Unbale to launch the game. Crashes during loading screen. 

**To Reproduce**
Steps to reproduce the behavior: Downgrading mod versions allow it to work.

**Additional context**
- Mod version:20230623a
- Forge version:43.2.14
- Create version:0.5.1.c
[crash-2023-07-24_00.58.16-client.txt](https://github.com/mrh0/createaddition/files/12143249/crash-2023-07-24_00.58.16-client.txt)

**Comment by mrh0** [comment]
Looks like its an issue with the mod custom fov: `java.lang.IllegalAccessError: failed to access class net.minecraft.client.Options$FieldAccess from class com.illusivesoulworks.customfov.mixin.ForgeMixinHooks`
