### ISSUE TITLE
Rolling mill ignores `count` for input items in its recipes

### ISSUE THREAD

**Issue by saltyseadoggo** [mrh0/createaddition#619]
**Describe the bug**
If you specify a `count` for the input item in a `createaddition:rolling` recipe and then try to use this recipe, the rolling mill will ignore the specified `count` and process the items one by one.

**To Reproduce**
- download this datapack: [rollingmilltest.zip](https://github.com/mrh0/createaddition/files/12152693/rollingmilltest.zip). it contains this recipe:
```
{
	"type":"createaddition:rolling",
	"input": {
      	"item": "minecraft:dirt",
	"count": 2
	},
	"result": {
		"item": "minecraft:stone",
		"count": 2
	}
}
```
- start up the game with create and c&a loaded
- create a new world, adding the datapack to it
- obtain two dirt
- place a rolling mill and power it
- ctrl-q to throw both dirt into the rolling mill at the same time

expected behavior: as per the recipe, the two dirt would be milled together into two stone
actual behavior: the `count` is ignored. the dirts are milled one at a time, producing a total of four stone.

**Additional context**
- Mod version: 20230623a
- Forge version: 43.2.8
- Create version: 0.5.1c

if this is intended behavior, then i would like to request that the ability to set the `count` for the rolling mill's input item be added. this would open up lots of options for modpack devs- for example, a recipe to mill six immersive engineering hemp into a tough fabric, so you can use the rolling mill to make the fabric more efficiently.~

**Comment by mrh0** [comment]
Yes, this is the intended behavior. However, I could add it.

**Comment by mrh0** [comment]
Not sure why, but I'm unable to get this working, I think that Create might be intervening and preventing the input be greater than one because the rolling mill implements sequenced assemblies. I gave it a good try. but I'm not willing to spend more time trying to fix this sorry.
