### ISSUE TITLE
Dynamo

### ISSUE THREAD

**Issue by Knalli65HD** [mrh0/createaddition#62]
For the Cogwheel-Mates if they want to power stuff with cogwheels

- **The Dynamo** is a block with a **cogwheel in the middle**, which **generates Power by using Cogwheels** 
- It would generate power at **-1 Rpm to -256 Rpm or 1 Rpm to 256 Rpm**
- **The FE/t is dependent on the Speed**

Hope this Suggestion is Approved

**Comment by mrh0** [comment]
This is just an Alternator with a cogwheel.
