### ISSUE TITLE
1.19.2 Fabric game crash on startup | version 20230723a

### ISSUE THREAD

**Issue by Hereux** [mrh0/createaddition#620]
The title already said it.
It is a modpack called "Create Live 4", which I copied and changed two things:
I added computercraft and updated Create Addition because of the redstone relay not working.
Now I wanted to do some ComputerCraft stuff with the mod. I had problems with accumulators and alternators not beeing recognized by the computer, so I decided to update the mod again. 
Now we're here. Minecraft starts and before the menu, it crashes with the error:

*The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'!*
[crash-2023-07-28_17.29.56-client.txt](https://github.com/mrh0/createaddition/files/12196159/crash-2023-07-28_17.29.56-client.txt)

**Additional context**
createaddition: createaddition-fabric+1.19.2-20230723a
Fabric: 0.14.19
create: create-fabric-0.5.0.i-1003)
some other create additions (i don't think they cause it) and about 60 other mods.

**Comment by Hereux** [comment]
Also happens with create version: create-fabric-0.5.0.i-1017

**Comment by mrh0** [comment]
20230723a does not support Create 0.5.0, update to 0.5.1
