### ISSUE TITLE
[1.20.1] Connector didn't broke with attached block broke

### ISSUE THREAD

**Issue by KLONOA9X6** [mrh0/createaddition#624]
**Describe the bug**
https://github.com/mrh0/createaddition/assets/95112579/63bcef80-f059-44bc-b58b-3d7acc3976a6

**To Reproduce**
_No Response_

**Additional context**
- Mod version: 1.20.1-1.0.0
- Forge version: 47.1.43
- Create version: 0.5.1.d

**Comment by mrh0** [comment]
it can be re-enabled in the configs

**Comment by KLONOA9X6** [comment]
OK, thanks
