### ISSUE TITLE
[1.20] JEI/REI Crash

### ISSUE THREAD

**Issue by Matiam0** [mrh0/createaddition#625]
**Describe the bug**
Crashing occures when attemting to use REI or JEI to get any rolling pin recipes to show.

**To Reproduce**
Steps to reproduce the behavior: Open inventory, hover over any wire or the rolling mill and hit either recipe keybind for the wire or uses keybind for the roller.

**Additional context**
- Mod version: 1.0.0
- Forge version: 47.1.3
- Create version: 0.5.1d

**Log**
[pastebin raw](https://pastebin.com/raw/nMQyXYVT)

**Comment by DJES169** [comment]
Yeah it's annoying and do you know the recipe to make wires? And it does the same with tesla coils.

**Comment by Matiam0** [comment]
I know the recipe but I'm testing a pack/creating one for some... less informed users. Crashing on the use of a function that I know will see extensive use, is bad.

**Comment by DJES169** [comment]
Do you know the recipe for the wires cause I don't know. :c

**Comment by DJES169** [comment]
also slows down pickaxes. :C

**Comment by mrh0** [comment]
fixed in 1.0.0b.

**Comment by Matiam0** [comment]
Thaanks!

**Comment by DJES169** [comment]
THANKS!!!! c:
