### ISSUE TITLE
[1.20.1] Crashes when Tesla Coil is activated

### ISSUE THREAD

**Issue by N-Wither** [mrh0/createaddition#626]
**Describe the bug**
[Crash Report](https://github.com/mrh0/createaddition/files/12268863/crash-2023-08-06_14.59.50-server.txt)

**To Reproduce**
1. Place a Tesla Coil and connect it to an energy source;
2. Activate it with a lever;
3. Game crashes

**Additional context**
- Mod version: 1.20.1-1.0.0
- Forge version: 47.1.3
- Create version: 1.20.1-0.5.1d

**Comment by mrh0** [comment]
fixed in 1.0.0b.
