### ISSUE TITLE
no working Pickaxes

### ISSUE THREAD

**Issue by RexXx2000** [mrh0/createaddition#627]
Hello
I created view weeks ago my own modpack to play with my friend.
everyday i look for mods i can add
and today i saw Create Crafts and Addition and added to my modpack.
Now is the problem, if i activate this mod in Curseforge and want to play every Pickaxe (paxels too) doesnt work (u break that block in the same time if u break that with a hand)

**Additional context**
- Mod version: 1.20.1-1.0.0
- Forge version:  471.3 (i know that are new versions but modpack works only with that version)
- Create version: 1.20.1-0.5.1.d

**Comment by Gbergz** [comment]
Can confirm this issue.

This is because of a block being in the blocks mineable tag that doesn't exist.
That block being: `createaddition:accumulator`, removing that entry makes blocks mineable again.

**Comment by mrh0** [comment]
fixed in 1.0.0b.
