### ISSUE TITLE
Electric Lamps

### ISSUE THREAD

**Issue by Thommy1830** [mrh0/createaddition#628]
Add Lamps that are activated using electricity

**Comment by samuelh2005** [comment]
If lamps are added I would like to see a large (ish) variety of lamps. For inspiration you can look at the [lamps from Electrical Age](https://wiki.electrical-age.net/index.php?title=Lamp#Street_Light)

**Comment by zavr1013** [comment]
This’ll be really cool

**Comment by mrh0** [comment]
added in v1.2.0.
