### ISSUE TITLE
Breaking of wires while driving

### ISSUE THREAD

**Issue by DefomCode** [mrh0/createaddition#630]
**Describe the bug**

Breakdown of wires during movement of mechanisms

**To Reproduce**

We connect two separate structures that move with wires and connectors. We move them and the wires break.
!
[Screen](https://github.com/mrh0/createaddition/assets/91155582/f2ac53d9-81c4-450b-a6c8-87d94e72e512)

I found this bug when I wanted to build a Mecha
(controlled robot). I had a working version of this mechanism on windmills, but it was too bulky and I decided to rebuild it with electricity. I rebuilt and at the moment of movement the wire broke. The wire distance was not exceeded.

**Additional context**
- Minecraft version: 1.19.2
- Mod version: createaddition-fabric+1.19.2-20230723a
- Fabric version: 0.14.21
- Create version:  create-fabric-0.5.1-b-build.1089+mc1.19.2
- Used optimized modpack OptiDef: https://modrinth.com/modpack/optidef-modpack

**Comment by mrh0** [comment]
connecting two separate contraptions is not supported, you need to use the Portable Energy Interface or have independent energy sources in each contraption
