### ISSUE TITLE
Errors: Couldn't load tag [createaddition:iron_spool (from createaddition-1.20.1-1.0.0b.jar)] + Couldn't parse element loot_tables:createaddition:blocks/accumulator

### ISSUE THREAD

**Issue by SkyKingPX** [mrh0/createaddition#631]
**Describe the bug**
Two Errors while startup

**To Reproduce**
Start a Forge Minecraft Server with this Mod

**Additional context**
- Mod version: 1.0.0b
- Forge version: 47.1.3
- Create version: 0.5.1d

Error: https://pastebin.com/nx2s2but

**Comment by GenuineJakob** [comment]
I also have this issue.

Minecraft:  1.19.2
Forge: 43.2.23
Create: 0.5.1.c
createaddition: 1.0.0

```
[net.minecraft.tags.TagLoader/]: Couldn't load tag [createaddition:iron_spool (from createaddition-1.19.2-1.0.0.jar)] as it is missing following references: createaddition:iron_spool (from createaddition-1.19.2-1.0.0.jar)
```
https://pastebin.com/XxyVAa2i

**Comment by mrh0** [comment]
this has been fixed
