### ISSUE TITLE
Liquid blaze burner block looses create:fan_transparent tag w/ post fix update

### ISSUE THREAD

**Issue by MikeyM3thodic4l** [mrh0/createaddition#634]
Liquid blaze burners block vencased fans placed vertically facing the block. 

Added createaddition:liquid_blaze_burner to data\create\tags\blocks\fan_transparent.json in a datapack to fix locally, apologies as I don't understand how to use github enough to be able to do a pull request or anything more helpful.

**Comment by mrh0** [comment]
fixed in v1.2.0.

**Comment by MikeyM3thodic4l** [comment]
I can open a new issue if you'd prefer, but I'd have to guess that it's related to the fix that was applied for this one. After the update, it appears that fans can now blow through the liquid blaze burners, but they don't seem to apply their state to the air passing though them. Both smoldering and kindled states don't seem to be reflected at all by the fan now.
