### ISSUE TITLE
[1.20.1] Multiple Createadditions blocks and items completely missing from JEI/Creative menu

### ISSUE THREAD

**Issue by markaabo** [mrh0/createaddition#638]
**Describe the bug**
When going creative stuff like electric motor and alot of other stuff is completely missing, and the same goes for JEI, with commands you are able to give yourself the items showing that the mod is working and it has the blocks ingame

**Additional context**
- Mod version: 1.0.0b
- Forge version: 1.20.1-47-1-43
- Create version: 1.20.1-0.5.1.d

Heres a screenshot of it
![2023-08-16_17 51 00](https://github.com/mrh0/createaddition/assets/68380434/5345277d-eebb-44ae-b3b1-f475dfb8a2e9)

**Comment by CcMenta** [comment]
I experienced this bug too, the original create items still exist but the creative menu doesn't show it.
I made a quick check which version of the mod doesn't do that and 1.0.0 don't make the items "disappear" but when I tried to check some items recipe the game crashed, so there was a change between 1.0.0 and 1.0.0b that makes this glitch.

**Comment by vnagfighter** [comment]
Use the curseforge version of the mod the version on modrinth is bugged now I tried 1.1.0 version (I use a modpack that has create 0.51d with mods that not compatible with 0.51e) from curseforge and there isn't any bug (I tried the 1.1.0 version from modrinth but the bug was still there).

**Comment by CcMenta** [comment]
Curseforge version seem to be less buggy than on modrinth
