### ISSUE TITLE
Connectors and Large Connectors not taking / moving FE after being placed.

### ISSUE THREAD

**Issue by ACactusWasTaken** [mrh0/createaddition#639]
This has been happening to me for a while on a server, the connector would work once we'd place it but stop after a while. This issue has been happening for a while.
This Modpack does not have any other mods that mess with FE Other Than CC&A.

Reproduction Steps
Placed the large / regular connectors to a alternator
Connect them all you are supposed to do to another connector that is connected to something.
Set Push / Pull whatever direction you want.
And You're Done. Trains do not affect this, this was just the only example I had but it has been happening for other stuff too.
Expected Result
after 5 - 10 Minutes the connectors will stop transfering power.

Screenshots and Videos
https://www.youtube.com/watch?v=3oxYeiCpmIA&ab_channel=ACactus Youtube Video because the video was too long unfortunately.

Crash Report or Log
No response

Operating System
Windows 11

Mod Version
0.5.1d

Minecraft Version
1.19.2

Forge Version
43.2.6

**Comment by mrh0** [comment]
well in the video the connector on the portable energy interface is in the wrong mode, should be push
