### ISSUE TITLE
Silver ingot missing

### ISSUE THREAD

**Issue by beans1324** [mrh0/createaddition#641]
Silver does not appear in the JEI list, and does not appear in the world. This makes it impossible to create things such as electrum. When in creative, silver only appears in the menu as crushed silver. 

- Mod version: 1.0.0b
- Forge version: 47.1.0
- Create version: 0.5.1.d

**Comment by unlistedsky2** [comment]
how is this working as intended? how are you supposed to make electrum?

**Comment by beans1324** [comment]
@mrh0 how is this working as intended?

**Comment by mrh0** [comment]
I dont add silver, bunch of other mods do however. Electrum was added for inter mod compat, i might make it obtainable trough some other methods late but ive not planned anything

**Comment by Dabduck** [comment]
> I dont add silver, bunch of other mods do however. Electrum was added for inter mod compat, i might make it obtainable trough some other methods late but ive not planned anything

Is there a mod that u would suggest using to get silver ingots into the game (1.20) @mrh0

**Comment by mrh0** [comment]
Immersive Engineering plays well with this mod, i also thing thermal expansion adds silver

**Comment by Dabduck** [comment]
@mrh0 I'm pretty sure that those 2 mods have versions only to 1.19. Could you maybe suggest a mod that is for 1.20

**Comment by mrh0** [comment]
This recipe is no longer visible (in latest version) if you do not have a mod that adds silver installed
