### ISSUE TITLE
Trains Powered & Made Faster By FE

### ISSUE THREAD

**Issue by ACactusWasTaken** [mrh0/createaddition#650]
In base Create, trains can be powered by putting a burnable source in a chest which makes them fast. What if you could do the same with Accumulators and maybe being able to toggle this.

**Comment by QWXL** [comment]
I hope this feature appears

**Comment by samuelh2005** [comment]
Maybe a duplicate of #301?

**Comment by mrh0** [comment]
Sorry, I'm not adding this
