### ISSUE TITLE
Electric Monorails

### ISSUE THREAD

**Issue by Xaidee** [mrh0/createaddition#653]
I'd love to see a new train track that's just a single line without the wood and trains placed upon it are powered by the monorail system that must be provided electricity from the things in this mod to work, maybe it could be made out of gold, copper, or the new electrum alloy

**Comment by Xaidee** [comment]
Similar suggestion to #650 except a new block/mechanic

**Comment by mrh0** [comment]
Sorry, I will not be adding this.

**Comment by Xaidee** [comment]
:+1:
