### ISSUE TITLE
item crashing

### ISSUE THREAD

**Issue by IshuCute** [mrh0/createaddition#655]
**Describe the bug**
when i start to use items, game gets crashed after couple of seconds with error code -1 (game version: 1.19.2)

**To Reproduce**
just get some items to inventory (generator, motor and wire)

**Additional context**
- Mod version: 20230211a
- Fabric version: 0.14.19
- Create version: 0.5.0i
![image](https://github.com/mrh0/createaddition/assets/119164425/cbe91aa5-ede3-4f32-a689-e111d33c4460)

**Comment by IshuCute** [comment]
correction: the game crashes in the creative menu in the mod's tab

**Comment by mrh0** [comment]
This issue was fixed in later versions
