### ISSUE TITLE
Missing passive model for large connector

### ISSUE THREAD

**Issue by Xyphenore** [mrh0/createaddition#656]
**Describe the bug**

For the blockstate '**large_connector**' missing the model '**block/connector/large/passive.json**' for the state 'large_connector#facing=north,mode=push,rotation=none'

The warning from the console:

'Unable to load model: 'createaddition:block/connector/large/passive' referenced from: createaddition:large_connector#facing=north,mode=push,rotation=none: java.io.FileNotFoundException: createaddition:models/block/connector/large/passive.json'

**To Reproduce**

- Install the mod.
- Run the game with the output console.
- Warning is printed to console.

**Additional context**
- Mod version: 1.0.0b for 1.20.1
- Forge version: 47.1.47
- Create version: 0.5.1b for 1.20.1

**Comment by mrh0** [comment]
fixed in v1.2.0.
