### ISSUE TITLE
Crashes On Launch without Latest.log or Crashlog

### ISSUE THREAD

**Issue by MasterCJ123** [mrh0/createaddition#661]
**Describe the bug**
So it too a while for me to figure out that it was Create Crafts & Additions that was the issue. I have over 122 mods loaded. I have no idea what or how to even give you more information.  Crashlogs and Latest.log dont pick up anything. Im sorry this isnt much help.

**To Reproduce**
Best Way i can say is download the "Master CJ's V+" modpack and add Create, Alexs Mobs and Visual Overhall. I have many mod mods I customized with this modpack but those are the biggest ones.:

**Additional context**
- Mod version: 1.201
- Forge version: 47.1.47
- Create version:  
create-1.20.1-0.5.1.e.jar

**Comment by mrh0** [comment]
Aware, will get to it asap

**Comment by mrh0** [comment]
fix is out.
