### ISSUE TITLE
Startup crashing with latest log and crash report

### ISSUE THREAD

**Issue by TimeNewKirill20** [mrh0/createaddition#662]
**Describe the bug**
![Minecraft Forge_ 1 20 1 22 09 2023 21_29_45](https://github.com/mrh0/createaddition/assets/126814818/43b7fb56-ae7f-456a-9856-4faa82fc5dc6)
![CurseForge 22 09 2023 21_48_08](https://github.com/mrh0/createaddition/assets/126814818/77b31f8e-057a-4b14-997b-c54e90bbbcc1)

**To Reproduce**
1.Launch Minecraft
2.Wait
3.It's crashing

**Additional context**
- Create Crafts & Additions v1.1.0:
- Forge version 47.1.0:
- Create v0.5.1e:

**Comment by TimeNewKirill20** [comment]
**Latest log**
[latest.log](https://github.com/mrh0/createaddition/files/12703879/latest.log)

**Crash report**
[crash-2023-09-22_21.11.29-fml.txt](https://github.com/mrh0/createaddition/files/12703885/crash-2023-09-22_21.11.29-fml.txt)

**Comment by MasterSparkInYourFace** [comment]
caused by latest create update. this mod needs to update for compatibility

**Comment by mrh0** [comment]
Aware, will get to it asap

**Comment by TimeNewKirill20** [comment]
@mrh0 thank you

**Comment by mrh0** [comment]
fix is out
