### ISSUE TITLE
Accumulator breaks chunks

### ISSUE THREAD

**Issue by BOTGrzes** [mrh0/createaddition#663]
**Describe the bug**
Chunk disappears and doesn't render if there's an accumulator in this chunk.

**To Reproduce**
Place an accumulator
Leave the server
Restart the server
Join back into the server

**Additional context**
- Mod version: 1.20.1-1.0.0b
- Forge version: 47.1.0
- Create version: 1.20.1-0.5.1.d

![image](https://github.com/mrh0/createaddition/assets/64188833/c0962259-739d-4902-818a-d0a24a34b0d4)

**Comment by mrh0** [comment]
Already fixed, update to 1.1.0
