### ISSUE TITLE
Straw missing in 1.16.5

### ISSUE THREAD

**Issue by Jevnaker** [mrh0/createaddition#667]
**Describe the bug**
The straw doesnt show up when i installed the 1.16.5 version of the mod

**To Reproduce**
Steps to reproduce the behavior: install create and this mod only to a 1.16.5 minecraft install along with JEI and start a world in creative mode and search for it. sorry if i missed something but unlike some other features it didnt have an works only in version x  y and z next to it

**Additional context**
- Mod version: 
createaddition 1.16.5-20220129a

- Forge version:
36.2.39
- Create version: 
Create 1.16.5 v0,3,2g 
flywheel 1.16-0.2.5.jar (beta)

**Comment by mrh0** [comment]
1.16 is no longer supported, the straw was added much later

**Comment by Jevnaker** [comment]
Ok thanks for the explenation it wasnt clear on the mod page ill uninstall it then sorry for the bug report.
