### ISSUE TITLE
Diamond Grit Sandpaper is unobtainable outside creative inventory.

### ISSUE THREAD

**Issue by payphone101** [mrh0/createaddition#674]
**Describe the bug**
Diamond grit sandpaper isn't available for crafting.

**To Reproduce**
1. Install the create mod `(v.0.5.1-d-build.1161+mc1.20.1)` and create crafts and additions `(v.0.9.0)`
2. Create a new world.
3. Acquire diamond grit (either from crushing diamonds or the creative inventory) and regular paper
4.a. Open your inventory screen (in survival) and try to craft diamond grit sandpaper by placing the ingredients on the 2x2 crafting grid
4.b. Interact with a crafting table and try to craft diamond grit sandpaper by placing the ingredients on the 2x2 crafting grid
4.c. Place the ingredients in a mechanical crafter and power the crafters

**Expected behaviour:**
You are able to craft the diamond grit sandpaper

**Observed Behaviour:**
You cannot craft the diamond grit sandpaper

**Additional context**
- Mod version: `v.0.9.0` FABRIC
- Fabric version: `0.14.3-1.20.1` 
- Create version: `v.0.5.1-d-build.1161+mc1.20.1`

**Comment by Dragonissa** [comment]
Same here, JEI is also reporting it only needs paper to craft it.
![image](https://github.com/mrh0/createaddition/assets/4233773/8146db5f-4db8-4e53-bfe0-3ea766bf49d7)

**Comment by mrh0** [comment]
odd, probably a fabric tag issue

**Comment by BLovegrove** [comment]
I'm seeing the same issue in Quilt - any chance this could be solved in a future update? Or is this up to whoever maintains the fabric port (:

**Comment by E3VL** [comment]
ples, how did u get 1.20.1 to work. My monk brain cant get it run

**Comment by Abieunder** [comment]
im having the same problem and i have a picture using the crafting blueprints that says it requires diamond_dusts 
![image](https://github.com/mrh0/createaddition/assets/111644779/45e2d83e-f25b-4161-bf31-0b309239b10d)

**Comment by cursedtitanium** [comment]
I definitely should've responded to this way earlier, because I actually already fixed this with #659 / #660, but those versions of the mod just haven't been updated since the fix.
