### ISSUE TITLE
Accumulator problem.

### ISSUE THREAD

**Issue by crizzdevizz** [mrh0/createaddition#676]
the battery only charges halfway, then it stops.
What can I change about this?

**Comment by crizzdevizz** [comment]
![image](https://github.com/mrh0/createaddition/assets/106772888/1fa88700-93d8-469f-b931-c7e41b7c97ff)

**Comment by mrh0** [comment]
could be a mismatch in configuration between the server and client, are you playing on a server?

**Comment by crizzdevizz** [comment]
Yes, this is on a server.

**Comment by mrh0** [comment]
then that's probably it, copy the config file from the server to your client
