### ISSUE TITLE
Straw Sadness

### ISSUE THREAD

**Issue by YoYoBobbyJoe** [mrh0/createaddition#678]
A Blaze Burner with a Straw cannot be blown by an Encased Fan like a regular Blaze Burner can.

Place a fan next to a Blaze Burner to cook things, and give it heat. Be happy. Give it a straw to automate fueling via lava. Be sad.

**Additional context**
- Mod version: 1.19.2-1.1.1
- Forge version: 43.3.0
- Create version: 0.5.1.f

**Comment by Bugamashoo** [comment]
I have this problem too

**Comment by mrh0** [comment]
fixed in v1.2.0.
