### ISSUE TITLE
Device to heat furnace blocks "Friction Heater"

### ISSUE THREAD

**Issue by TheSpicePhantom** [mrh0/createaddition#68]
The idea of a Friction Heater dates all the way back to "Rotary Craft" (1.4-1.6, I think).

It's a device just like the Furnace Engine.
It attaches directly to one of the 4 cardinal sides of a Furnace, Blast Furnace or Smoker.

High RPM required, as well as at least double the rotational force of a normal crushing wheel.
When powered sufficiently, it will constantly produce heat in the furnace.
It needs to be incompatible with the Furnace Engine, of course 😄

**Comment by T3sT3ro** [comment]
isn't that what induction heater does ?

**Comment by TheSpicePhantom** [comment]
The induction heater requires energy (FE) to work. And it's "harder" to make (as you need to have an alternator and the induction heater itself).
With the friction heater it's the other way around. It requires rotational force and maybe an item, "Friction Pads"(?) which get used up.
The Friction Heater is way cheaper to make but has a significant impact on the stress capacity of the network.

**Comment by mrh0** [comment]
feels redundant, bulk smelting/smoking already use rotational force to smelt.
