### ISSUE TITLE
[Server Crash] [1.20.1] java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'

### ISSUE THREAD

**Issue by originalFactor** [mrh0/createaddition#681]
**Describe the bug**
crash report: https://gist.github.com/originalFactor/68760cb197f9aaad972cc354376e199c

**To Reproduce**
1. Deploy a Minecraft forge 1.20.1 server using mohist core
2. Add mods in crash report
3. Start the server
4. The problem arises!
5. I don’t know how it happened.

**Additional context**
- Mod version: 1.20.1-1.0.0b
- Forge version: 1.20.1-47.2.4
- Create version: 1.20.1-0.5.1

**Comment by mrh0** [comment]
please update to version 1.1.1
