### ISSUE TITLE
Compatibility Broken with CraftTweaker and KubeJs

### ISSUE THREAD

**Issue by TopStiGear** [mrh0/createaddition#683]
**Describe the bug**
Unable to create recipes using CreateAddition machines.
CraftTweaker reads all existing RecipeTypes as `<recipetype:null>` and sends back the error `Unknown RecipeType: <recipetype:createadditions:rolling>`

**To Reproduce**
Run Command `/crafttweaker recipes hand` with a CreateAdditions machine craftable item for logs to read back `<recipetype:null>`.
Run Command `/ct dump recipetype` to have no CreateAddition RecipeTypes return in logs.

**Additional context**
- Mod version: 1.1.1
- Forge version: 47.2.6
- Create version: 0.5.1.f
- CraftTweaker version: 14.0.23
- CreateTweaker version: 4.0.7

This is not just a CraftTweaker issue. It is a base code issue of the CreateAddition Mod itselt by not labelling RecipeType's correctly.
All it would take to fix is to change the RecipeType from Null to the correct type, Rolling, Charging or Liquid_Burning.
KubeJs is not a fix its a cop-out for coding a mod incorrectly.
Update: It also does not work with KubeJs as they also rely on correct RecipeType labelling.

**Comment by mrh0** [comment]
fixed in v1.2.0.
