### ISSUE TITLE
[Suggestion] Ender Storage-type inventory that can move with contraption

### ISSUE THREAD

**Issue by lord-ne** [mrh0/createaddition#686]
Some kind of ender chest like in Ender Storage that is able to move with contraptions/work while moving would be very useful. It would allow a lot of things to be more fully automated with other mods (such as AE2 storing items from a miner, or providing more tracks when building a new rail line) . I believe Create Integration had an Ender Crate that worked like this.

**Comment by mrh0** [comment]
No, not adding this, this steps on the usefulness of trains and portable storage interfaces
