### ISSUE TITLE
[1.20.1] Mod caused a crash in the server

### ISSUE THREAD

**Issue by GameBurrow** [mrh0/createaddition#688]
**Describe the bug**
It seems the mod caused a crash on our server
Crash report: https://gist.github.com/GameBurrow/eb25e1202d94d4e303c3f29991a99a25

This what the person described he was doing when the server crashed:
> i rewired my woodfarm .. so i guess when i removed the powerline it got placed ... and this crashed server once again ..

**To Reproduce**
N/A

**Additional context**
- Mod version: 0.9.0
- Fabric version:  0.14.24
- Create version: Create Sodium Fix v0.5.1.d https://modrinth.com/mod/create-fabric-sodium-fix/version/0.5.1-d-build.5+mc1.20.1

**Comment by mrh0** [comment]
log references `org.antarcticgardens.newage.content.electricity.network` and thats not this mod

**Comment by GameBurrow** [comment]
Ah yes, I was looking at the entity that ticked during the crash. Apologies.
