### ISSUE TITLE
Radio station 

### ISSUE THREAD

**Issue by Dorpi43** [mrh0/createaddition#689]
This thing can help to transmit signals from very long distance. For example it's make possible to activate some contraptions on zero chunk from any distance. But for larger distances you need more energy of course. Also for this thing can be used transformer and new type of current: alternating. Because transformer can't work on DC. I wish you make dc only like current for accumulators and to make it we need to use inverter because alternator also must generate alternating current with frequency

**Comment by mrh0** [comment]
Already said previously in the discord: I'm not adding AC/DC, I sort of like the idea of a radio though, but I'm not sure i want to ad wireless redstone when that already exists in create
