### ISSUE TITLE
Mechanical arm not working with blaze burner with straw

### ISSUE THREAD

**Issue by hahawowausername** [mrh0/createaddition#690]
**Describe the bug**
Mechanical arm cannot be set to deposit items to a blaze burner with straw

**To Reproduce**
Attempt to right click a blaze burner with straw with a mechanical arm in hand

**Additional context**
- Mod version: 1.18.2-1.0.0
- Forge version: Whatever version of forge FTB Stoneblock 3 1.8.1 runs
- Create version: 1.18.2-0.5.1.c

**Comment by mrh0** [comment]
fixed in v1.2.0.
