### ISSUE TITLE
Config Changes Not Affecting Alternator

### ISSUE THREAD

**Issue by SpaceFlier100** [mrh0/createaddition#702]
I was trying to change the max stress input of the alternator to require less of them for my steam engine, so I changed the max_stress value under general to a higher number (not sure if this is right but the description says max stress for alt and motor at 256 rpm). Upon this not changing anything I changed the efficiency for the alternator to 1 instead of 0.75 and found that the energy generated did not change

1. Change the config file
2. see that this doesn't affect anything
3. 
- Mod version: 1.0
- Forge version: 40.2.14
- Create version: 0.5.1

**Comment by mrh0** [comment]
This has been fixed, please update the mod
