### ISSUE TITLE
Placeholder death message (Tesla Coil)

### ISSUE THREAD

**Issue by Eggmanplant** [mrh0/createaddition#707]
**Describe the bug**
Placeholder death message (Tesla Coil)

**To Reproduce**
Kill using tesla coil

**Additional context**
- Mod version: 1.20.1-1.1.1
- Forge version: NeoForge 47.1.84
- Create version: 0.5.1.f

![Screenshot from 2023-12-31 22-07-aa04](https://github.com/mrh0/createaddition/assets/126160675/a7e651c2-84bf-414b-9e1a-b88783f493c5)

**Comment by mrh0** [comment]
It shows the correct message for me, update the mod and see if it persists
