### ISSUE TITLE
Enhance Accumulator to be read by Threshold Switch

### ISSUE THREAD

**Issue by KalWantsPizza** [mrh0/createaddition#711]
Having the ability to turn off an alternator linked to an accumulator and automatically turn back on when falling below a pre-determined level would be helpful in managing SU.

There IS a workaround where you can use a comparator to read it but that isn't as "Create-y" as using a threshold switch like you can for item storage and fluid tanks.

**Comment by samuelh2005** [comment]
This could solves #90 and duplicates

**Comment by mrh0** [comment]
This is already a thing, i even tested it recently to make sure it was still working

**Comment by KalWantsPizza** [comment]
Is there a trick to attaching it to a certain place? I'll give it another shot, but it wouldn't work for me at all. If it still doesn't I'll provide screenshot(s).

**Comment by KalWantsPizza** [comment]
I stand corrected, it does work. Must have been attaching the wrong face before.
