### ISSUE TITLE
No Energy (FE) getting passed through the accumulator

### ISSUE THREAD

**Issue by FnafPizzaFan** [mrh0/createaddition#716]
**Description**
I was just working on an elevator when suddenly everything stopped, I checked the gauge and suddenly all 10Mfe worth of power just vanished to 0fe, and the problem isn't that there's too much usage because I use the Redstone relay to store power.

**Reproduction**
No clue how to reproduce, it just happened suddenly.

**Additional context**
- Mod version: 1.0.0 (1.18.2)
- Forge version: 40.2.4
- Create version: 0.5.1f
![Desktop Screenshot 2024 01 14 - 22 05 06 55](https://github.com/mrh0/createaddition/assets/90162306/4ec08ae6-a9e1-4c17-90be-064b7b25e34a)
![Desktop Screenshot 2024 01 14 - 22 05 14 49](https://github.com/mrh0/createaddition/assets/90162306/5330f237-b0b3-4b56-a87f-c2a623146c4d)

**Comment by mrh0** [comment]
Update to the latest version, you provided no steps to reproduce so this will be hard to debug

**Comment by MrRedstoneToGo** [comment]
Did you set the first connector to input and the second one to output mode on each accumulator?

**Comment by MrRedstoneToGo** [comment]
Does electricity flow through the cables? Make sure all connectors have the right mode (Push/Pull/None) and there the FE aren't being consumed by motors or Tesla Coils etc...
