### ISSUE TITLE
Games crashes upon mod loading

### ISSUE THREAD

**Issue by ferforious1** [mrh0/createaddition#718]
**Describe the bug**
Game crashes with an error upon mod loading

**To Reproduce**
-

**Additional context**
- Mod version: 1.0.0b
- Forge version: 47.2.20
- Create version: 0.5.1f
- Minecraft version: 1.20.1

[crash-2024-01-17_09.03.21-fml.txt](https://github.com/mrh0/createaddition/files/13959323/crash-2024-01-17_09.03.21-fml.txt)

**Comment by mrh0** [comment]
please update to the latest version before submitting a report
