### ISSUE TITLE
Add Immersive Engineering kinetic power -> Create rotation converter (Treated Wood Gearbox?)

### ISSUE THREAD

**Issue by Lgmrszd** [mrh0/createaddition#72]
I personally love aesthetics of IE's Windmills and Water Wheels. It would be neat to have them as alternative power sources for Create, slightly better than Create's Water Wheel and Windmill, as IE ones require more and also refined materials.

If such functionality is possible (for example, with specific conversion block, as I suggested for example "Treated Wood Gearbox"). it would be neat if it would actually scale Stress Capacity depending of kinetic power provider (e.g. scale with number of water wheels attached)

**Comment by mrh0** [comment]
Nah, use an electric motor.

**Comment by Lgmrszd** [comment]
IE windmill -> IE kinetic generator -> CC&A motor would look kinda lame tho...

**Comment by Lgmrszd** [comment]
_Fine, I'll do that myself_
