### ISSUE TITLE
Liquid Blaze Burners hold wrong amount of liquid

### ISSUE THREAD

**Issue by KonSola5** [mrh0/createaddition#728]
## Describe the bug
Liquid Blaze Burners hold 4000... **droplets**. (Fabric uses Droplets, 1 bucket = 81000 droplets).

![burner](https://github.com/mrh0/createaddition/assets/125081901/5e18983e-1e5d-41e1-97da-d0707dd2cf3c)

It's probably an oversight when porting the mod from Forge to Fabric:
https://github.com/mrh0/createaddition/blob/e5b55eea526a04d51d24aa95a1896f040e2d406b/src/main/java/com/mrh0/createaddition/blocks/liquid_blaze_burner/LiquidBlazeBurnerTileEntity.java#L102-L104

## To Reproduce
1. Equip Engineer's Goggles.
2. Give a Blaze Burner a Straw.
3. Watch the tank capacity being "49 mB" or "4000 Droplets".

## Additional context
- Mod version: v20230704a
- Fabric version: 0.15.1
- Create version: v0.5.1-b-build.1088+mc1.18.2

**Comment by skippyall** [comment]
I already fixed that
