### ISSUE TITLE
Game crashes when a connector with a wire attached rotates and other strange behaviour.

### ISSUE THREAD

**Issue by DevLaika** [mrh0/createaddition#73]
**Describe the bug**
This is a bug consisting out of two stages:
1. Connectors don't rotate properly. They keep their original rotation. This means that after rotating, if the connector is not supported ("attached" to air), it pops off and drops as an item.
2. When two connectors were already connected by wire, and the connectors are then rotated, causing them to become unsupported ("attached" to air), the game crashes.
Steps to reproduce this issue are listed below.

I have also found two other, most likely, unintentional cases of strange behavior:
a. Most of the time, when moved a wired connector loses its connection. This only happens if both connectors are moved.
b. When both by wire connected connectors are moved with another empty connector moving to the previous location of the connected ones some of the connectors will connect to one another, not the intended ones however.

I recommend playing around with moving and rotating the connectors around as these are most likely not the only instanced of strange behavior. 

**To Reproduce**
For the first issue simply create a platform with a mechanical bearing attached to rotate, controlled by a crank. Attach two connectors, one vertically and one horizontally, to the platform and connect these with a wire. Turn the platform and the game crashes. (See the attached image)
![See: ](https://user-images.githubusercontent.com/41267035/120719129-2bab0c00-c4ca-11eb-880c-4e35d739204a.png)

**Additional context**
- Mod version: createaddition-1.16.5-20210517a
- Forge version: forge-36.1.0
- Create version: create-mc1.16.5_v0.3.1c

**Comment by mrh0** [comment]
Yeah, they don't handle being moved atm.

**Comment by mrh0** [comment]
Fixed in 20220517a.
