### ISSUE TITLE
RF/SU Ratio Tweaks

### ISSUE THREAD

**Issue by dannydjdk** [mrh0/createaddition#74]
With the default settings, you can produce a ton of stress units with a tiny amount of RF. For example, a single water wheel from IE can produce as much rotational force as 16 Create water wheels. I'd like to suggest changing that ratio by a factor of 10. This also requires increasing the capacity and input/output rates of the motor and alternator.

I understand (and very much appreciate) the fact that mod authors can tweak these numbers to their heart's desire... and I did just that. But, I really think the default behavior is unreasonable and trivializes rotational energy.

Here's an example of my setting which I believe to be reasonable, resulting in 1 IE water wheel producing about the same as 1.6 Create water wheels:
https://pastebin.com/FpE1g1Nb

**Comment by mrh0** [comment]
Yes, I'll consider it.

**Comment by mrh0** [comment]
The default SU/FE numbers have recently been tweaked.
