### ISSUE TITLE
[Fabric] Recipes not wokring

### ISSUE THREAD

**Issue by muriplz** [mrh0/createaddition#740]
**Describe the bug**
Some recipes don't work.

**To Reproduce**
![image](https://github.com/mrh0/createaddition/assets/46825658/fd6c8540-fe28-45f8-b45e-cf73b126f441)

**Additional context**
- Mod version: 1.2.1b
- Fabric version: 91
- Create version: 0.5.1d

**Comment by xCykrix** [comment]
I'm having a separate odd issues which might possibly be related to this. When using this version of the mod with Nuministic Overhaul specifically a server fails to send recipe data to the client. Last version is compatible and works as expected.

@muriplz What is your modlist for this? Would like to see if it is similar behavior. Also were you using server or singleplayer?

https://mclo.gs/p69oUu3

**Comment by muriplz** [comment]
> I'm having a separate odd issues which might possibly be related to this. When using this version of the mod with Nuministic Overhaul specifically a server fails to send recipe data to the client. Last version is compatible and works as expected.
> 
> @muriplz What is your modlist for this? Would like to see if it is similar behavior. Also were you using server or singleplayer?
> 
> https://mclo.gs/p69oUu3

The modlist is rather small. No logs or anything in console.
- Create
- Create Missions
- this mod
- Brewin and Chewin
- Farmers delight
- decorative blocks
- steam n rails
- create deco

Its being used in a server

**Comment by mrh0** [comment]
what are you trying to make in the image? that's like any recipe in the mod

**Comment by MrRedstoneToGo** [comment]
If you want to connect blocks that use FE, place down two Connectors and right click on both with a copper/iron/gold/electrum spool. The recipe what you're showing doesn't exist, I think.

**Comment by MrRedstoneToGo** [comment]
Install Just Enough Items/REI/EMI to view all recipes in your modpack.
