### ISSUE TITLE
1.20.1 Error logging into server - Loading NBT data

### ISSUE THREAD

**Issue by Gamerbolts** [mrh0/createaddition#744]
**Describe the bug**
I updated your mod to 1.2.1b on my server and the client loads fine and the server loads up fine but when I try to connect I get an error
Caused by: java.io.IOException: Invalid tag id: -103
at com.mrh0.createaddition.recipe.charging.SequencedAssemblyChargingRecipeSerializer.readFromBuffer(SequencedAssemblyChargingRecipeSerializer.java:83) ~[createaddition-fabric+1.20.1-1.2.1b.jar:?]

**To Reproduce**
Steps to reproduce the behavior: This is my modpack PXC Fabric Adventure which is on CurseForge, I was updating mods and got this error logging into my server

**Additional context**
- Mod version: 1.2.1b
- Fabric version: 0.15.7
- Create version: I am using Prominent Create v0.5.1-d

Here is the log since it was not technically a crash I don't have a crash log. Any help is appreciated. Thanks!
[latest.log](https://github.com/mrh0/createaddition/files/14434550/latest.log)

**Comment by LoAndEvolve** [comment]
I have the same issue

**Comment by CassieRoseZA** [comment]
Same Here

**Comment by skippyall** [comment]
Oh no I forgot to write the max charge rate to the buffer. I'm going to make a pull request

**Comment by skippyall** [comment]
#749

**Comment by mrh0** [comment]
Fixed in 1.2.1c
