### ISSUE TITLE
Wire/spool doesn't get shown to all player when made

### ISSUE THREAD

**Issue by Ch1216** [mrh0/createaddition#75]
**Describe the bug**
When a player makes a wire by connecting 2 connecters with a spool, The wire only shows up in the player who made it screen, other player don't see the wire

**To Reproduce**
1. Be in a multiplayer
2. Make someone who is not you make a wire 
3. Notice how the wire only shows up on their screen and not yours

**Additional context**
- Mod version: 20210517a
- Forge version: 36.1.24
- Create version: 0.3.1c

**Comment by mrh0** [comment]
Strange, haven't experienced this myself when testing, I'll look into it.

**Comment by Ch1216** [comment]
its been kind of fixed by 20210713a, but there still are some issues, it works when connecting two unconnected connectors, but **_sometimes_** when connecting two connectors which have been connected to other connecters, the wire wont appear, its not random chance, its only on certain circumstances

**Comment by mrh0** [comment]
> its been kind of fixed by 20210713a, but there still are some issues, it works when connecting two unconnected connectors, but **_sometimes_** when connecting two connectors which have been connected to other connecters, the wire wont appear, its not random chance, its only on certain circumstances

Didn't see this message until now, could you be more specific such that I can replicate it myself?
