### ISSUE TITLE
Modular Accumulator

### ISSUE THREAD

**Issue by LordMaximus05** [mrh0/createaddition#755]
**Describe the bug**
Someone on the server has a modular accumulator, and every time anyone goes to their area, it crashes the server and no longer allows them to join the server as it keeps crashing. Log attached.

**To Reproduce**
Log onto server
Go to area
crash.

**Additional context**
- Mod version: createaddition-fabric+1.20.1-0.9.0
- Fabric version: 1.20.1
- Create version: create-sodium-fix-0.5.1-d-build.5+mc1.20.1 
[latest (6).log](https://github.com/mrh0/createaddition/files/14565855/latest.6.log)

**Comment by mrh0** [comment]
Please update to the latest version of the mod
