### ISSUE TITLE
Zinc Plate Conflict

### ISSUE THREAD

**Issue by RobHof24** [mrh0/createaddition#763]
I was attempting to create a zinc plate for a capacitor and realized the recipe coincided with Create Deco's recipe for their zinc plate and neither are compatible with each other. 

**To Reproduce**
Use a press on a zinc ingot while both Create Crafts & Additions and Create Deco are downloaded.

**Additional context**
- Mod version: CC&A: 1.20.1-1.2.3 | CDeco: 2.0.1-1.20.1
- Forge version:  47.2.0
- Create version: 1.20.1_v1.1.0

**Comment by mrh0** [comment]
Create Deco needs to tag their plate with forge:plates/zink
