### ISSUE TITLE
Chunk not loading when accumulator is placed in it

### ISSUE THREAD

**Issue by CDNHeadls** [mrh0/createaddition#764]
Description
Whenever placing a accumulator and letting the chunk unload, the chunk wont load again unless you rejoin

**To Reproduce**
- Place a accumulator
- Unload the chunk
- Come back

**Additional context**
- Mod version:  1.18.2 1.0.0
- Forge version:  40.2.4
- Create version: 1.18.2 0.5.1f

**Comment by mrh0** [comment]
Sorry, I'm no longer supporting 1.18
