### ISSUE TITLE
Server crashing after breaking accumulator from Create: Crafts and Additions

### ISSUE THREAD

**Issue by rymusov** [mrh0/createaddition#768]
As soon as I want to break the accumulator, with energy and it is connected by wires - the server crashes. If I disconnect the connectors and wires beforehand, the crash does not happen. Version 1.20.1, Forge 47.2.21. Video: https://youtu.be/sEwVBQ1Fihs

**To Reproduce**
[Steps to reproduce the behavior:] https://youtu.be/sEwVBQ1Fihs

**Additional context**
- Mod version: 1.20.1-1.2.3
- Forge version: 47.2.21
- Create version: 0.5.1f

**Comment by mrh0** [comment]
Could you please provide the crash logs for the server?

**Comment by rymusov** [comment]
Oh, sorry, yes
[2024-04-03-1 (1).log](https://github.com/mrh0/createaddition/files/14896838/2024-04-03-1.1.log)
[debug-1 (1).log](https://github.com/mrh0/createaddition/files/14896839/debug-1.1.log)
[crash-2024-04-03_12.25.47-server (1).txt](https://github.com/mrh0/createaddition/files/14896840/crash-2024-04-03_12.25.47-server.1.txt)

**Comment by mrh0** [comment]
This is a Create New age error `org.antarcticgardens.newage`
