### ISSUE TITLE
Small connector with light doesn't work with redstone relay.

### ISSUE THREAD

**Issue by JohnM6502** [mrh0/createaddition#798]
**Issue**
When using a light connector hooked up to a relay to turn it on an off, the lights will not turn on unless there is a load on that line.

**To Reproduce**
Hook up a power source to a relay, then connect the relay to the string of light connectors. When the relay is flipped on, the lights will not work. But if you hook up a motor, accumulator, etc... to the end of the lights it will turn them on. 

**Additional context**
- Mod version: Minecraft 1.20.1
- Forge version: 47.2.0
- Create version: Crafts and Additions 1.2.3

**Comment by skippyall** [comment]
I think that network.demand must be called somewhere in the specialTick method of [SmallLightConnectorBlockEntity](https://github.com/mrh0/createaddition/blob/1.19.2/src/main/java/com/mrh0/createaddition/blocks/connector/SmallLightConnectorBlockEntity.java)

**Comment by mrh0** [comment]
This has been fixed
