### ISSUE TITLE
Electrical Resistance (Block)

### ISSUE THREAD

**Issue by Knalli65HD** [mrh0/createaddition#80]
Electrical Resistances are used for:

- setting the Max FE, which amount of it is allowed to flow through
- using it to generate Thermal energy (You could power Encased fans with it or maybe using it as a other Basin-Heater)
- Messure the FE and FE/t
- Splitting the Circuit/Wiring

It is configurable with a wrench

(To be honest i have no other idea what it used for FE-Network or anything else)
Any more ideas for it?

**Comment by mrh0** [comment]
This is just a worse Electric Motor
