### ISSUE TITLE
Motor caps current at 256fe/t and starves itself [Ver. 1.0.0]

### ISSUE THREAD

**Issue by abertym** [mrh0/createaddition#801]
**Describe the bug**
Electric motor does not allow for more than 256fe/t input on any given side of the block, even if it needs it. 
When putting 2 connectors on the motor and wiring them both to the same power source, the motor is then able to source enough current to run. This is because one connector will bring the motor 256fe/t, and the other connector will supply the rest of the required current.

**To Reproduce**
Take any power source than can supply more fe/t than the electric motor needs, and connect it to the motor via any wire and a connector on each side (large or small). To specify, that is 1 connector on the power source, and 1 connector on the motor. Set the motor speed anywhere above 137rpm, the higher the rpm, the clearer the issue. 160rpm is good. Even though the power source can supply more than 256 fe/t, the motor is starving itself of energy.

I have done this with multiple different ways of power transmission, including placing an accumulator (with sufficient power) directly underneath it, using Immersive Engineering's wiring system, and putting a fully juiced Flux Cell from Thermal right next to it. All of these yield the same result: the motor stores some energy, spins for a bit, chokes and stops spinning, and repeat. Only if two or more power connections are supplying it at the same time is it able to effectively run.

**Additional context**
- Game version: 1.18.2
- Mod version: 1.0.0
- Forge version: 40.2.17
- Create version: 0.5.1.f

**Comment by mrh0** [comment]
i no longer support 1.18
