### ISSUE TITLE
Latest version results in datapack error when trying to load a new world and a crash when creating new ones.

### ISSUE THREAD

**Issue by Nereithr** [mrh0/createaddition#804]
**Describe the bug**
Attempting to load a world with Crafts and Additions v1.20 - 1.2.4 results in the following datapack-related error:

<details>
  <summary>Image</summary>
  
![unknown_2024 06 23-12 28](https://github.com/mrh0/createaddition/assets/72263884/767f14b9-6639-4267-be58-e026c4c37929)
  
</details>

Attempting to create a new world results in a crash. [Here is the log file.](https://github.com/user-attachments/files/15944302/latest.log)

Downpatching to version 1.20.-1.2.3 fixes the issue.

**To Reproduce**

1. Attempt to load an old world with Crafts and Additions v1.2.3
2. Observe
3. Quit out and attempt to create a new world
4. Crash

**Additional context**
- Mod version: 1.20.1-1.2.4
- Forge version: NeoForge 47.1.106/Forge 47.3.0
- Create version: 0.5.1.f

**Comment by Maxi90909** [comment]
If this is correct I wasted 6 hours and 30min trying to find this issue

**Comment by Maxi90909** [comment]
Yes I wasted indeed 6,5 hours. Thanks man.

**Comment by mrh0** [comment]
Fixed in 1.2.4d
