### ISSUE TITLE
Errors in currently selected datapacks prevented the world from loading. You can either try to load it with only the vanilla data pack ("safe mode") or go back to the title screen to manually fix it

### ISSUE THREAD

**Issue by WesleyWerter** [mrh0/createaddition#805]
**Describe the bug**
Unable to load existing saves.

**To Reproduce**
Load any save game

**Additional context**
- Mod version: 1.2.4
- Forge version: 47.3.1
- Create version: 0.5.1

**Comment by Mjolinir** [comment]
Additional info from me, same issue:

Describe the bug
Unable to load any MC 1.20.1 world with current mod ver installed
[latest.log](https://github.com/user-attachments/files/16021520/latest.log)
.

To Reproduce
Load any save game

Additional context

    Mod version: 1.2.4a, b, or c
    Forge version: 47.2.21
    Create version: 0.5.1

If I revert to 1.2.3 the world will load. Attached latest.log.

**Comment by mrh0** [comment]
fixed in 1.2.4d
