### ISSUE TITLE
I keep getting a data pack arror after updating the mod

### ISSUE THREAD

**Issue by ScottishEngineer** [mrh0/createaddition#806]
**Describe the bug**
After updating the mod and loading my world i got the enter safe mod screen, after pressing the safe mode button it says failed to load world in safe mode would contains invalid or corrupted save data

**To Reproduce**
To be fair I have a lot of mods on but all i have done was load a world that had the previous version of the mod on and it cant load with the updated version of it
**Additional context**
- Mod version: 1.2.4
- Forge version: 43.3.1
- Create version:0.5.1
I have screenshots if you need them

**Comment by festro** [comment]
Getting the same here, ended up deleting the world because I thought it was bad.
Nice to know this was the culprit.

**Comment by Aspyro** [comment]
I have the same error under 1.20.1 NeoForge 47.1.106. I traced back this mod being the culprit by rolling back all mods that updated the same day and updating them all one by one.
As to what in the update caused the problem, I don't know. But here is my log, see the latest lines for the world load error.
[2024-06-24-4.log](https://github.com/user-attachments/files/15960567/2024-06-24-4.log)

**Comment by Aspyro** [comment]
Updated my mods with version `1.20.1-1.2.4b` and get the same error as in `1.20.1-1.2.4`. Rolled back to `1.20.1-1.2.2` and it works fine.
Here are logs of me loading the game then a world with both versions just now :
[1.20.1-1.2.4b.log](https://github.com/user-attachments/files/15967989/latest.log)
[1.20.1-1.2.2.log](https://github.com/user-attachments/files/15968160/latest.log)

**Comment by Aspyro** [comment]
It does not happen to me anymore with version `1.20.1-1.2.4c` of the mod, so I believe it is fixed.
Thank you for your work 👍

**Comment by mrh0** [comment]
Fixed in 1.2.4d
