### ISSUE TITLE
Fluid error after updating the mod and trying to make a new world

### ISSUE THREAD

**Issue by ScottishEngineer** [mrh0/createaddition#807]
**Describe the bug**
[crash-2024-06-24_03.03.52-client.txt](https://github.com/user-attachments/files/15953487/crash-2024-06-24_03.03.52-client.txt)

**To Reproduce**
All i am doing is trying to make a new world and that error code pops up 

**Additional context**
- Mod version:1.2.4
- Forge version:47.3.1
- Create version:0.5.1
I hope the crash file i sent will work if not @ me on the discord, name is Scottish Engineer 
so far the crash log is saying moderfix and create are causing the issue but i disabled Moderfix and it still happend and i cant disable create and have this mod on so yeah

**Comment by 5Cascade** [comment]
I had a similar issue with this mod and Thermal Foundation. I fixed it by downgrading Create: Crafts and Additions from version 1.2.4 to 1.2.3. Someone said in the CoFH discord it was to do with this mod being created with MCreator. Hope this helps.

**Comment by mrh0** [comment]
Fixed in 1.2.4d
