### ISSUE TITLE
Can't craft the Pale Gold Amulet

### ISSUE THREAD

**Issue by ELPatitoLoco** [mrh0/createaddition#808]
**Describe the bug**
Can't craft the pale gold amulet

**To Reproduce**
Try to craft it in fabric 1.20.1, it doesn't let you.
![imagen_2024-06-25_140843948](https://github.com/mrh0/createaddition/assets/130762237/3d2cd96d-c9b0-4d6b-890c-20f799beaaad)

**Additional context**
- Mod version: createaddition-fabric-1.20.1-1.2.3
- Fabric version: [1.20.1] Fabric API 0.92.2+1.20.1
- Create version: Create 1.20.1 v0.5.1.f Patch 1 (create fabric)

**Comment by mrh0** [comment]
this has been fixed
