### ISSUE TITLE
1.20.1 Neoforge - Create Craft and Additions 1.2.3+ Always Fails To Load Versions In Existing World

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [mrh0/createaddition#809]
https://mclo.gs/gXI4aJh

**Comment by Lana-chan** [comment]
same datapack failure error in Forge 47.3.0 with additions v1.2.4c when attempting to load worldgen (either starting a server or by clicking "singleplayer" in client with no worlds), as mentioned elsewhere the same modpack but with additions v1.2.2 does not cause the issue

**Comment by P3rf3ctXZer0** [comment]
Fixed in createaddition-1.20.1-1.2.4c.jar

**Comment by P3rf3ctXZer0** [comment]
Nevermind might still be an issue. Seems to only trigger after you add the mod then add any third party mod then try entering an already built world. With third party mod removed ... its a chain fail trigger I think.

**Comment by Lana-chan** [comment]
because the recipe that causes the issue is processed by create at worldgen init time

1.2.4d's changelog is that the recipe was reverted, uploaded 3 days ago to modrinth, i haven't tried it yet myself

**Comment by P3rf3ctXZer0** [comment]
Actually this mod was not the cause of my issue ... anymore best of luck. It was an issue prior.
