### ISSUE TITLE
Treated Wood filling recipe is not working

### ISSUE THREAD

**Issue by LunarFactory** [mrh0/createaddition#812]
**Describe the bug**

I can't find treated wood filling recipe in world, and it can't be crafted.

**To Reproduce**

load game with mods.

**Additional context**
- Mod version: 1.2.4c
- Forge version: 47.1.106 Neoforge(47.3.3 forge)
- Create version: 0.5.1f

Here's my log
[latest.log](https://github.com/user-attachments/files/16042659/latest.log)

**Comment by mrh0** [comment]
Fixed in 1.2.4d
