### ISSUE TITLE
Custom modpack crashes on startup: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'

### ISSUE THREAD

**Issue by TRRT004** [mrh0/createaddition#814]
Describe the Bug
The game crashes on startup (see crash report for more details

Reproduction Steps
Install the modpack (curseforge import file attached below)
[Tweak.That.Create-1.0.0.zip](https://github.com/user-attachments/files/16059520/Tweak.That.Create-1.0.0.zip)
Launch minecraft

Expected Result
The game boots up

Crash Report or Log
https://pastebin.com/CKpYMPmb

Operating System
Windows 11

Mod Version
createaddition-fabric+1.19.2-1.2.3

Create Version
0.5.1f

Fabric
Launcher 0.5.11
fabric-api-0.77.0+1.19.2

Minecraft Version
1.19.2

**Comment by skippyall** [comment]
In the crash report it says that the Create Crafts & Additions version is 20230211a. Please make sure that you are really using the latest version

**Comment by samuelh2005** [comment]
Your using a version of Create that is incompatible with the version of Create Crafts and Additions.

The log says:

```
Caused by: java.lang.NoClassDefFoundError: com/simibubi/create/content/contraptions/fluids/tank/BoilerHeaters$Heater
	at com.mrh0.createaddition.CreateAddition.onInitialize(CreateAddition.java:43)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 7 more
```

This means Create Crafts and Additions is trying to use a feature of Create which does not exist in the version of Create you are using.

Please update both Create and Create Crafts and Additions. You should compare each versions' release date to make sure they are the same or make sure Create Crafts and Addition is newer than Create.
