### ISSUE TITLE
game will crash when running 1.2.4c (most recent version)

### ISSUE THREAD

**Issue by poly-1810** [mrh0/createaddition#815]
**Describe the bug**
when running the most recent release for 1.20.1(neo)forge, the game crashes upon loading worlds or creating new ones due to "cannot modify empty stack"

**To Reproduce**
install mod alongside create, run game, try to load or create new world

**Additional context**
- Mod version: 1.2.4c
- Forge version: 47.1.103 neoforge
- Create version: 0.5.1f
- Crash report: [crash-2024-07-01_18.32.19-client.txt](https://github.com/user-attachments/files/16059869/crash-2024-07-01_18.32.19-client.txt)

**Comment by mrh0** [comment]
try 1.2.4d

**Comment by tobi1449** [comment]
Is it intentional that 1.2.4d has not been uploaded to CurseForge yet?

**Comment by mrh0** [comment]
No it was not, but its up now
