### ISSUE TITLE
Machines not outputting enough power

### ISSUE THREAD

**Issue by Glowstonesword** [mrh0/createaddition#82]
**Describe the bug**
No Create Additions machines can output power faster than roughly 408FE/t (creative generator, alternator)

**To Reproduce**
Steps to reproduce the behavior: Attach a creative generator (or other 256rpm) source to an Alternator with config changed to up the FE/t. Connect to a power source (directly, with connectors, or with IE wire coils; any power transfer works)

**Additional context**
- Mod version: 20210517a
- Forge version: 36.1.24
- Create version: 0.3.1c
- Related to https://github.com/mrh0/createaddition/issues/27

**Comment by mrh0** [comment]
20210625a completely rework the energy system, hopefully, this will resolve your issues.
