### ISSUE TITLE
Create Additions 1.2.4c is incompatible with Immersive Engineering

### ISSUE THREAD

**Issue by TheOneSalem** [mrh0/createaddition#820]
**Describe the bug**
I once had Immersive Engineering running alongside Create but, after a while the server began to time out with a rendering error. I since removed Immersive Engineering everything's worked fine. Lately I've been wanting to bridge compatibility with ore processing and found IE on the list of supported mods. So, I thought I'd try it again and immediately crashed in single player during world creation. So, digging into it, I reached out for some help and learned that the issue isn't Create itself conflicting with IE but, Create: Additions. 
   
  This is my first time learning how to locate exact issues and reporting them. If you need any additional information, I can post the log. 

**To Reproduce**
I've reproduced this numerous times while trying to figure out what exactly the problem is. Either of the most recent versions of Immersive Engineering causes this crash although I have not tried a previous version of Create: Additions yet. 

**Additional context**
- Mod version: Createaddition 1.20.1-1.2.4c
- Forge version: 47.3.1
- Create version: 0.5.1f

**Comment by Luviam** [comment]
Also having this happen to me with just the following:
- create-1.20.1-0.5.1.f
- createaddition-1.20.1-1.2.4c
- ImmersiveEngineering-1.20.1-10.1.0-171
- Forge 47.3.5
[latest.log](https://github.com/user-attachments/files/16138370/latest.log)

Edit: Lowest version of Additions I avoided the crash on is 1.2.3

**Comment by karouvirae** [comment]
Just a heads-up from someone who's stumbled upon this: modrinth has a newer version that is compatible (1.2.4d)

**Comment by TheOneSalem** [comment]
Oh awesome! I didn't realize there was a compatible version out. Thanks for the info!

**Comment by mrh0** [comment]
Fixed in 1.2.4d
