### ISSUE TITLE
Make Pale Gold Amulet consumed upon use

### ISSUE THREAD

**Issue by MarioSMB** [mrh0/createaddition#832]
The Pale Gold Amulet upsets gameplay balance by allowing virtual immortality... what if it broke when providing the effect to keep it from being infinitely used?

**Comment by mrh0** [comment]
It was not intentional to make it that powerful, ive nerfed it in the latest release

**Comment by MarioSMB** [comment]
Glad to hear that, thanks!

**Comment by MarioSMB** [comment]
The permanent Luck buff is powerful enough that some may intentionally keep their health low while exploring to ensure structures generate with more loot (weirdly it affects chest loot!), but other than that this seems to have helped balance it out a little.  
I'll go ahead and close the issue, thanks for addressing it so quickly!
