### ISSUE TITLE
inductive heater does not power furnace burner that's in the furnace engine

### ISSUE THREAD

**Issue by RobinVanTol** [mrh0/createaddition#85]
**Describe the bug**
I enable being able to use the inductive heater in the config but in game it does not work, just set it up in creative but the furnace burner does not start burning, it starts burning when i break the furnace engine so the setup for the furnace burner is correct, i assume changing the config didn't enable it.

**To Reproduce**
connect a creative gen to a inductive heater to a furnace burner to a furnace engine to a flywheel and watch it do nothing

**Additional context**
- Mod version: 20210517a
- Forge version: 36.1.32
- Create version: v0.3.1c

**Comment by mrh0** [comment]
Solved in 20210625a (although the heater still need an absurd amount of power to run the Furnace Engine)
