### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by FrannDzs** [mrh0/createaddition#86]
Hi, how are you? I really love your mod, and I have a suggestion.
I see you use wires and objects similar to Immersive Engineering, why instead of recreating the objects don't you make them compatible with? I know it took some work but it would be a way to unify 3 great mods in one shot?

**Comment by mrh0** [comment]
Would be neat, but to really feasible.

**Comment by FrannDzs** [comment]
> Would be neat, but to really feasible.

It would be great. I wish you a good day.
