### ISSUE TITLE
Power does not transfer to some devices after a certain distance

### ISSUE THREAD

**Issue by eyemotif** [mrh0/createaddition#87]
**Describe the bug**
A power source will no longer send power to a device that is about 150 blocks away. My testing showed that a creative generator at -91 64 would not transfer power to a refined storage controller at 15 123, but would at 5 118. But, once I add an electric motor to the connector the controller is attatched to, the connector updates and power is sent to both devices.

**To Reproduce**
Place a creative power source 150(+) blocks away from a device drawing power and connect them using wire.

**Additional context**
- Mod version: 20210517a
- Forge version: 36.1.23
- Create version: 0.3.1c

**Comment by mrh0** [comment]
Fixed in 20210625a
