### ISSUE TITLE
Broken connectors do not drop wires

### ISSUE THREAD

**Issue by eyemotif** [mrh0/createaddition#88]
**Describe the bug**
Breaking the block a connector is placed on will break the connector but not drop its wire(s).

**To Reproduce**
Place a connector on a block, connect wire to the connector, and break the block.

**Additional context**
- Mod version: 20210517a
- Forge version: 36.1.23
- Create version: 0.3.1c

**Comment by mrh0** [comment]
Fixed in 20210626a
