### ISSUE TITLE
Vertical wires don't show up

### ISSUE THREAD

**Issue by Ch1216** [mrh0/createaddition#89]
**Describe the bug**
When making a vertical wire by connecting two connectors vertically, wires don't appear

**To Reproduce**
1. Place 2 connectors attached to walls, 1 under the other
2. Connect the 2 connectors
No wire

https://user-images.githubusercontent.com/68875386/123476509-cfb83c80-d5ca-11eb-96a2-555c1c6aa9d6.mp4

**Additional context**
- Mod version: 20210625a
- Forge version: 36.1.0
- Create version: 0.3.1c

**Comment by mrh0** [comment]
Fixed in 20210626a

**Comment by Ch1216** [comment]
this seems to be back in 20210713a @mrh0

**Comment by Ch1216** [comment]
It has been fixed in 20210731a, hope it doesnt show up again
