### ISSUE TITLE
seed_oil and flowing_seed_oil blocks need minecraft:water fluid tag

### ISSUE THREAD

**Issue by erisdev** [mrh0/createaddition#91]
Without this tag, the player just falls straight through it and there is no fog effect. It's a fluid tag, so it lives in `data/minecraft/tags/fluids/water.json`. Apparently, to get the appropriate fog color you'll have to [hard code it](https://github.com/Creators-of-Create/Create/blob/2cfb84995f0ca991d5520e95985b2b71604d0228/src/main/java/com/simibubi/create/events/ClientEvents.java#L283).

**Comment by mrh0** [comment]
Thanks for the thorough report!

**Comment by erisdev** [comment]
I actually have another thought about this. Do you think it would be good to make seed oil a virtual fluid, like milk or tea? There'd be no fluid block for it, but it would still have a bucket and work with Create's machinery. I can try and do a PR later.

**Comment by mrh0** [comment]
Fixed in 20210711a
