### ISSUE TITLE
Wires stop transmitting power.

### ISSUE THREAD

**Issue by rradt2001** [mrh0/createaddition#92]
**Describe the bug**
Wires stopped transmitting power to a refined storage system after an unknown amount of time, this is not caused by server restarts as I have checked this manually.

**To Reproduce**
1. Use wires to plug into RF controller (and presumably other blocks)
2. Wait.
I am sorry to not give specifics, but I have yet to find any specific action that causes this behavior (though I think it might have to do with the chunks being unloaded)

**Additional context**
- Mod version: 1.16.5-20210517a
- Forge version: 36.1.0
- Create version: mc1.16.5_v0.3.1c+151

**Comment by mrh0** [comment]
I've been unable to reproduce this.
