### ISSUE TITLE
Optifine Incompatibility: Connecting stuff with wire spools causes all entities to stop rendering. 

### ISSUE THREAD

**Issue by Hunkydoodle** [mrh0/createaddition#93]
Wire connections cause all entities to stop rendering. the game must be restarted in order for objects to render again. I AM using optifine which is what seems to be causing the issue. obviously this should not be a priority, but it would be nice if this mod had optifine compatibility.

-Forge version: release 1.16.5-forge-36.1.32
-Mod version: createaddition-1.16.5-20210626a
-OptiForge version: OptiForge-MC1.16.5-0.5.5
-Optifine version: OptiFine_1.16.5_HD_U_G8

**Comment by mrh0** [comment]
That's strange, are you using any shaders? If so does it work without?

**Comment by mrh0** [comment]
![image](https://user-images.githubusercontent.com/20174184/124359551-d4fa3480-dc25-11eb-9be0-ff87030a9789.png)
Works for me, Must be your shader pack´, try using another shader pack.
