### ISSUE TITLE
Electric Motors consume power incorrectly

### ISSUE THREAD

**Issue by Jelllllly** [mrh0/createaddition#95]
The Electric Motor block does not consume any energy when set to negative RPM.
It still requires non-zero energy to be provided, however once this condition is satisfied, the motor keeps running even after disconnecting the power supply completely.
When set back to positive RPM, the Motor consumes the energy, and stops as expected.

**To Reproduce**
- Place down an Electric Motor
- Provide it with power
- Set it's target RPM to any negative number
- Wait for it to start spinning
- Observe the power is not being drawn
- _This can also be observed with the engineering goggles, reading the power consumption as 0_

**Additional context**
- Mod version: 1.16.5-20210626a
- Forge version: 1.16.5 36.1.32
- Create version: 1.16.5 v0.3.1c+151

**Comment by mrh0** [comment]
Fixed in 20210711a
