### ISSUE TITLE
Mod crashes on new create update

### ISSUE THREAD

**Issue by ModernGamingWorld** [mrh0/createaddition#96]
**Describe the bug**

![2021-07-10_18 05 11](https://user-images.githubusercontent.com/75923060/125178334-6844e400-e1a9-11eb-833e-4935db97b773.png)

**To Reproduce**
Launched game and crashed

**Additional context**
- Mod version: latest
- Forge version: 36.1.32
- Create version: 1.16.5 v0.3.2

**Comment by P3rf3ctXZer0** [comment]
I second this.

**Comment by P3rf3ctXZer0** [comment]
@ModernGamingWorld you spelled Crate not Create just fyi.

**Comment by AcrazyD** [comment]
Third, noticed the issue and thought it was a fluke

**Comment by dajiuji** [comment]
Me too, it seems that I am not alone.

**Comment by mrh0** [comment]
Updated in 20210711a
