### ISSUE TITLE
create crafts & additions crashes with the new update

### ISSUE THREAD

**Issue by thecatking9274** [mrh0/createaddition#97]
**Describe the bug**
when i load the game with the new create update and create crafts & additions it crashs

**To Reproduce**
1. download create crafts & additions
2. update the new create update

**Additional context**
- Mod version: latest
- Forge version: latest
- Create version: latest
crash log:
https://pastebin.pl/view/2dac8776

**Comment by mrh0** [comment]
Updated in 20210711a
